<?php declare(strict_types=1);
require_once __DIR__.'/commercial-lines.php';
$credit=$kind===$creditKind;
$label=match($kind){'invoice'=>'Invoice','bill'=>'Bill','customer_credit'=>'Credit note',default=>'Supplier credit'};
$names=pl_starter_options($accounts);
?>
<div class="py-5"><section class="rounded-panel border border-border bg-surface">
<?php pl_ui_document_header(($correct?'Correct ':($document?'':'New ')).($document?$document['number']:$label),$correct?'posted':'draft',static function () use ($correct,$path,$postingPreview,$filters): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_url($path,$filters)) ?>">Cancel</a>
<?php if ($correct): ?><button class="btn btn-primary" form="ar-document-editor">Reverse and post correction</button>
<?php else: ?><button class="btn btn-secondary" form="ar-document-editor">Save draft for review</button><button class="btn btn-secondary" form="ar-document-editor" name="editor_action" value="preview">Update posting preview</button>
<?php if ($postingPreview): ?><button class="btn btn-primary" form="ar-document-editor" name="editor_action" value="post_reviewed_document" data-review-confirm>Post</button><?php endif; endif; ?>
<?php }); ?>
<form id="ar-document-editor" class="doc-body" method="post" action="<?= pl_e(pl_url($path,['return_filters'=>$filters])) ?>" data-commercial-form data-reviewed-form data-tax-context="<?= pl_e(json_encode($taxContext,JSON_THROW_ON_ERROR)) ?>">
<?php pl_starter_form($company,$correct?'correct':'save',['id'=>$document['id']??0,'revision'=>$form['input']['revision']??$document['revision']??0,'kind'=>$kind,'original_document_id'=>$v['original_document_id']??0,'request_key'=>$form['input']['request_key']??bin2hex(random_bytes(20))]); ?>
<?php if ($form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?><p>Your entered values are retained.<?php if ($document): ?> <a href="<?= pl_e(pl_url($path,['id'=>$document['id'],'edit'=>'1','return_filters'=>$filters])) ?>">Reload the saved document</a> before resolving a revision conflict.<?php endif; ?></p></div><?php endif; ?>
<?php if ($original): ?><section><div class="alert alert-info">Credit against <a href="<?= pl_e(pl_url($path,['id'=>$original['id']])) ?>"><?= pl_e($original['number']) ?></a>, revision <?= (int)$original['revision'] ?>. Prices <?= $original['price_mode']==='inclusive'?'include':'exclude' ?> tax, matching the original. Choose the original line for each taxed credit.</div><details class="mt-2"><summary class="text-sm">Original lines and remaining credit basis</summary><?php pl_ui_table(['Original line','Description','Net','Tax'],static function () use ($original): void { foreach ($original['lines'] as $line): ?><tr><td><?= (int)$line['line_number'] ?></td><td><?= pl_e($line['description']) ?></td><td class="amount"><?= pl_e(pl_money($line['line_total'])) ?></td><td class="amount"><?= pl_e(pl_money($line['tax_amount'])) ?></td></tr><?php endforeach; },'Original document lines'); ?><p class="text-xs text-ink-muted mt-2">These are original amounts. Preview checks the remaining net and tax amounts after earlier credits.</p></details></section><?php endif; ?>
<section class="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
<?php pl_starter_select($isAr?'Customer':'Vendor','party_id',pl_starter_options(array_filter($parties,static fn(array $p):bool=>(bool)$p[$isAr?'is_customer':'is_vendor']),'legal_name'),$v['party_id']??'');
pl_starter_field('Document date','date',$v['date']??$v['document_date']??gmdate('Y-m-d'),'date'); pl_starter_field('Due date','due_date',$v['due_date']??gmdate('Y-m-d'),'date'); pl_starter_field('Currency','currency',$v['currency']??$company['currency']);
if ($credit) { pl_starter_hidden('price_mode',$v['price_mode']??$original['price_mode']??'exclusive'); } else { pl_starter_select('Entered prices','price_mode',['exclusive'=>'Exclude tax','inclusive'=>'Include tax'],$v['price_mode']??$priceMode); }
pl_starter_field('Reference','reference',$v['reference']??'','text',false); pl_starter_field('Terms','terms',$v['terms']??'','text',false); pl_starter_field('Notes','notes',$v['notes']??'','text',false); ?>
</section>
<details<?= $correct || ($v['rate']??'')!=='' || ($v['rounding_account_id']??'')!==''?' open':'' ?>><summary class="text-sm">More options<?= $correct?' and correction reason':'' ?></summary><div class="grid grid-cols-2 md:grid-cols-3 gap-4 mt-3">
<?php pl_starter_select('FX rounding account (optional)','rounding_account_id',pl_starter_options(array_filter($accounts,static fn(array $a):bool=>$a['type']==='expense')),$v['rounding_account_id']??'',false); pl_starter_field($correct?'Replacement rate (base per foreign unit)':'Manual exchange rate (blank for domestic or recorded rate)','rate',$v['rate']??'','text',false);
if ($correct) { pl_starter_field('Correction reason','reason',$v['reason']??''); pl_starter_field('Reversal date (blank = today)','reversal_date',$v['reversal_date']??'','date',false); } ?>
</div><?php if ($correct): ?><p class="text-xs text-ink-muted mt-2">This keeps the document identity and records a linked reversal and replacement. Dependent payments and credits must be reversed first; closed periods remain protected.</p><?php endif; ?></details>
<section><h2 class="section-title mb-2">Lines</h2><?php pl_ui_commercial_lines($v['lines']??[],['account_id'=>$accountOptions,'product_id'=>pl_starter_options($products),'tax_code_id'=>pl_starter_options($taxCodes)],$credit); ?>
<p class="text-xs text-ink-muted mt-3">Amounts allow four decimal places. Unit prices follow the tax entry mode above. <?= $isAr?'A stock invoice also issues the goods and records their cost.':'For stock purchases, receive goods in Purchasing before matching the supplier bill.' ?></p></section>
<div class="flex justify-end" data-commercial-tax-totals><?php pl_ui_totals(['Subtotal'=>$postingPreview?pl_money($postingPreview['document']['subtotal']):'—','Tax'=>$postingPreview?pl_money($postingPreview['document']['tax_total']):'—','Total ('.($v['currency']??$company['currency']).')'=>$postingPreview?pl_money($postingPreview['document']['total']):'—']); ?></div>
<?php if ($postingPreview): ?><section data-review-preview>
<details open><summary class="section-title mb-2">Posting preview</summary><?php pl_ui_table(['Account','Debit ('.$postingPreview['currency'].')','Credit ('.$postingPreview['currency'].')'],static function () use ($postingPreview,$names): void { foreach ($postingPreview['lines'] as $line): ?><tr><td><?= pl_e($names[$line['account_id']]??('Account '.$line['account_id'])) ?></td><td class="amount"><?= pl_e(pl_money($line['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($line['credit'])) ?></td></tr><?php endforeach; },'Customer or supplier document posting'); ?></details></section><?php endif; ?>
<?php if (($postingPreview['stock']??[])!==[]): ?><section data-review-preview><details open><summary class="section-title mb-2">Stock and cost effects</summary>
<?php foreach ($postingPreview['stock'] as $stock): ?><p class="text-xs text-ink-muted my-2"><?= pl_e($stock['product_name']) ?> · Quantity change <?= pl_e($stock['quantity_delta']) ?> · Carrying value change <?= pl_e($company['currency'].' '.$stock['value_delta']) ?></p>
<?php pl_ui_table(['Account','Debit','Credit'],static function () use ($stock,$names): void { foreach ($stock['movement']['journal']['lines']??[] as $line): ?><tr><td><?= pl_e($names[$line['account_id']]??('Account '.$line['account_id'])) ?></td><td class="amount"><?= pl_e(pl_money($line['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($line['credit'])) ?></td></tr><?php endforeach; },'Linked stock journal effect'); ?>
<?php endforeach; ?></details></section><?php endif; ?>
<p class="text-xs text-ink-muted" data-review-message aria-live="polite">Posting adds this transaction to reports. A saved draft does not change your books.</p>
</form></section></div>
