<?php declare(strict_types=1);
$recordStatus=str_replace('_','-',$document['payment_status']??$document['status']);
$canAct=pl_can_write($company);
$canSettle=$document['kind']===$normalKind && $document['journal_id'] && !$document['reversal_journal_id'] && bccomp($document['outstanding_fc'],'0',4)>0;
$names=pl_starter_options($accounts);
?>
<div class="py-5">
<a class="btn btn-ghost mb-3" href="<?= pl_e(pl_url($path)) ?>"><?= pl_icon('arrow-left') ?> Back to <?= $isAr?'invoices':'bills' ?></a>
<?php if (pl_web_text($_GET,'return_report')==='ageing'): ?><a class="btn btn-ghost mb-3" href="<?= pl_e(pl_url('/reports/ageing',['direction'=>$isAr?'receivable':'payable','as_of'=>$report['as_of']])) ?>">Back to ageing report</a><?php endif; ?>
<section class="rounded-panel border border-border bg-surface">
<?php pl_ui_document_header($document['number'],$recordStatus,static function () use ($document,$path,$canAct,$canSettle,$isAr): void { ?>
<button class="btn btn-ghost" type="button" data-print-document hidden><?= pl_icon('printer') ?> Print</button>
<?php if ($canAct && $document['status']==='draft'): ?><a class="btn btn-primary" href="<?= pl_e(pl_url($path,['id'=>$document['id'],'edit'=>'1'])) ?>">Edit draft</a><?php endif; ?>
<?php if ($canAct && $canSettle): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url($path,['new'=>'1','credit_for'=>$document['id']])) ?>">Create <?= $isAr?'credit note':'supplier credit' ?></a><a class="btn btn-primary" href="<?= pl_e(pl_url($path,['settle'=>'1','party_id'=>$document['party_id'],'currency'=>$document['currency']])) ?>"><?= $isAr?'Record customer receipt':'Record supplier payment' ?></a><?php endif; ?>
<?php if ($document['reversal_journal_id']): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/journals/detail',['id'=>$document['reversal_journal_id']])) ?>">View reversing entry</a><?php endif; ?>
<?php }); ?>
<div class="doc-body">
<?php if ($form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
<?php if ($document['reversal_journal_id']): pl_ui_strip('This document has been reversed. Its original posting and linked reversal remain in the history.','warning'); endif; ?>
<section><p class="text-sm text-ink-muted mb-3"><?= pl_e($company['name'].' · '.ucwords(str_replace('_',' ',$document['kind']))) ?></p>
<dl class="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
<?php foreach ([$isAr?'Customer':'Vendor'=>$document['party']['legal_name'],'Document date'=>pl_date_label($document['document_date']),'Due date'=>pl_date_label($document['due_date']),'Currency'=>$document['currency'],'Entered prices'=>$document['price_mode']==='inclusive'?'Include tax':'Exclude tax','Reference'=>$document['reference']?:'—','Terms'=>$document['terms']?:'—','Revision'=>(string)$document['revision']] as $label=>$value): ?><div><dt class="field-label"><?= pl_e($label) ?></dt><dd class="text-sm font-medium mt-0.5"><?= pl_e($value) ?></dd></div><?php endforeach; ?>
</dl></section>
<?php if ($document['is_credit'] && $original): ?><p class="text-sm">Credit against <a class="link" href="<?= pl_e(pl_url($path,['id'=>$original['id']])) ?>"><?= pl_e($original['number']) ?></a>, original revision <?= (int)$document['original_revision'] ?>.</p><?php endif; ?>
<section><h2 class="section-title mb-2">Lines</h2>
<?php pl_ui_table(['Line / description','Account','Quantity','Entered unit price','Tax','Net'],static function () use ($document,$names): void { foreach ($document['lines'] as $line): ?><tr><td><span class="row-title"><?= pl_e($line['description']) ?></span><span class="row-sub">Line <?= (int)$line['line_number'] ?></span></td><td><?= pl_e($names[$line['account_id']]??('Account '.$line['account_id'])) ?></td><td class="amount"><?= pl_e($line['quantity']) ?></td><td class="amount"><?= pl_e(pl_money($line['unit_price'])) ?></td><td class="amount"><?= pl_e(pl_money($line['tax_amount'])) ?><span class="row-sub"><?= pl_e($line['tax_label']??'') ?></span></td><td class="amount"><?= pl_e(pl_money($line['line_total'])) ?></td></tr><?php endforeach; },'Document lines'); ?>
<div class="flex flex-wrap justify-between items-start gap-4 mt-3">
<dl class="dgrid"><?php if ($document['journal_id'] && !$document['is_credit'] && !$document['reversal_journal_id']): ?><div class="dgrid-row"><dt>Amount remaining</dt><dd class="amount"><?= pl_e($document['currency'].' '.pl_money($document['outstanding_fc'])) ?></dd></div><?php endif; ?><div class="dgrid-row"><dt>Notes</dt><dd><?= pl_e($document['notes']?:'—') ?></dd></div></dl>
<?php pl_ui_totals(['Subtotal'=>pl_money($document['subtotal']),'Tax'=>pl_money($document['tax_total']),'Total ('.$document['currency'].')'=>pl_money($document['total'])]); ?></div>
<p class="text-xs text-ink-muted mt-2"><?= $document['status']==='draft'?'Posting adds this transaction to reports. A saved draft does not change your books.':'Net, tax and total are preserved from the posted revision. Posted entries cannot be edited.' ?></p></section>
<?php if ($canAct && $document['status']==='draft'): ?><section><h2 class="section-title mb-2">Post saved draft</h2><form method="post" action="<?= pl_e(pl_url($path)) ?>"><?php pl_starter_form($company,'post',['id'=>$document['id'],'revision'=>$postInput['revision']??$document['revision'],'request_key'=>$postInput['request_key']??bin2hex(random_bytes(20))]); ?><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><?php pl_starter_field('Manual exchange rate (blank for domestic or recorded rate)','rate',$postInput['rate']??'','text',false); ?></div><button class="btn btn-primary mt-3">Post <?= pl_e(str_replace('_',' ',$document['kind'])) ?></button></form></section><?php endif; ?>
<?php if ($recordJournal): ?><section><h2 class="section-title mb-2">Journal effect</h2><?php pl_ui_table(['Account','Debit ('.$company['currency'].')','Credit ('.$company['currency'].')'],static function () use ($recordJournal): void { foreach ($recordJournal['lines'] as $line): ?><tr><td><?= pl_e($line['code'].' · '.$line['name']) ?></td><td class="amount"><?= pl_e(pl_money($line['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($line['credit'])) ?></td></tr><?php endforeach; },'Posted financial journal'); ?><a class="link text-sm" href="<?= pl_e(pl_url('/journals/detail',['id'=>$document['journal_id']])) ?>">View journal and source reference</a></section><?php endif; ?>
<?php if ($settlements): ?><section><h2 class="section-title mb-2">Ledger activity</h2>
<?php foreach ($settlements as $entry): ?><div class="border-b border-border py-3"><p class="text-sm"><a class="link" href="<?= pl_e(pl_url('/journals/detail',['id'=>$entry['journal_id']])) ?>"><?= pl_e($entry['posting_date'].' · '.ucfirst(str_replace('_',' ',$entry['kind']))) ?></a> · <span class="amount"><?= pl_e($document['currency'].' '.pl_money($entry['amount_fc'])) ?></span><?= $entry['already_reversed']?' · Reversed':'' ?></p>
<?php if ($entry['credit_document_id']): ?><a class="link text-sm" href="<?= pl_e(pl_url($path,['id'=>$entry['credit_document_id']])) ?>">View <?= pl_e(pl_ar_document_number((int)$entry['credit_document_id'],$entry['credit_kind'])) ?></a><?php endif; ?>
<?php if ($canAct && $document['kind']===$normalKind && !$entry['already_reversed'] && !$entry['credit_document_id'] && in_array($entry['source_type'],['open_item_settlement','open_item_batch_settlement'],true) && $entry['kind']==='allocation'): $paymentReversal=$failedAction==='reverse_payment' && (int)($form['input']['journal_id']??0)===(int)$entry['journal_id']?$form['input']:[]; ?><details class="mt-2" <?= $paymentReversal?'open':'' ?>><summary class="text-sm">Reverse this payment</summary><p class="text-xs text-ink-muted my-3">This reverses the whole payment and all its allocations, including allocations to other documents.</p><form method="post" action="<?= pl_e(pl_url($path)) ?>"><?php pl_starter_form($company,'reverse_payment',['id'=>$document['id'],'journal_id'=>$entry['journal_id'],'request_key'=>$paymentReversal['request_key']??bin2hex(random_bytes(20))]); ?><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><?php pl_starter_field('Reason','reason',$paymentReversal['reason']??''); pl_starter_field('Reversal date (blank = today)','date',$paymentReversal['date']??'','date',false); ?></div><button class="btn btn-secondary mt-3">Reverse payment</button></form></details><?php endif; ?></div><?php endforeach; ?></section><?php endif; ?>
<?php if ($canAct && $document['journal_id'] && !$document['reversal_journal_id']): ?><section><details <?= $reverseInput?'open':'' ?>><summary class="section-title">Correction and cancellation</summary><p class="text-xs text-ink-muted my-3">Corrections keep the document identity and create a linked reversal and replacement. Dependent payments and credits must be reversed first. Bank-reconciled entries and closed periods remain protected.</p><a class="btn btn-secondary" href="<?= pl_e(pl_url($path,['id'=>$document['id'],'correct'=>'1'])) ?>">Correct this document under the same identity</a><form class="mt-4" method="post" action="<?= pl_e(pl_url($path)) ?>"><?php pl_starter_form($company,'reverse',['id'=>$document['id'],'request_key'=>$reverseInput['request_key']??bin2hex(random_bytes(20))]); ?><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><?php pl_starter_field('Reason','reason',$reverseInput['reason']??''); pl_starter_field('Reversal date (blank = today)','date',$reverseInput['date']??'','date',false); ?></div><button class="btn btn-secondary mt-3">Reverse document</button></form></details></section><?php endif; ?>
<section><h2 class="section-title mb-2">History</h2><dl class="dgrid"><?php foreach ($document['history'] as $revision): ?><div class="dgrid-row"><dt>Revision <?= (int)$revision['revision'] ?></dt><dd><a class="link" href="<?= pl_e(pl_url('/journals/detail',['id'=>$revision['journal_id']])) ?>">Journal <?= (int)$revision['journal_id'] ?></a> · <?= pl_e($revision['reason']) ?> · <time data-local-time datetime="<?= pl_e(str_replace(' ','T',$revision['recorded_at']).'Z') ?>"><?= pl_e($revision['recorded_at']) ?> UTC</time></dd></div><?php endforeach; ?><?php if (!$document['history']): ?><div class="dgrid-row"><dt>Draft</dt><dd>No posting yet.</dd></div><?php endif; ?></dl></section>
<p class="text-xs text-ink-muted">Use your browser’s Print command for this document.</p>
</div></section></div>
