<?php declare(strict_types=1);
if (!$party && !pl_can_write($company)) { pl_ui_empty('Read-only access','A company owner or bookkeeper can add customers and suppliers.'); return; }
?>
<div class="py-5"><section class="rounded-panel border border-border bg-surface">
<?php pl_ui_document_header($party?$party['legal_name']:'New party','',static function () use ($company,$filters): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_url('/parties',$filters)) ?>">Cancel</a><?php if (pl_can_write($company)): ?><button class="btn btn-primary" form="party-editor">Save party</button><?php endif; ?>
<?php }); ?>
<div class="doc-body">
<?php if ($form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?><p>Your entered values are retained.</p></div><?php endif; ?>
<?php if (pl_can_write($company)): ?><form id="party-editor" class="flex flex-col gap-5" method="post" action="<?= pl_e(pl_url('/parties',$filters)) ?>">
<?php pl_ui_return_filters($filters); pl_starter_form($company,'save',['id'=>$party['id']??0,'revision'=>$partyInput['revision']??$party['revision']??0,'request_key'=>$partyInput['request_key']??bin2hex(random_bytes(20))]); ?>
<section><h2 class="section-title mb-2">Identity &amp; role</h2><div class="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
<?php pl_starter_field('Legal name','legal_name',$v['legal_name']??''); pl_starter_field('Trading name','trading_name',$v['trading_name']??'','text',false); pl_starter_field('Entity type','entity_type',$v['entity_type']??'business'); pl_starter_field('Country code (two letters)','country_code',$v['country_code']??''); ?></div>
<div class="flex flex-wrap gap-5 mt-3"><label class="inline-flex items-center gap-2 text-sm"><input type="checkbox" name="is_customer" value="1" <?= !empty($v['is_customer'])?'checked':'' ?>> Customer</label><label class="inline-flex items-center gap-2 text-sm"><input type="checkbox" name="is_vendor" value="1" <?= !empty($v['is_vendor'])?'checked':'' ?>> Supplier</label></div><p class="text-xs text-ink-muted mt-2">One shared record can have both roles.</p></section>
<section><h2 class="section-title mb-2">Financial</h2><div class="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
<?php pl_starter_field('Default currency','currency',$v['currency']??$company['currency']); pl_starter_field('Payment terms','payment_terms',$v['payment_terms']??'','text',false);
pl_starter_select('Receivables account override','ar_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['role']==='receivables')),$v['ar_account_id']??'',false);
pl_starter_select('Payables account override','ap_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['role']==='payables')),$v['ap_account_id']??'',false);
pl_starter_field('Reason','reason',$partyInput['reason']??''); ?></div><p class="text-xs text-ink-muted mt-2">Leave account overrides blank to use the company defaults.</p></section>
<?php if (!$party): ?><details <?= !empty($v['identifier_value'])?'open':'' ?>><summary class="text-sm">Legal identifier (optional)</summary><div class="grid grid-cols-2 gap-4 mt-3"><?php pl_starter_field('Identifier scheme, e.g. TAX_ID','identifier_scheme',$v['identifier_scheme']??'','text',false); pl_starter_field('Identifier value','identifier_value',$v['identifier_value']??'','text',false); ?></div></details><?php endif; ?>
<?php if ($partyInput && $party): ?><a class="link text-sm" href="<?= pl_e(pl_url('/parties',['id'=>$party['id'],'return_filters'=>$filters])) ?>">Reload saved party</a><?php endif; ?>
</form><?php else: ?><section><dl class="dgrid"><?php foreach (['Country'=>$party['country_code'],'Currency'=>$party['financial']['currency']??$company['currency'],'Payment terms'=>$party['financial']['payment_terms']??'—'] as $label=>$value): ?><div class="dgrid-row"><dt><?= pl_e($label) ?></dt><dd><?= pl_e($value) ?></dd></div><?php endforeach; ?></dl><p class="text-xs text-ink-muted mt-3">You have read-only access.</p></section><?php endif; ?>
<?php if ($party && $party['identifiers']): ?><section><details><summary class="section-title">Legal identifiers</summary><?php foreach ($party['identifiers'] as $identifier): ?><p class="text-sm mt-2"><?= pl_e($identifier['country_code'].' / '.$identifier['scheme'].': '.$identifier['value']) ?></p><?php endforeach; ?></details></section><?php endif; ?>
<?php if ($party): ?><section><h2 class="section-title mb-2">Contacts</h2>
<?php pl_ui_table(['Name','Role','Email','Phone'],static function () use ($contacts): void { foreach ($contacts as $contact): ?><tr><td><?= pl_e($contact['name']) ?> <?php if ($contact['is_primary']) { pl_ui_badge('info','Primary'); } ?></td><td><?= pl_e(ucfirst(str_replace('_',' ',$contact['role']))) ?></td><td><?= pl_e($contact['email']?:'—') ?></td><td><?= pl_e($contact['phones']?:'—') ?></td></tr><?php endforeach; if (!$contacts): ?><tr><td colspan="4">No contacts yet.</td></tr><?php endif; },'Party contacts'); ?>
<?php if (pl_can_write($company)): ?><details class="rounded-panel border border-border mt-3" <?= $contactInput?'open':'' ?>><summary class="section-title px-4 py-3">Add contact</summary><form class="border-t border-border px-4 py-3" method="post" action="<?= pl_e(pl_url('/parties',$filters)) ?>">
<?php pl_ui_return_filters($filters); pl_starter_form($company,'contact',['id'=>$party['id'],'request_key'=>$contactInput['request_key']??bin2hex(random_bytes(20))]); ?><div class="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
<?php pl_starter_field('Name','name',$contactInput['name']??''); pl_starter_field('Email','email',$contactInput['email']??'','email',false); pl_starter_field('Phone with country code','phone',$contactInput['phone']??'','tel',false); pl_starter_select('Role','role',['billing'=>'Billing','receiving'=>'Receiving','authorised_signatory'=>'Authorised signatory','owner'=>'Owner'],$contactInput['role']??'billing'); pl_starter_field('Reason','reason',$contactInput['reason']??''); ?></div>
<label class="inline-flex items-center gap-2 text-sm mt-3"><input type="checkbox" name="is_primary" value="1" <?= !empty($contactInput['is_primary'])?'checked':'' ?>> Primary contact</label>
<details class="mt-3" <?= $contactInput?'open':'' ?>><summary class="text-sm">Shared phone acknowledgement</summary><label class="flex items-center gap-2 text-sm my-3"><input type="checkbox" name="acknowledge_phone_duplicates" value="1" <?= !empty($contactInput['acknowledge_phone_duplicates'])?'checked':'' ?>> I reviewed the duplicate phone and intend to share it.</label><?php pl_starter_field('Why this phone is shared','duplicate_reason',$contactInput['duplicate_reason']??'','text',false); ?></details>
<button class="btn btn-secondary mt-3">Save contact</button></form></details><?php endif; ?></section><?php endif; ?>
</div></section></div>
