<?php declare(strict_types=1); ?>
<div class="flex flex-col gap-4 py-5">
<?php pl_ui_page_header('Customers & suppliers',$list['total'].' parties · one shared record can be both a customer and a supplier',static function () use ($company,$filters): void { if (pl_can_write($company)): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/parties',['new'=>'1','return_filters'=>$filters])) ?>"><?= pl_icon('plus') ?> New party</a><?php endif; }); ?>
<div class="split-view"><section class="split-view-list<?= $selection?' has-detail':'' ?>" aria-label="Party list">
<nav class="tabs-seg mb-3" aria-label="Party type"><?php foreach (['all'=>'All','customer'=>'Customers','vendor'=>'Suppliers'] as $key=>$label): ?><a class="tabs-seg-item" href="<?= pl_e(pl_url('/parties',array_replace($filters,['role'=>$key,'page'=>1]))) ?>"<?= $filters['role']===$key?' aria-current="page"':'' ?>><?= pl_e($label) ?></a><?php endforeach; ?></nav>
<form class="filter-bar mb-3" method="get" action="<?= pl_e(pl_url('/parties')) ?>"><input type="hidden" name="role" value="<?= pl_e($filters['role']) ?>"><?php pl_ui_list_controls($filters); ?><button class="btn btn-secondary">Filter</button></form>
<div class="table-wrap"><table class="table"><caption class="sr-only">Customers and suppliers; balances in <?= pl_e($company['currency']) ?></caption><thead><tr><th scope="col"><?php pl_ui_sort('/parties',$filters,'name','Legal name'); ?></th><th scope="col">Role</th><th scope="col" class="text-end">Receivable</th><th scope="col" class="text-end">Payable</th></tr></thead><tbody>
<?php foreach ($list['rows'] as $row): ?><tr><td><a class="record-link" data-record-link href="<?= pl_e(pl_url('/parties',array_replace($filters,['select'=>$row['id']]))) ?>"<?= $selection && $selection['id']===(int)$row['id']?' aria-current="true"':'' ?>><span class="row-title"><?= pl_e($row['legal_name']) ?></span><span class="row-sub"><?= pl_e($row['country_code']) ?></span></a></td><td><?php if ($row['is_customer']): ?><span class="role-tag">Customer</span><?php endif; ?> <?php if ($row['is_vendor']): ?><span class="role-tag">Supplier</span><?php endif; ?></td><?php foreach (['receivable','payable'] as $direction): ?><td class="amount"><?= pl_e(pl_money($balances[$row['id']][$direction]??'0.0000')) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table><?php if (!$list['rows']) { pl_ui_empty('No matching parties.','Adjust the search or add a customer or supplier.'); } ?></div>
<div class="flex flex-wrap justify-between items-center gap-3 mt-3"><span class="text-xs text-ink-muted"><?= (int)$list['total'] ?> records · <?= pl_e($company['currency']) ?></span><?php pl_ui_pagination('/parties',$filters,$list['page'],$list['pages']); ?></div>
<?php if ($company['is_sample']): ?><p class="sample-note">These are sample records in a separate sample company.</p><?php endif; ?></section>
<?php pl_ui_side_panel('Party details',static function () use ($selection,$filters,$company,$balances,$contacts,$activity): void { ?>
<a class="split-view-back link" href="<?= pl_e(pl_url('/parties',$filters)) ?>"><?= pl_icon('arrow-left') ?> Back to list</a>
<?php if (!$selection) { pl_ui_empty('Choose a party','Select a name to view details, contacts and recent activity.'); return; } ?>
<div class="border-b border-border px-5 py-4"><h2 class="text-lg font-semibold"><?= pl_e($selection['legal_name']) ?></h2><dl class="dgrid mt-3"><?php foreach (['receivable'=>'Receivable balance','payable'=>'Payable balance'] as $direction=>$label): ?><div class="dgrid-row"><dt><?= pl_e($label) ?></dt><dd><?= pl_e($company['currency'].' '.pl_money($balances[$selection['id']][$direction]??'0.0000')) ?></dd></div><?php endforeach; ?></dl></div>
<div class="flex flex-col min-h-0 flex-1 overflow-y-auto px-5 pt-4"><?php pl_ui_tabs(['Details'=>'#party-details','Contacts'=>'#party-contacts','Activity'=>'#party-activity'],'Details',true); ?>
<section id="party-details" class="py-3" data-ui-tab-panel><dl class="dgrid"><?php foreach (['Trading name'=>$selection['trading_name']?:'—','Entity type'=>$selection['entity_type'],'Country'=>$selection['country_code'],'Currency'=>$selection['financial']['currency']??$company['currency'],'Payment terms'=>$selection['financial']['payment_terms']??'—'] as $label=>$value): ?><div class="dgrid-row"><dt><?= pl_e($label) ?></dt><dd><?= pl_e($value?:'—') ?></dd></div><?php endforeach; ?></dl></section>
<section id="party-contacts" class="py-3" data-ui-tab-panel><?php foreach ($contacts as $contact): ?><div class="border-b border-border py-3"><h3 class="text-sm font-semibold"><?= pl_e($contact['name']) ?></h3><p class="text-xs text-ink-muted"><?= pl_e($contact['role']) ?><?= $contact['is_primary']?' · Primary':'' ?></p><p class="text-sm"><?= pl_e($contact['email'].' · '.$contact['phones']) ?></p></div><?php endforeach; if (!$contacts): ?><p class="text-sm text-ink-muted">No contacts yet.</p><?php endif; ?></section>
<section id="party-activity" class="py-3" data-ui-tab-panel><p class="text-xs text-ink-muted mb-2">Latest 20 documents, including drafts.</p><dl class="dgrid"><?php foreach ($activity as $item): ?><div class="dgrid-row"><dt><a class="link" href="<?= pl_e(pl_url(in_array($item['kind'],['invoice','customer_credit'],true)?'/ar':'/ap',['id'=>$item['id']])) ?>"><?= pl_e($item['number']) ?></a></dt><dd><?= pl_e(ucfirst($item['payment_status']??$item['status']).' · '.$item['currency'].' '.pl_money($item['total'])) ?></dd></div><?php endforeach; if (!$activity): ?><div class="dgrid-row"><dt>Activity</dt><dd>No documents yet.</dd></div><?php endif; ?></dl></section></div>
<div class="panel-actions"><p class="panel-actions-note">One shared record for both roles.</p><a class="btn btn-secondary" href="<?= pl_e(pl_url('/parties',['id'=>$selection['id'],'return_filters'=>$filters])) ?>"><?= pl_icon('pencil') ?> <?= pl_can_write($company)?'Edit party':'View party' ?></a></div>
<?php }); ?></div></div>
