<?php declare(strict_types=1); $stock=array_column($valuation['products'],null,'id'); ?>
<div class="flex flex-col gap-4 py-5">
<?php pl_ui_page_header('Products & stock',$list['total'].' products · '.$company['currency'].' '.pl_money($valuation['total_value_base']).' total carrying value',static function () use ($write,$filters): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_url('/purchasing')) ?>">Purchase orders</a><?php if ($write): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/inventory',['new'=>'1','return_filters'=>$filters])) ?>"><?= pl_icon('plus') ?> New product</a><?php endif; }); ?>
<?php if (!$enabled): ?><div class="alert alert-info">Inventory is disabled for new operations. Existing products and reports remain available. <a class="link" href="<?= pl_e(pl_url('/modules')) ?>">Review modules</a>.</div><?php endif; ?>
<?php if ($form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?><p>Your entered values are retained.</p></div><?php endif; ?>
<div class="split-view"><section class="split-view-list<?= $selection?' has-detail':'' ?>" aria-label="Product list">
<nav class="tabs-seg mb-3" aria-label="Product type"><?php foreach (['all'=>'All','stock'=>'Stock','nonstock'=>'Non-stock'] as $key=>$label): ?><a class="tabs-seg-item" href="<?= pl_e(pl_url('/inventory',array_replace($filters,['kind'=>$key,'page'=>1]))) ?>"<?= $filters['kind']===$key?' aria-current="page"':'' ?>><?= pl_e($label) ?></a><?php endforeach; ?></nav>
<form class="filter-bar mb-3" method="get" action="<?= pl_e(pl_url('/inventory')) ?>"><input type="hidden" name="kind" value="<?= pl_e($filters['kind']) ?>"><?php pl_ui_list_controls($filters); ?><select class="select" name="status" aria-label="Product status"><?php foreach (['all'=>'All statuses','active'=>'Active','inactive'=>'Inactive'] as $key=>$label): ?><option value="<?= pl_e($key) ?>" <?= $filters['status']===$key?'selected':'' ?>><?= pl_e($label) ?></option><?php endforeach; ?></select><label class="text-xs">As of <input class="input" type="date" name="as_of" value="<?= pl_e($filters['as_of']) ?>"></label><button class="btn btn-secondary">Filter</button></form>
<div class="table-wrap"><table class="table"><caption class="sr-only">Products and stock as of <?= pl_e($filters['as_of']) ?></caption><thead><tr><th scope="col"><?php pl_ui_sort('/inventory',$filters,'name','Product'); ?></th><th scope="col" class="text-end">On hand</th><th scope="col" class="text-end">Carrying value</th><th scope="col">Status</th></tr></thead><tbody>
<?php foreach ($list['rows'] as $row): $value=$stock[$row['id']]??null; ?><tr><td><a class="record-link" data-record-link href="<?= pl_e(pl_url('/inventory',array_replace($filters,['select'=>$row['id']]))) ?>"<?= $selection && $selection['id']===(int)$row['id']?' aria-current="true"':'' ?>><span class="row-title"><?= pl_e($row['name']) ?></span><span class="row-sub"><?= pl_e($row['sku'].' · '.$row['kind']) ?></span></a></td><td class="amount"><?= $value?pl_e($value['quantity'].' '.$row['base_unit']):'—' ?></td><td class="amount"><?= $value?pl_e(pl_money($value['value_base'])):'—' ?></td><td><?php pl_ui_badge($row['is_active']?'active':'inactive'); ?></td></tr><?php endforeach; ?></tbody></table><?php if (!$list['rows']) { pl_ui_empty('No matching products.','Adjust the search or add a stock item or service.'); } ?></div>
<div class="flex flex-wrap justify-between items-center gap-3 mt-3"><span class="text-xs text-ink-muted"><?= (int)$list['total'] ?> records · <?= pl_e($company['currency']) ?></span><?php pl_ui_pagination('/inventory',$filters,$list['page'],$list['pages']); ?></div>
<?php if ($company['is_sample']): ?><p class="sample-note">These are synthetic records in a separate sample company.</p><?php endif; ?></section>
<?php pl_ui_side_panel('Product details',static function () use ($selection,$stock,$filters,$company,$accountOptions,$movements,$write): void { ?>
<a class="split-view-back link" href="<?= pl_e(pl_url('/inventory',$filters)) ?>"><?= pl_icon('arrow-left') ?> Back to list</a>
<?php if (!$selection) { pl_ui_empty('Choose a product','Select a product to view its stock, accounts and movements.'); return; } $value=$stock[$selection['id']]??null; ?>
<div class="border-b border-border px-5 py-4"><div class="flex flex-wrap gap-2 items-center"><h2 class="text-lg font-semibold"><?= pl_e($selection['name']) ?></h2><?php pl_ui_badge($selection['is_active']?'active':'inactive'); ?></div><p class="text-sm text-ink-muted mt-2"><?= pl_e($selection['sku']) ?><?= $value?' · '.pl_e($value['quantity'].' '.$selection['base_unit']).' on hand':'' ?></p><p class="amount-lg mt-2"><?= $value?pl_e($company['currency'].' '.pl_money($value['value_base'])):'Non-stock item' ?></p><p class="text-xs text-ink-muted mt-1">As of <?= pl_e(pl_date_label($filters['as_of'])) ?></p></div>
<div class="flex flex-col min-h-0 flex-1 overflow-y-auto px-5 pt-4"><?php pl_ui_tabs(['Details'=>'#product-details','Movements'=>'#product-movements'],'Details',true); ?>
<section id="product-details" class="py-3" data-ui-tab-panel><dl class="dgrid"><?php foreach (['Base unit'=>$selection['base_unit'],'Average unit cost'=>$value['average_cost']??'—','Selling price'=>$selection['selling_price'],'Sales account'=>$accountOptions[$selection['sales_account_id']]??'—','Inventory account'=>$accountOptions[$selection['inventory_account_id']]??'—','Cost account'=>$accountOptions[$selection['cogs_account_id']]??'—'] as $label=>$text): ?><div class="dgrid-row"><dt><?= pl_e($label) ?></dt><dd><?= pl_e($text) ?></dd></div><?php endforeach; ?></dl></section>
<section id="product-movements" class="py-3" data-ui-tab-panel><p class="text-xs text-ink-muted mb-2">Latest 500 movements, all dates, with original source references.</p><?php pl_ui_table(['Date / movement','Quantity / value','Source'],static function () use ($movements): void { foreach ($movements as $row): ?><tr><td><?= pl_e(pl_date_label($row['movement_date'])) ?><span class="row-sub"><?= pl_e(str_replace('_',' ',$row['kind'])) ?></span></td><td class="amount"><?= pl_e($row['quantity_delta']) ?><span class="row-sub"><?= pl_e($row['value_delta']) ?></span></td><td><?php if ($row['journal_id']): ?><a class="link" href="<?= pl_e(pl_url('/journals/detail',['id'=>$row['journal_id']])) ?>"><?= pl_e($row['source_reference']) ?></a><?php else: ?><?= pl_e($row['source_reference']) ?><?php endif; ?></td></tr><?php endforeach; if (!$movements): ?><tr><td colspan="3">No movements yet.</td></tr><?php endif; },'Product movements'); ?></section></div>
<div class="panel-actions"><a class="btn btn-secondary" href="<?= pl_e(pl_url('/inventory',['id'=>$selection['id'],'return_filters'=>$filters])) ?>"><?= $write?'Edit product':'View product' ?></a><?php if ($write && $selection['kind']==='stock'): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/inventory',['id'=>$selection['id'],'count'=>'1','return_filters'=>$filters])) ?>">Record count</a><?php endif; ?></div>
<?php }); ?></div>
<details class="rounded-panel border border-border bg-surface p-4"><summary class="section-title">Stock to ledger reconciliation</summary><p class="text-sm my-3">Total carrying value <?= pl_e($company['currency'].' '.pl_money($valuation['total_value_base'])) ?> as of <?= pl_e(pl_date_label($valuation['as_of'])) ?>. Totals cover all stock products, regardless of list filters.</p><?php pl_ui_table(['Account','Stock value','Ledger value','Difference'],static function () use ($valuation,$accountOptions): void { foreach ($valuation['accounts'] as $row): ?><tr><td><a class="link" href="<?= pl_e(pl_url('/reports/account',['id'=>$row['account_id'],'as_of'=>$valuation['as_of']])) ?>"><?= pl_e($accountOptions[$row['account_id']]??('Account '.$row['account_id'])) ?></a></td><td class="amount"><?= pl_e(pl_money($row['stock_value'])) ?></td><td class="amount"><?= pl_e(pl_money($row['ledger_value'])) ?></td><td class="amount"><?= pl_e(pl_money($row['difference'])) ?></td></tr><?php endforeach; },'Stock to ledger'); ?><a class="link text-sm" href="<?= pl_e(pl_url('/accounts')) ?>">Manage accounts</a></details>
<?php require __DIR__.'/inventory-opening.php'; ?>
</div>
