<?php declare(strict_types=1); $progress=pl_purchase_order_progress($order); ?>
<section class="rounded-panel border border-border bg-surface">
<?php pl_ui_document_header($order['number'],$progress==='partial'?'partially-received':$progress,static function () use ($order,$filters,$write,$hasUnreceived): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_url('/purchasing',$filters)) ?>">Back to orders</a>
<?php if ($write && $order['status']==='confirmed' && $hasUnreceived): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/purchasing',['id'=>$order['id'],'receive'=>'1','return_filters'=>$filters])) ?>">Receive goods</a><?php endif; }); ?>
<div class="doc-body"><dl class="grid grid-cols-2 md:grid-cols-4 gap-4"><?php foreach (['Supplier'=>$order['party_name'],'Order date'=>pl_date_label($order['document_date']),'Status'=>ucfirst($order['status']),'Reference'=>$order['reference']?:'—'] as $label=>$value): ?><div><dt class="field-label"><?= pl_e($label) ?></dt><dd class="text-sm mt-1"><?= pl_e($value) ?></dd></div><?php endforeach; ?></dl>
<?php pl_ui_table(['Goods','Ordered','Received','Unreceived','Unit price','Order value'],static function () use ($order): void { foreach ($order['lines'] as $line): ?><tr><td><?= pl_e($line['description']) ?></td><td class="amount"><?= pl_e($line['quantity']) ?></td><td class="amount"><?= pl_e($line['received_quantity']) ?></td><td class="amount"><?= pl_e($line['remaining_quantity']) ?></td><td class="amount"><?= pl_e($line['unit_price']) ?></td><td class="amount"><?= pl_e($line['amount']) ?></td></tr><?php endforeach; },'Purchase order lines'); ?>
<div class="flex justify-end"><?php pl_ui_totals(['Total order value ('.$order['currency'].')'=>pl_money($order['total'])]); ?></div>
<?php if ($order['notes']!==''): ?><p class="text-sm"><?= pl_e($order['notes']) ?></p><?php endif; ?>
<p class="text-xs text-ink-muted">An order is a commitment. Accounting starts when goods are received or a supplier bill is posted.</p>
<?php if ($order['status']==='confirmed' && !$hasUnreceived): ?><p class="alert alert-info">All ordered quantities have been received. Receipt history, supplier billing and returns remain available below.</p><?php endif; ?>
<?php if ($write && $order['status']!=='cancelled' && $hasUnreceived) { pl_ui_sheet('Cancel unreceived quantities',static function () use ($company,$order,$cancelInput,$filters,$form): void { ?>
<?php if ($cancelInput && $form['message']!==''): ?><p class="alert alert-danger" role="alert"><?= pl_e($form['message']) ?></p><?php endif; ?>
<p class="text-sm mb-3">Existing receipts and supplier bills remain in their ledgers.</p><form class="flex flex-col gap-3" method="post" action="<?= pl_e(pl_url('/purchasing')) ?>"><?php pl_ui_return_filters($filters); pl_starter_form($company,'cancel',['id'=>$order['id'],'revision'=>$cancelInput?($cancelInput['revision']??''):$order['revision'],'request_key'=>$cancelInput['request_key']??null]); pl_starter_field('Cancellation reason','reason',$cancelInput['reason']??''); ?><button class="btn btn-secondary">Cancel remaining order</button><?php if ($cancelInput): ?><a class="link" href="<?= pl_e(pl_url('/purchasing',['id'=>$order['id'],'return_filters'=>$filters])) ?>">Reload current order for review</a><?php endif; ?></form>
<?php },(bool)$cancelInput); } ?></div></section>
