<?php declare(strict_types=1);
$isAr=$normalKind==='invoice'; $editing=isset($_GET['new']) || isset($_GET['edit']) || isset($_GET['correct']) || ($original!==null && $document===null) || ($form['input'] && in_array($form['input']['action']??'',['save','correct'],true));
$v=$form['input']?:($document??($original?['party_id'=>$original['party_id'],'currency'=>$original['currency'],'original_document_id'=>$original['id'],'price_mode'=>$original['price_mode'],'kind'=>$creditKind]:[]));
$correct=isset($_GET['correct']) || ($v['action']??'')==='correct';
$kind=$v['kind']??$document['kind']??$normalKind;
$accountOptions=pl_starter_options(array_filter($accounts,fn($a)=>$isAr?$a['type']==='income':in_array($a['type'],['expense','asset','liability'],true)&&!in_array($a['role'],['cash_bank','receivables','payables'],true)));
$failedAction=$form['input']['action']??'';
$paymentInput=$failedAction==='settle'?$form['input']:[];
$reverseInput=$failedAction==='reverse'?$form['input']:[];
$postInput=$failedAction==='post'?$form['input']:[];
?>
<section class="page-wrap starter-detail">
<?php if (pl_web_text($_GET,'return_report')==='ageing'): ?><a class="btn btn-ghost" href="<?= pl_e(pl_url('/reports/ageing',['direction'=>$isAr?'receivable':'payable','as_of'=>$report['as_of']])) ?>"><?= pl_icon('arrow-left') ?> Back to ageing report</a><?php endif; ?>
<?php pl_starter_header($isAr?'Accounts receivable':'Accounts payable',$isAr?'Invoice customers, record collections and follow what remains due.':'Record supplier bills, payments and credits, with a traceable balance.',$form,$company); ?>
<div class="starter-actions"><?php if (pl_can_write($company)): ?><a class="button primary" href="<?= pl_e(pl_url($path,['new'=>'1'])) ?>">New <?= $isAr?'invoice':'bill' ?></a><a class="button secondary" href="<?= pl_e(pl_url($path,['settle'=>'1'])) ?>"><?= $isAr?'Record receipt':'Record payment' ?></a><a class="button secondary" href="<?= pl_e(pl_url('/parties' ,['new'=>'1'])) ?>">Add customer or vendor</a><?php endif; ?><a class="button secondary" href="<?= pl_e(pl_url('/bank-reconciliation')) ?>">Bank reconciliation</a></div>
<?php if ($editing && pl_can_write($company)): ?><section class="panel"><h2><?= $correct?'Correct under the same document identity':($document?'Edit draft':ucwords(str_replace('_',' ',$kind))) ?></h2>
<form method="post" action="<?= pl_e(pl_url($path)) ?>">
<?php pl_starter_form($company,$correct?'correct':'save',['id'=>$document['id']??0,'revision'=>$form['input']['revision']??$document['revision']??0,'kind'=>$kind,'original_document_id'=>$v['original_document_id']??0,'request_key'=>$form['input']['request_key']??bin2hex(random_bytes(20))]); ?>
<div class="starter-grid"><?php
pl_starter_select($isAr?'Customer':'Vendor','party_id',pl_starter_options(array_filter($parties,fn($p)=>(bool)$p[$isAr?'is_customer':'is_vendor']),'legal_name'),$v['party_id']??'');
pl_starter_field('Document date','date',$v['date']??$v['document_date']??gmdate('Y-m-d'),'date');
pl_starter_field('Due date','due_date',$v['due_date']??gmdate('Y-m-d'),'date');
pl_starter_field('Currency','currency',$v['currency']??$company['currency']);
if ($kind===$creditKind) { pl_starter_hidden('price_mode',$v['price_mode']??$original['price_mode']??'exclusive'); } else { pl_starter_select('Entered prices','price_mode',['exclusive'=>'Exclude tax','inclusive'=>'Include tax'],$v['price_mode']??$priceMode); }
pl_starter_field('Reference','reference',$v['reference']??'','text',false); pl_starter_field('Terms','terms',$v['terms']??'','text',false);
pl_starter_field('Notes','notes',$v['notes']??'','text',false); pl_starter_select('FX rounding account (optional)','rounding_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['type']==='expense')),$v['rounding_account_id']??'',false);
if ($correct) { pl_starter_field('Correction reason','reason',$v['reason']??''); pl_starter_field('Reversal date (blank = today)','reversal_date',$v['reversal_date']??'','date',false); pl_starter_field('Replacement rate (base per foreign unit)','rate',$v['rate']??'','text',false); }
?></div>
<?php if ($original): ?><p>Credit against <a href="<?= pl_e(pl_url($path,['id'=>$original['id']])) ?>"><?= pl_e($original['number']) ?></a>, revision <?= (int)$original['revision'] ?>. Credit prices <?= $original['price_mode']==='inclusive'?'include':'exclude' ?> tax, matching the original.</p><div class="starter-report"><table class="data-table"><thead><tr><th>Original line</th><th>Description</th><th>Net</th><th>Tax</th></tr></thead><tbody><?php foreach ($original['lines'] as $sourceLine): ?><tr><td><?= (int)$sourceLine['line_number'] ?></td><td><?= pl_e($sourceLine['description']) ?></td><td><?= pl_e(pl_money($sourceLine['line_total'])) ?></td><td><?= pl_e(pl_money($sourceLine['tax_amount'])) ?></td></tr><?php endforeach; ?></tbody></table></div><p class="muted">Choose the original line for each taxed credit. Partial credits use the original tax rate and remaining amount.</p><?php endif; ?>
<h3>Lines</h3><p class="muted">Leave unused rows empty. Amounts allow four decimal places. Unit prices follow the tax entry mode shown above. <?= $isAr?'A stock invoice also issues the goods and records their cost.':'For stock purchases, receive goods in Purchasing before matching the supplier bill.' ?></p>
<div class="starter-lines"><?php $lineRows=$v['lines']??[]; for ($i=0;$i<max(5,count($lineRows)+1);$i++): $line=$lineRows[$i]??[]; ?><fieldset class="starter-line"><legend>Line <?= $i+1 ?></legend><div class="starter-grid">
<?php pl_starter_field('Description',"lines[$i][description]",$line['description']??'','text',false); pl_starter_field('Quantity',"lines[$i][quantity]",$line['quantity']??'','text',false); pl_starter_field('Entered unit price',"lines[$i][unit_price]",$line['unit_price']??'','text',false); pl_starter_select('Account',"lines[$i][account_id]",$accountOptions,$line['account_id']??'',false); pl_starter_select('Product (optional)',"lines[$i][product_id]",pl_starter_options($products),$line['product_id']??'',false); pl_starter_select('Tax code (optional)',"lines[$i][tax_code_id]",pl_starter_options($taxCodes),$line['tax_code_id']??'',false); if ($kind===$creditKind) { pl_starter_field('Original line number',"lines[$i][original_line_number]",$line['original_line_number']??'','text',false); } ?>
</div></fieldset><?php endfor; ?></div><div class="starter-actions"><button class="button primary"><?= $correct?'Reverse and post correction':'Save draft for review' ?></button><a class="button secondary" href="<?= pl_e(pl_url($path)) ?>">Back to register</a><?php if ($form['input'] && $document): ?><a href="<?= pl_e(pl_url($path,['id'=>$document['id']])) ?>">Reload saved document</a><?php endif; ?></div></form></section><?php endif; ?>
<?php if ($document && !$editing): ?><section class="panel starter-document"><p class="starter-print-heading"><?= pl_e($company['name']) ?></p><div class="page-heading"><div><h2><?= pl_e($document['number']) ?></h2><p><?= pl_e($document['party']['legal_name']) ?></p></div><strong><?= pl_e($document['currency'].' '.pl_money($document['total'])) ?></strong></div>
<p>Entered prices <?= $document['price_mode']==='inclusive'?'include':'exclude' ?> tax. Net, tax and total are shown separately.</p><p><?= pl_e(ucwords(str_replace('_',' ',$document['kind']))) ?> · <?= pl_e($document['payment_status']??$document['status']) ?> · <?= pl_e($document['document_date']) ?> · Due <?= pl_e($document['due_date']) ?></p><p><?= pl_e($document['reference']) ?></p>
<div class="starter-report"><table class="data-table"><thead><tr><th>Line</th><th>Description</th><th>Quantity</th><th>Entered unit price</th><th>Net</th><th>Tax</th></tr></thead><tbody><?php foreach ($document['lines'] as $line): ?><tr><td><?= (int)$line['line_number'] ?></td><td><?= pl_e($line['description']) ?></td><td><?= pl_e($line['quantity']) ?></td><td><?= pl_e(pl_money($line['unit_price'])) ?></td><td><?= pl_e(pl_money($line['line_total'])) ?></td><td><?= pl_e(pl_money($line['tax_amount'])) ?></td></tr><?php endforeach; ?></tbody></table></div><p>Net <?= pl_e(pl_money($document['subtotal'])) ?> | Tax <?= pl_e(pl_money($document['tax_total'])) ?> | Total <?= pl_e(pl_money($document['total'])) ?></p><p><?= pl_e($document['terms']) ?></p><p><?= pl_e($document['notes']) ?></p>
<?php if ($document['is_credit'] && $original): ?><p>Credit against <a href="<?= pl_e(pl_url($path,['id'=>$original['id']])) ?>"><?= pl_e($original['number']) ?></a>, original revision <?= (int)$document['original_revision'] ?>.</p><?php endif; ?>
<?php if ($document['reversal_journal_id']): ?><p><a href="<?= pl_e(pl_url('/journals/detail',['id'=>$document['reversal_journal_id']])) ?>">View reversing entry</a></p><?php endif; ?>
<?php if ($document['journal_id']): ?><p><a href="<?= pl_e(pl_url('/journals/detail',['id'=>$document['journal_id']])) ?>">View journal</a> · Remaining <?= pl_e($document['currency'].' '.pl_money($document['outstanding_fc']??'0.0000')) ?></p><?php endif; ?>
<?php if (pl_can_write($company)): ?>
<?php if ($document['status']==='draft'): ?><div class="starter-actions"><a class="button secondary" href="<?= pl_e(pl_url($path,['id'=>$document['id'],'edit'=>'1'])) ?>">Edit draft</a></div><form method="post" action="<?= pl_e(pl_url($path)) ?>"><?php pl_starter_form($company,'post',['id'=>$document['id'],'revision'=>$postInput['revision']??$document['revision'],'request_key'=>$postInput['request_key']??bin2hex(random_bytes(20))]); pl_starter_field('Manual exchange rate (blank for domestic or recorded rate)','rate',$postInput['rate']??'','text',false); ?><button class="button primary">Post <?= pl_e(str_replace('_',' ',$document['kind'])) ?></button></form>
<?php elseif ($document['journal_id'] && $document['reversal_journal_id']===null): ?>
<?php if ($document['kind']===$normalKind && bccomp($document['outstanding_fc']??'0','0',4)>0): ?><a class="button primary" href="<?= pl_e(pl_url($path,['settle'=>'1','party_id'=>$document['party_id'],'currency'=>$document['currency']])) ?>"><?= $isAr?'Record customer receipt':'Record supplier payment' ?></a>
<a class="button secondary" href="<?= pl_e(pl_url($path,['new'=>'1','credit_for'=>$document['id']])) ?>">Create <?= $isAr?'credit note':'supplier credit' ?></a><?php endif; ?>
<details <?= $reverseInput?'open':'' ?>><summary>Correction and cancellation</summary><p>Dependent payments and credits must be reversed first. Bank-reconciled entries and closed periods remain protected.</p><a href="<?= pl_e(pl_url($path,['id'=>$document['id'],'correct'=>'1'])) ?>">Correct this document under the same identity</a><form method="post" action="<?= pl_e(pl_url($path)) ?>"><?php pl_starter_form($company,'reverse',['id'=>$document['id'],'request_key'=>$reverseInput['request_key']??bin2hex(random_bytes(20))]); pl_starter_field('Reason','reason',$reverseInput['reason']??''); pl_starter_field('Reversal date (blank = today)','date',$reverseInput['date']??'','date',false); ?><button class="button secondary">Reverse document</button></form></details>
<?php endif; endif; ?>
<div class="starter-no-print"><?php if ($settlements): ?><h3>Ledger activity</h3><?php foreach ($settlements as $entry): ?><p><a href="<?= pl_e(pl_url('/journals/detail',['id'=>$entry['journal_id']])) ?>"><?= pl_e($entry['posting_date'].' · '.str_replace('_',' ',$entry['kind'])) ?></a> · <?= pl_e($entry['amount_fc']) ?></p><?php if ($entry['credit_document_id']): ?><p><a href="<?= pl_e(pl_url($path,['id'=>$entry['credit_document_id']])) ?>">View <?= pl_e(str_replace('_',' ',$entry['credit_kind'])) ?> <?= pl_e(pl_ar_document_number((int)$entry['credit_document_id'],$entry['credit_kind'])) ?></a></p><?php endif; ?><?php if (pl_can_write($company) && $document['kind']===$normalKind && !$entry['already_reversed'] && !$entry['credit_document_id'] && in_array($entry['source_type'],['open_item_settlement','open_item_batch_settlement'],true) && $entry['kind']==='allocation'): $paymentReversal=$failedAction==='reverse_payment' && (int)($form['input']['journal_id']??0)===(int)$entry['journal_id']?$form['input']:[]; ?><details <?= $paymentReversal?'open':'' ?>><summary>Reverse this payment</summary><p>This reverses the whole payment and all its allocations, including allocations to other documents.</p><form method="post" action="<?= pl_e(pl_url($path)) ?>"><?php pl_starter_form($company,'reverse_payment',['id'=>$document['id'],'journal_id'=>$entry['journal_id'],'request_key'=>$paymentReversal['request_key']??bin2hex(random_bytes(20))]); pl_starter_field('Reason','reason',$paymentReversal['reason']??''); pl_starter_field('Reversal date (blank = today)','date',$paymentReversal['date']??'','date',false); ?><button class="button secondary">Reverse payment</button></form></details><?php endif; endforeach; endif; ?>
<p class="muted">Use your browser’s Print command for this document.</p></div></section><?php endif; ?>
<section class="panel"><h2>Ageing and reconciliation</h2><form method="get" action="<?= pl_e(pl_url($path)) ?>"><div class="starter-grid"><?php pl_starter_field('As of','as_of',$report['as_of'],'date'); ?></div><button class="button secondary">Refresh report</button></form><p><strong><?= pl_e($company['currency'].' '.pl_money($report['total_base'])) ?></strong> outstanding · <?= pl_e(pl_money($report['overdue_base'])) ?> overdue</p>
<?php if (isset($report['buckets'])): ?><div class="starter-grid"><?php foreach ($report['buckets'] as $bucket=>$amount): ?><p><?= pl_e((['not_due'=>'Not due','1_30'=>'1-30 days','31_60'=>'31-60 days','61_90'=>'61-90 days','over_90'=>'Over 90 days'][(string)$bucket]??str_replace('_',' ',(string)$bucket))) ?><br><strong><?= pl_e(is_string($amount)?pl_money($amount):'') ?></strong></p><?php endforeach; ?></div><?php endif; ?>
<div class="starter-report"><table class="data-table"><thead><tr><th>Party / document</th><th>Due</th><th>Days overdue</th><th>Remaining</th><th>Base value</th></tr></thead><tbody><?php foreach ($report['items'] as $item): ?><tr><td><?= pl_e($item['legal_name']) ?><br><?php if (!empty($item['document_id'])): ?><a href="<?= pl_e(pl_url($path,['id'=>$item['document_id']])) ?>"><?= pl_e($item['number']??$item['source_reference']) ?></a><?php else: ?><?= pl_e($item['source_reference']??'Opening debt') ?><?php endif; ?></td><td><?= pl_e($item['due_date']??'') ?></td><td><?= (int)($item['age_days']??0) ?></td><td><?= pl_e($item['currency'].' '.pl_money($item['remaining_fc'])) ?></td><td><?= pl_e(pl_money($item['remaining_base'])) ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php if (isset($report['controls'])): ?><h3>Control accounts</h3><?php foreach ($report['controls'] as $control): ?><p><?= pl_e($control['name']??(string)$control['id']) ?> · Ledger <?= pl_e($control['ledger_base']??'') ?> · Open items <?= pl_e($control['open_items_base']??'') ?> · Difference <?= pl_e($control['difference_base']??'') ?></p><?php endforeach; endif; ?>
<p><a href="<?= pl_e(pl_url('/opening-conversion')) ?>">Review and convert unpaid opening documents</a></p></section>
<section class="panel starter-report"><h2>Document register</h2><table class="data-table"><thead><tr><th>Document / date</th><th>Party</th><th>Type</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach ($documents as $row): ?><tr><td><a href="<?= pl_e(pl_url($path,['id'=>$row['id']])) ?>"><?= pl_e($row['number']) ?></a><br><?= pl_e($row['document_date']) ?></td><td><?= pl_e($row['party']['legal_name']) ?></td><td><?= pl_e(str_replace('_',' ',$row['kind'])) ?></td><td><?= pl_e($row['currency'].' '.pl_money($row['total'])) ?></td><td><?= pl_e($row['payment_status']??$row['status']) ?></td></tr><?php endforeach; ?><?php if (!$documents): ?><tr><td colspan="5">No documents yet. Add a party and create your first draft.</td></tr><?php endif; ?></tbody></table></section>
<?php if ($company['role']==='owner'): ?><details class="panel"><summary>Activate an unused control account</summary><p>Existing opening balances require the reviewed opening-debt conversion.</p><form method="post" action="<?= pl_e(pl_url($path)) ?>"><?php pl_starter_form($company,'activate'); pl_starter_select('Control account','account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['role']===($isAr?'receivables':'payables')&&!$a['open_item_managed']))); pl_starter_field('Reason','reason'); ?><button class="button secondary">Activate control account</button></form></details><?php endif; ?>
</section>
