<?php declare(strict_types=1);
$isAr=$normalKind==='invoice'; $editing=isset($_GET['new']) || isset($_GET['edit']) || isset($_GET['correct']) || ($original!==null && $document===null) || ($form['input'] && in_array($form['input']['action']??'',['save','correct'],true));
$v=$form['input']?:($document??($original?['party_id'=>$original['party_id'],'currency'=>$original['currency'],'original_document_id'=>$original['id'],'price_mode'=>$original['price_mode'],'kind'=>$creditKind]:[]));
$correct=isset($_GET['correct']) || ($v['action']??'')==='correct';
$kind=$v['kind']??$document['kind']??$normalKind;
$accountOptions=pl_starter_options(array_filter($accounts,fn($a)=>$isAr?$a['type']==='income':in_array($a['type'],['expense','asset','liability'],true)&&!in_array($a['role'],['cash_bank','receivables','payables'],true)));
$failedAction=$form['input']['action']??'';
$paymentInput=$failedAction==='settle'?$form['input']:[];
$reverseInput=$failedAction==='reverse'?$form['input']:[];
$postInput=$failedAction==='post'?$form['input']:[];
if ($editing && pl_can_write($company)) { require dirname(__DIR__).'/partials/ui/ar-document-editor.php'; return; }
if ($document && !$editing) { require dirname(__DIR__).'/partials/ui/ar-document-record.php'; return; }
?>
<section class="page-wrap starter-detail">
<?php if (pl_web_text($_GET,'return_report')==='ageing'): ?><a class="btn btn-ghost" href="<?= pl_e(pl_url('/reports/ageing',['direction'=>$isAr?'receivable':'payable','as_of'=>$report['as_of']])) ?>"><?= pl_icon('arrow-left') ?> Back to ageing report</a><?php endif; ?>
<?php pl_starter_header($isAr?'Accounts receivable':'Accounts payable',$isAr?'Invoice customers, record collections and follow what remains due.':'Record supplier bills, payments and credits, with a traceable balance.',$form,$company); ?>
<div class="starter-actions"><?php if (pl_can_write($company)): ?><a class="button primary" href="<?= pl_e(pl_url($path,['new'=>'1'])) ?>">New <?= $isAr?'invoice':'bill' ?></a><a class="button secondary" href="<?= pl_e(pl_url($path,['settle'=>'1'])) ?>"><?= $isAr?'Record receipt':'Record payment' ?></a><a class="button secondary" href="<?= pl_e(pl_url('/parties' ,['new'=>'1'])) ?>">Add customer or vendor</a><?php endif; ?><a class="button secondary" href="<?= pl_e(pl_url('/bank-reconciliation')) ?>">Bank reconciliation</a></div>
<section class="panel"><h2>Ageing and reconciliation</h2><form method="get" action="<?= pl_e(pl_url($path)) ?>"><div class="starter-grid"><?php pl_starter_field('As of','as_of',$report['as_of'],'date'); ?></div><button class="button secondary">Refresh report</button></form><p><strong><?= pl_e($company['currency'].' '.pl_money($report['total_base'])) ?></strong> outstanding · <?= pl_e(pl_money($report['overdue_base'])) ?> overdue</p>
<?php if (isset($report['buckets'])): ?><div class="starter-grid"><?php foreach ($report['buckets'] as $bucket=>$amount): ?><p><?= pl_e((['not_due'=>'Not due','1_30'=>'1-30 days','31_60'=>'31-60 days','61_90'=>'61-90 days','over_90'=>'Over 90 days'][(string)$bucket]??str_replace('_',' ',(string)$bucket))) ?><br><strong><?= pl_e(is_string($amount)?pl_money($amount):'') ?></strong></p><?php endforeach; ?></div><?php endif; ?>
<div class="starter-report"><table class="data-table"><thead><tr><th>Party / document</th><th>Due</th><th>Days overdue</th><th>Remaining</th><th>Base value</th></tr></thead><tbody><?php foreach ($report['items'] as $item): ?><tr><td><?= pl_e($item['legal_name']) ?><br><?php if (!empty($item['document_id'])): ?><a href="<?= pl_e(pl_url($path,['id'=>$item['document_id']])) ?>"><?= pl_e($item['number']??$item['source_reference']) ?></a><?php else: ?><?= pl_e($item['source_reference']??'Opening debt') ?><?php endif; ?></td><td><?= pl_e($item['due_date']??'') ?></td><td><?= (int)($item['age_days']??0) ?></td><td><?= pl_e($item['currency'].' '.pl_money($item['remaining_fc'])) ?></td><td><?= pl_e(pl_money($item['remaining_base'])) ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php if (isset($report['controls'])): ?><h3>Control accounts</h3><?php foreach ($report['controls'] as $control): ?><p><?= pl_e($control['name']??(string)$control['id']) ?> · Ledger <?= pl_e($control['ledger_base']??'') ?> · Open items <?= pl_e($control['open_items_base']??'') ?> · Difference <?= pl_e($control['difference_base']??'') ?></p><?php endforeach; endif; ?>
<p><a href="<?= pl_e(pl_url('/opening-conversion')) ?>">Review and convert unpaid opening documents</a></p></section>
<section class="panel starter-report"><h2>Document register</h2><table class="data-table"><thead><tr><th>Document / date</th><th>Party</th><th>Type</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach ($documents as $row): ?><tr><td><a href="<?= pl_e(pl_url($path,['id'=>$row['id']])) ?>"><?= pl_e($row['number']) ?></a><br><?= pl_e($row['document_date']) ?></td><td><?= pl_e($row['party']['legal_name']) ?></td><td><?= pl_e(str_replace('_',' ',$row['kind'])) ?></td><td><?= pl_e($row['currency'].' '.pl_money($row['total'])) ?></td><td><?= pl_e($row['payment_status']??$row['status']) ?></td></tr><?php endforeach; ?><?php if (!$documents): ?><tr><td colspan="5">No documents yet. Add a party and create your first draft.</td></tr><?php endif; ?></tbody></table></section>
<?php if ($company['role']==='owner'): ?><details class="panel"><summary>Activate an unused control account</summary><p>Existing opening balances require the reviewed opening-debt conversion.</p><form method="post" action="<?= pl_e(pl_url($path)) ?>"><?php pl_starter_form($company,'activate'); pl_starter_select('Control account','account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['role']===($isAr?'receivables':'payables')&&!$a['open_item_managed']))); pl_starter_field('Reason','reason'); ?><button class="button secondary">Activate control account</button></form></details><?php endif; ?>
</section>
