<?php declare(strict_types=1); $canWrite = pl_can_write($company) && !pl_demo_enabled(); ?>
<div class="flex flex-col gap-3 py-4 bank-reconciliation">
<?php pl_ui_page_header('Bank reconciliation','Compare a statement with posted bank entries in '.$company['currency'].'.',static function (): void { ?><a class="btn btn-ghost" href="<?= pl_e(pl_url('/bank-reconciliation')) ?>">Statement history</a><?php }); ?>
    <?php if ($form['message']): ?><div class="alert alert-info" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
    <?php if (pl_demo_enabled()): ?><div class="alert alert-info">Bank imports and reconciliation changes are disabled in the public sample.</div><?php endif; ?>
    <?php if ($preview): $data = $preview['preview']['data']; ?>
        <?php foreach ($accounts as $account): ?><?php if ((int) $account['id'] === $data['account_id']): ?><p><strong>Selected account:</strong> <?= pl_e($account['code'] . ' · ' . $account['name']) ?> · <?= pl_e($company['currency']) ?></p><?php endif; ?><?php endforeach; ?>
        <section class="rounded-panel border border-border bg-surface p-3"><p class="eyebrow">Review before importing</p><h2 class="section-title mb-2"><?= pl_e($data['reference']) ?></h2><p><?= pl_e(pl_date_label($data['start_date'])) ?> – <?= pl_e(pl_date_label($data['end_date'])) ?> · <?= count($data['rows']) ?> transactions</p><p>Opening <?= pl_e(pl_money($data['opening_balance'])) ?> → closing <?= pl_e(pl_money($data['closing_balance'])) ?>. The statement totals balance.</p><p class="text-sm text-ink-muted">Imported rows are retained as supplied. Check the bank account, dates, references and amounts before confirming.</p>
        <div class="table-wrap"><table class="table"><caption class="sr-only">Statement import preview</caption><thead><tr><th scope="col">Date</th><th scope="col">Reference / description</th><th scope="col" class="amount">Money in</th><th scope="col" class="amount">Money out</th></tr></thead><tbody><?php foreach ($data['rows'] as $row): ?><tr><td><?= pl_e($row['date']) ?></td><td><?= pl_e($row['reference']) ?><br><span class="text-sm text-ink-muted"><?= pl_e($row['description']) ?></span></td><td class="amount"><?= pl_e(pl_money($row['money_in'])) ?></td><td class="amount"><?= pl_e(pl_money($row['money_out'])) ?></td></tr><?php endforeach; ?></tbody></table></div>
        <form method="post" action="<?= pl_e(pl_url('/bank-reconciliation')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="action" value="import"><input type="hidden" name="preview_key" value="<?= pl_e($preview['key']) ?>"><button class="btn btn-primary">Confirm statement import</button></form></section>
    <?php endif; ?>
    <?php if ($statement): ?>
        <section class="rounded-panel border border-border bg-surface p-3"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="section-title mb-2"><?= pl_e($statement['reference']) ?></h2><p><?= pl_e($statement['account_code'] . ' · ' . $statement['account_name']) ?> · <?= pl_e($statement['start_date']) ?> – <?= pl_e($statement['end_date']) ?></p></div><span class="badge <?= $statement['status'] === 'completed' ? 'badge-posted' : 'badge-draft' ?>"><?= pl_e(['draft' => 'In progress', 'completed' => 'Completed', 'cancelled' => 'Cancelled'][$statement['status']]) ?></span></div>
        <p class="text-xs text-ink-muted">Imported <time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $statement['imported_at']) . 'Z') ?>"><?= pl_e($statement['imported_at']) ?> UTC</time> by user <?= (int) $statement['imported_by'] ?>. Initial cleared baseline: <?= pl_e(pl_money((string) $statement['baseline_balance'])) ?> before <?= pl_e($statement['baseline_date']) ?>.</p>
        <?php if ($statement['status'] === 'cancelled'): ?><div class="alert alert-info"><strong>Cancelled import.</strong> <?= pl_e($statement['cancellation_reason']) ?><br>Cancelled <time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $statement['cancelled_at']) . 'Z') ?>"><?= pl_e($statement['cancelled_at']) ?> UTC</time> by user <?= (int) $statement['cancelled_by'] ?>. Original statement rows remain below. <a href="<?= pl_e(pl_url('/bank-reconciliation')) ?>">Import a corrected statement</a>.</div><?php endif; ?>
        <?php if ($statement['status'] === 'completed'): ?><p>Completed <time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $statement['completed_at']) . 'Z') ?>"><?= pl_e($statement['completed_at']) ?> UTC</time> by user <?= (int) $statement['completed_by'] ?>. Recorded ledger balance <?= pl_e(pl_money((string) $statement['ledger_balance'])) ?>; recorded outstanding <?= pl_e(pl_money((string) $statement['outstanding_balance'])) ?>.</p><?php endif; ?>
</section>
<dl class="grid grid-cols-2 lg:grid-cols-5 gap-px overflow-hidden rounded-panel border border-border bg-border" aria-label="Reconciliation totals">
<?php foreach (['Statement closing'=>$statement['closing_balance'],'+ Outstanding ('.$summary['outstanding_count'].')'=>$summary['outstanding_balance'],'Adjusted balance'=>$summary['adjusted_statement_balance'],'Ledger balance'=>$summary['ledger_balance'],'Difference'=>$summary['difference']] as $label=>$value): ?><div class="bg-surface px-3 py-2"><dt class="text-xs text-ink-muted"><?= pl_e($label) ?></dt><dd class="text-sm font-semibold tabular-nums"><?= pl_e(pl_money((string)$value)) ?></dd></div><?php endforeach; ?></dl>
        <?php if (!$summary['baseline_unchanged']): ?><div class="alert alert-info" role="alert">The ledger before the initial statement start changed. Resolve the baseline before completion.</div><?php endif; ?>
<div class="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_300px] gap-4 items-start"><section class="min-w-0" aria-label="Statement lines"><h2 class="section-title">Statement lines</h2>
        <p><a href="<?= pl_e(pl_url('/reports/account', ['id' => (int) $statement['account_id'], 'as_of' => $statement['end_date']])) ?>">Review bank account activity</a> · <?= $summary['unmatched_count'] ?> unmatched statement rows</p>
        <form method="get" action="<?= pl_e(pl_url('/bank-reconciliation')) ?>" class="filter-bar"><input type="hidden" name="id" value="<?= (int)$statement['id'] ?>"><?php pl_ui_list_controls($filters); ?><button class="btn btn-secondary" type="submit">Filter rows</button></form>
<div class="table-wrap"><table class="table"><caption class="sr-only">Bank statement rows and journal matches</caption><thead><tr><th scope="col"><?php pl_ui_sort('/bank-reconciliation', $filters, 'date', 'Date'); ?></th><th scope="col"><?php pl_ui_sort('/bank-reconciliation', $filters, 'reference', 'Reference / description'); ?></th><th scope="col" class="amount"><?php pl_ui_sort('/bank-reconciliation', $filters, 'money_in', 'Money in'); ?></th><th scope="col" class="amount"><?php pl_ui_sort('/bank-reconciliation', $filters, 'money_out', 'Money out'); ?></th><th scope="col"><?php pl_ui_sort('/bank-reconciliation', $filters, 'match', 'Journal match'); ?></th></tr></thead><tbody><?php foreach ($statement['rows'] as $row): ?><tr><td><?= pl_e($row['transaction_date']) ?></td><td><?= pl_e($row['reference']) ?><br><span class="text-sm text-ink-muted"><?= pl_e($row['description']) ?></span></td><td class="amount"><?= pl_e(pl_money((string) $row['money_in'])) ?></td><td class="amount"><?= pl_e(pl_money((string) $row['money_out'])) ?></td><td><?php if ($row['journal_line_id'] !== null): ?><a href="<?= pl_e(pl_url('/journals/detail', ['id' => (int) $row['journal_id']])) ?>">Journal <?= (int) $row['journal_id'] ?> · line <?= (int) $row['journal_line_id'] ?></a><br><span class="text-xs text-ink-muted"><?= pl_e($row['journal_date']) ?></span><?php if ($canWrite && $statement['status'] === 'draft'): ?><form method="post" action="<?= pl_e(pl_url('/bank-reconciliation')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="action" value="unmatch"><input type="hidden" name="statement_id" value="<?= (int) $statement['id'] ?>"><input type="hidden" name="row_id" value="<?= (int) $row['id'] ?>"><input type="hidden" name="revision" value="<?= (int) $statement['revision'] ?>"><button class="btn btn-secondary btn-sm">Remove match</button></form><?php endif; ?><?php elseif ($canWrite && $statement['status'] === 'draft'): ?><a class="btn btn-secondary btn-sm" href="<?= pl_e(pl_url('/bank-reconciliation', array_replace($filters, ['id' => (int) $statement['id'], 'row' => (int) $row['id']]))) ?>#match-review">Review matches</a><?php else: ?>Unmatched<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php pl_ui_pagination('/bank-reconciliation', $filters, $statement['page'], $statement['pages']); ?>
        <?php if ($statement['rows'] === []): ?><p>No bank transactions match these filters.</p><?php endif; ?>
</section><aside class="min-w-0">
        <?php if ($selectedRow && $canWrite && $statement['status'] === 'draft'): ?><section class="rounded-panel border border-border bg-surface p-3" id="match-review"><h2 class="section-title mb-2">Review matches for <?= pl_e($selectedRow['reference']) ?></h2><p><?= pl_e($selectedRow['transaction_date']) ?> · <?= pl_e($selectedRow['description']) ?></p><p class="text-sm text-ink-muted">Suggestions have the exact signed amount and are ordered by the nearest posting date. Verify the source and date; no suggestion is accepted automatically. Older entries may be outstanding payments or deposits.</p><?php if (count($candidates) > 1): ?><div class="alert alert-info">Multiple candidates have the same amount. Choose only the entry supported by your statement and source record.</div><?php endif; ?><?php if ($candidates === []): ?><p>No unused exact-amount entries are available. Review the account activity and record missing transactions through the normal posting workflow before matching.</p><?php else: ?><form method="post" action="<?= pl_e(pl_url('/bank-reconciliation')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="action" value="match"><input type="hidden" name="statement_id" value="<?= (int) $statement['id'] ?>"><input type="hidden" name="row_id" value="<?= (int) $selectedRow['id'] ?>"><input type="hidden" name="revision" value="<?= (int) $statement['revision'] ?>"><div class="field"><label for="bank-match-line">Journal entry to match</label><select class="select" id="bank-match-line" name="line_id" required><option value="">Choose after reviewing the source</option><?php foreach (array_slice($candidates, 0, 100) as $candidate): ?><option value="<?= (int) $candidate['id'] ?>"><?= pl_e($candidate['journal_date'] . ' · Journal ' . $candidate['journal_id'] . ' / line ' . $candidate['id'] . ' · ' . $candidate['source_reference'] . ' · ' . $candidate['description']) ?></option><?php endforeach; ?></select></div><button class="btn btn-primary">Confirm this match</button></form><?php if (count($candidates) > 100): ?><p>Showing 100 candidates on this page. Continue to more candidates to review other possible sources.</p><?php endif; ?><?php endif; ?></section><?php endif; ?>
        <?php if ($selectedRow && $canWrite && $statement['status'] === 'draft'): ?><p><?php if ($candidatePage > 1): ?><a class="btn btn-secondary btn-sm" href="<?= pl_e(pl_url('/bank-reconciliation', array_replace($filters, ['row'=>(int)$selectedRow['id'],'candidate_page'=>$candidatePage - 1]))) ?>#match-review">Previous candidates</a><?php endif; ?><?php if (count($candidates) > 100): ?><a class="btn btn-secondary btn-sm" href="<?= pl_e(pl_url('/bank-reconciliation', array_replace($filters, ['row'=>(int)$selectedRow['id'],'candidate_page'=>$candidatePage + 1]))) ?>#match-review">More candidates</a><?php endif; ?></p><?php endif; ?>
<?php if (!$selectedRow): ?><div class="rounded-panel border border-border bg-surface p-3"><h2 class="section-title">Review matches</h2><p class="text-sm text-ink-muted">Select an unmatched statement row to review possible journal entries. Every bank row must be matched before completion, even when the difference is zero.</p></div><?php endif; ?>
</aside></div>
        <?php if ($canWrite && $statement['status'] === 'draft'): ?><section class="rounded-panel border border-border bg-surface p-3"><h2 class="section-title mb-2">Complete reconciliation</h2><p>Completion freezes this statement and prevents new entries in this bank account on or before <?= pl_e($statement['end_date']) ?>. Corrections need a later date.</p><form method="post" action="<?= pl_e(pl_url('/bank-reconciliation')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="action" value="complete"><input type="hidden" name="statement_id" value="<?= (int) $statement['id'] ?>"><input type="hidden" name="revision" value="<?= (int) $statement['revision'] ?>"><input type="hidden" name="completion_key" value="bank:<?= (int) $statement['id'] ?>:complete:<?= (int) $statement['revision'] ?>"><label><input type="checkbox" name="review_confirmed" value="1" required> I reviewed every match and the outstanding ledger entries.</label><p><button class="btn btn-primary" <?= !$summary['ready'] ? 'disabled' : '' ?>>Confirm reconciliation</button></p></form></section><?php endif; ?>
<details class="rounded-panel border border-border bg-surface p-3"><summary>How the reconciliation balances</summary>
        <p class="text-xs text-ink-muted">Outstanding entries are posted deposits or payments through the statement end that have not cleared this or an earlier statement. Add their signed net amount to the bank closing balance to compare with the ledger. Every bank row must be matched even when the difference is zero. Reconciliation creates no journal entries.</p>
        <?php if ($summary['outstanding_count'] > 0): ?><section class="rounded-panel border border-border bg-surface p-3" id="outstanding"><h2 class="section-title mb-2">Outstanding ledger entries</h2><p class="text-sm text-ink-muted">These entries were not matched to this or an earlier statement. They remain available to match when they clear a later statement.</p><div class="table-wrap"><table class="table"><caption class="sr-only">Outstanding bank ledger entries</caption><thead><tr><th scope="col">Date</th><th>Source</th><th class="amount">Deposit</th><th class="amount">Payment</th></tr></thead><tbody><?php foreach (array_slice($outstandingLines, 0, 50) as $entry): ?><tr><td><?= pl_e($entry['journal_date']) ?></td><td><a href="<?= pl_e(pl_url('/journals/detail', ['id' => (int) $entry['journal_id']])) ?>"><?= pl_e($entry['source_reference']) ?> · Journal <?= (int) $entry['journal_id'] ?> / line <?= (int) $entry['id'] ?></a><br><?= pl_e($entry['description']) ?></td><td class="amount"><?= pl_e(pl_money((string) $entry['debit'])) ?></td><td class="amount"><?= pl_e(pl_money((string) $entry['credit'])) ?></td></tr><?php endforeach; ?></tbody></table></div><?php if ($outstandingPage > 1): ?><a class="btn btn-secondary btn-sm" href="<?= pl_e(pl_url('/bank-reconciliation', array_replace($filters, ['outstanding_page'=>$outstandingPage - 1]))) ?>#outstanding">Previous outstanding entries</a><?php endif; ?><?php if (count($outstandingLines) > 50): ?><a class="btn btn-secondary btn-sm" href="<?= pl_e(pl_url('/bank-reconciliation', array_replace($filters, ['outstanding_page'=>$outstandingPage + 1]))) ?>#outstanding">More outstanding entries</a><?php endif; ?></section><?php endif; ?>
</details>
        <?php if ($canWrite && $statement['status'] === 'draft'): ?><details class="rounded-panel border border-border bg-surface p-3"><summary>Cancel an incorrect import</summary><p>Remove any saved matches first, then explain the correction. Cancellation retains the original statement, rows and match audit. You can import corrected data using the same bank references.</p><form method="post" action="<?= pl_e(pl_url('/bank-reconciliation')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="action" value="cancel"><input type="hidden" name="statement_id" value="<?= (int) $statement['id'] ?>"><input type="hidden" name="revision" value="<?= (int) $statement['revision'] ?>"><input type="hidden" name="cancellation_key" value="bank:<?= (int) $statement['id'] ?>:cancel:<?= (int) $statement['revision'] ?>"><label class="field">Reason for cancelling<textarea class="textarea" name="reason" required maxlength="400" rows="3"><?= pl_e(pl_web_text($input, 'reason')) ?></textarea></label><button class="btn btn-secondary btn-sm" <?= $summary['row_count'] !== $summary['unmatched_count'] ? 'disabled' : '' ?>>Cancel draft statement</button></form></details><?php endif; ?>
    <?php else: ?>
        <?php if ($canWrite): ?><section class="rounded-panel border border-border bg-surface p-3"><h2 class="section-title mb-2">Import a bank statement</h2><p class="text-sm text-ink-muted">Use UTF-8 CSV with up to 500 transactions and 512 KiB. Exact headers: <code>date,reference,description,money_in,money_out</code>. Use YYYY-MM-DD dates, decimal points and 0 for the unused amount column. Each bank transaction needs a durable reference unique across statements for this account.</p>
        <form method="post" enctype="multipart/form-data" action="<?= pl_e(pl_url('/bank-reconciliation')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="action" value="preview"><input type="hidden" name="MAX_FILE_SIZE" value="524288"><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div class="field"><label for="bank-account">Cash / bank account</label><select class="select" id="bank-account" name="account_id" required><option value="">Choose account</option><?php foreach ($accounts as $account): ?><option value="<?= (int) $account['id'] ?>" <?= (int) ($input['account_id'] ?? 0) === (int) $account['id'] ? 'selected' : '' ?>><?= pl_e($account['code'] . ' · ' . $account['name']) ?></option><?php endforeach; ?></select></div><label class="field">Statement reference<input class="input" name="reference" maxlength="120" value="<?= pl_e(pl_web_text($input, 'reference')) ?>" required></label><label class="field">Start date<input class="input" type="date" name="start_date" value="<?= pl_e(pl_web_text($input, 'start_date')) ?>" required></label><label class="field">End date<input class="input" type="date" name="end_date" value="<?= pl_e(pl_web_text($input, 'end_date')) ?>" required></label><label class="field">Opening balance<input class="input" name="opening_balance" inputmode="decimal" value="<?= pl_e(pl_web_text($input, 'opening_balance', '0')) ?>" required></label><label class="field">Closing balance<input class="input" name="closing_balance" inputmode="decimal" value="<?= pl_e(pl_web_text($input, 'closing_balance')) ?>" required></label><label class="field md:col-span-2">Paste CSV<textarea class="textarea" name="csv" rows="7" maxlength="524288" placeholder="date,reference,description,money_in,money_out"><?= pl_e(pl_web_text($input, 'csv')) ?></textarea></label><label class="field md:col-span-2">Or upload CSV<input class="input" type="file" name="statement_csv" accept=".csv,text/csv"></label></div><p class="text-xs text-ink-muted">Balances can be negative for an overdraft. Statement amounts must be in <?= pl_e($company['currency']) ?>. XLSX and bank-specific formats are not supported.</p><label><input type="checkbox" name="baseline_confirmed" value="1" <?= pl_web_text($input, 'baseline_confirmed') === '1' ? 'checked' : '' ?>> For the first statement, all earlier ledger entries for this account have cleared the bank and its opening balance agrees with the ledger. Resolve earlier outstanding items before starting.</label><p><button class="btn btn-primary">Preview statement</button></p></form></section><?php endif; ?>
        <section class="rounded-panel border border-border bg-surface p-3"><h2 class="section-title mb-2">Statement history</h2><?php if ($statements === []): ?><p>No statements imported yet.</p><?php else: ?><div class="table-wrap"><table class="table"><caption class="sr-only">Imported bank statements</caption><thead><tr><th>Statement</th><th>Bank account</th><th>Dates</th><th class="amount">Closing</th><th>Status</th></tr></thead><tbody><?php foreach ($statements as $item): ?><tr><td><a href="<?= pl_e(pl_url('/bank-reconciliation', ['id' => (int) $item['id']])) ?>"><?= pl_e($item['reference']) ?></a></td><td><?= pl_e($item['account_name']) ?></td><td><?= pl_e($item['start_date']) ?> – <?= pl_e($item['end_date']) ?></td><td class="amount"><?= pl_e(pl_money((string) $item['closing_balance'])) ?></td><td><?= pl_e(['draft' => 'In progress', 'completed' => 'Completed', 'cancelled' => 'Cancelled'][$item['status']]) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?><?php if ($page > 1): ?><a class="btn btn-secondary btn-sm" href="<?= pl_e(pl_url('/bank-reconciliation', ['page' => $page - 1])) ?>">Previous</a><?php endif; ?><?php if ($hasMore): ?><a class="btn btn-secondary btn-sm" href="<?= pl_e(pl_url('/bank-reconciliation', ['page' => $page + 1])) ?>">Next</a><?php endif; ?></section>
    <?php endif; ?>
</div>
