<?php declare(strict_types=1); ?>
<section class="flex flex-col gap-4 py-5">
    <?php pl_ui_page_header('Connections', 'Connect your tools to ' . $company['name'] . '. Each credential reads only this company and book using your current permissions.'); ?>
    <?php if ($message !== ''): ?><p class="alert" role="alert"><?= pl_e($message) ?></p><?php endif; ?>
    <section class="panel"><h2 class="section-title">Connect a client</h2><p>Use the Streamable HTTP endpoint below with a personal token, or choose OAuth in a client that supports it. OAuth opens a sign-in and consent screen here.</p><p><code><?= pl_e($endpoint) ?></code></p><p>Access is read-only. Your client receives financial results and may store or send them according to its own settings. Use a separate credential for each private agent or workflow. Shared chat services should use a separate OAuth connection for each user.</p>
    <?php if (pl_demo_enabled()): ?><p class="alert">Sample access ends at the next hourly reset. After it expires, start a new sample and reconnect your client. Refresh tokens cannot extend demo access.</p><?php else: ?><p>Personal tokens and OAuth grants expire after 30 days. OAuth access tokens last up to 15 minutes. Revocation takes effect on the next request.</p><?php endif; ?></section>
    <?php if ($issued): ?><section class="panel" aria-labelledby="new-token-heading"><h2 id="new-token-heading">Save your token now</h2><p>This is its only display. Copy it into your client's private credential settings. Reloading this page cannot retrieve it.</p><div class="field"><label for="new-token">Personal token</label><textarea class="textarea" id="new-token" readonly rows="3" autocomplete="off" spellcheck="false"><?= pl_e($issued['token']) ?></textarea></div><p>Access expires <time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $issued['connection']['expires_at']) . 'Z') ?>"><?= pl_e($issued['connection']['expires_at']) ?> UTC</time>.</p><a class="btn btn-secondary" href="<?= pl_e(pl_url('/connections')) ?>">I saved the token</a></section><?php endif; ?>
    <?php if ($endpoint !== ''): ?><section class="panel"><h2 class="section-title">Create a personal token</h2><form method="post" action="<?= pl_e(pl_url('/connections')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="create"><div class="field"><label for="connection-name">Connection name</label><input class="input" id="connection-name" name="name" maxlength="120" required placeholder="For example, my private reporting agent" autocomplete="off"></div><?php pl_ui_connection_scope('connection-scope'); ?><p>Company: <strong><?= pl_e($company['name']) ?></strong> · Book <?= (int) $company['book_id'] ?> · Read access</p><button class="btn btn-primary" type="submit">Create token</button></form></section><?php endif; ?>
    <h2 class="section-title">Recent connections for this book</h2><p>Owners can revoke any connection that includes their company. Revoking a connection ends all of its company grants.</p>
    <div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Kind</th><th>Scope</th><th>Status</th><th>Expires</th><th>Action</th></tr></thead><tbody>
    <?php foreach ($connections as $connection): ?><tr><th scope="row"><?= pl_e($connection['name']) ?></th><td><?= pl_e($connection['kind'] === 'personal' ? 'Personal token' : 'OAuth') ?></td><td><?= $connection['access_mode'] === 'reports' ? 'Report-only' : 'Full read' ?></td><td><?= $connection['revoked_at'] !== null ? 'Revoked' : ($connection['expires_at'] <= gmdate('Y-m-d H:i:s') ? 'Expired' : 'Active') ?></td><td><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $connection['expires_at']) . 'Z') ?>"><?= pl_e($connection['expires_at']) ?> UTC</time></td><td><?php if ($connection['revoked_at'] === null): ?><?php pl_ui_confirmation('Revoke ' . $connection['name'], 'This ends all company grants held by this connection on its next request. The client will need a new token or new consent to reconnect.', static function () use ($company, $connection): void { ?><form method="post" action="<?= pl_e(pl_url('/connections')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="connection_id" value="<?= pl_e($connection['id']) ?>"><button class="btn btn-danger" name="action" value="revoke">Confirm revoke</button></form><?php }); ?><?php endif; ?></td></tr><?php endforeach; ?>
    </tbody></table></div>
    <?php if ($connections === []): ?><p>No connections have been created for this book.</p><?php endif; ?>
</section>
