<?php declare(strict_types=1); ?>
<section class="report-page">
    <div class="page-heading"><div><p class="eyebrow">Authorized reporting</p><h1>Connections</h1><p>Connect your tools to <?= pl_e($company['name']) ?>. Each credential reads only this company and book using your current permissions.</p></div></div>
    <?php if ($message !== ''): ?><p class="alert" role="alert"><?= pl_e($message) ?></p><?php endif; ?>
    <section class="panel"><h2>Connect a client</h2><p>Use the Streamable HTTP endpoint below with a personal token, or choose OAuth in a client that supports it. OAuth opens a sign-in and consent screen here.</p><p><code><?= pl_e($endpoint) ?></code></p><p>Access is read-only. Your client receives financial results and may store or send them according to its own settings. Use a separate credential for each private agent or workflow. Shared chat services should use a separate OAuth connection for each user.</p>
    <?php if (pl_demo_enabled()): ?><p class="alert">Sample access ends at the next hourly reset. After it expires, start a new sample and reconnect your client. Refresh tokens cannot extend demo access.</p><?php else: ?><p>Personal tokens and OAuth grants expire after 30 days. OAuth access tokens last up to 15 minutes. Revocation takes effect on the next request.</p><?php endif; ?></section>
    <?php if ($issued): ?><section class="panel" aria-labelledby="new-token-heading"><h2 id="new-token-heading">Save your token now</h2><p>This is its only display. Copy it into your client's private credential settings. Reloading this page cannot retrieve it.</p><div class="field"><label for="new-token">Personal token</label><textarea id="new-token" readonly rows="3" autocomplete="off" spellcheck="false"><?= pl_e($issued['token']) ?></textarea></div><p>Access expires <time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $issued['connection']['expires_at']) . 'Z') ?>"><?= pl_e($issued['connection']['expires_at']) ?> UTC</time>.</p><a class="button secondary" href="<?= pl_e(pl_url('/connections')) ?>">I saved the token</a></section><?php endif; ?>
    <?php if ($endpoint !== ''): ?><section class="panel"><h2>Create a personal token</h2><form method="post" action="<?= pl_e(pl_url('/connections')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="create"><div class="field"><label for="connection-name">Connection name</label><input id="connection-name" name="name" maxlength="120" required placeholder="For example, my private reporting agent" autocomplete="off"></div><p>Company: <strong><?= pl_e($company['name']) ?></strong> · Book <?= (int) $company['book_id'] ?> · Read access</p><button class="button primary" type="submit">Create token</button></form></section><?php endif; ?>
    <h2>Recent connections for this book</h2><p>Owners can revoke any connection that includes their company. Revoking a connection ends all of its company grants.</p>
    <?php foreach ($connections as $connection): ?><section class="panel"><h3><?= pl_e($connection['name']) ?></h3><p><?= pl_e($connection['kind'] === 'personal' ? 'Personal token' : 'OAuth') ?> · <?= $connection['revoked_at'] !== null ? 'Revoked' : ($connection['expires_at'] <= gmdate('Y-m-d H:i:s') ? 'Expired' : 'Active') ?></p><p>Expires <time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $connection['expires_at']) . 'Z') ?>"><?= pl_e($connection['expires_at']) ?> UTC</time></p><?php if ($connection['revoked_at'] === null): ?><form method="post" action="<?= pl_e(pl_url('/connections')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="connection_id" value="<?= pl_e($connection['id']) ?>"><button class="button secondary" name="action" value="revoke">Revoke <?= pl_e($connection['name']) ?></button></form><?php endif; ?></section><?php endforeach; ?>
    <?php if ($connections === []): ?><p>No connections have been created for this book.</p><?php endif; ?>
</section>
