<?php
declare(strict_types=1);
$kind = pl_web_text($input, 'kind', 'expense');
$cashAccounts = array_filter($company['accounts'], static fn (array $a): bool => $a['semantic_key'] === 'core.cash_bank' && $a['is_active']);
$categoryAccounts = array_filter($company['accounts'], static fn (array $a): bool => in_array($a['type'], ['income', 'expense'], true) && $a['is_active']);
$defaultCash = array_key_first($cashAccounts);
$cashId = pl_web_id($input, 'money_account_id', $defaultCash === null ? 0 : (int) $cashAccounts[$defaultCash]['id']);
?>
<div class="page-wrap editor-wrap"><a class="back-link" href="<?= pl_e(pl_url($document ? '/transactions/detail' : '/transactions', $document ? ['id' => $document['id']] : [])) ?>"><?= pl_icon('arrow-left') ?> Back to <?= $document ? 'transaction' : 'transactions' ?></a>
<div class="page-heading"><div><p class="eyebrow"><?= $document ? pl_e($document['number']) . ' · Editing draft' : 'Money in. Money out.' ?></p><h1><?= $document ? 'Edit draft' : 'Record a transaction' ?></h1><p class="muted">Save first. Review the entry. Post when you're ready.</p></div><span class="badge draft">Draft</span></div>
<?php if ($form['message']): ?><div class="alert" role="alert"><strong>Your draft has not been changed.</strong><p><?= pl_e($form['message']) ?></p><p>Your submitted values are kept below.<?php if ($document): ?> <a href="<?= pl_e(pl_url('/transactions/edit', ['id' => $document['id']])) ?>">Reload the latest saved version</a> to resolve a revision conflict.<?php endif; ?></p></div><?php endif; ?>
<div class="editor-grid"><form class="panel editor-form" method="post" action="<?= pl_e(pl_url('/transactions/save')) ?>" data-document-form>
    <?= pl_csrf_field() ?><?= pl_scope_fields($company) ?>
    <input type="hidden" name="creation_key" value="<?= pl_e(pl_web_text($input, 'creation_key')) ?>">
    <?php if ($document): ?><input type="hidden" name="id" value="<?= (int) $document['id'] ?>"><input type="hidden" name="revision" value="<?= pl_web_id($input, 'revision', (int) $document['revision']) ?>"><?php endif; ?>
    <div class="form-grid"><fieldset class="transaction-kind full-width"><legend>Transaction type</legend><label><input type="radio" name="kind" value="expense" <?= $kind !== 'receipt' ? 'checked' : '' ?>> Money out <span>Expense</span></label><label><input type="radio" name="kind" value="receipt" <?= $kind === 'receipt' ? 'checked' : '' ?>> Money in <span>Receipt</span></label></fieldset>
    <label class="field">Date<input type="date" name="date" value="<?= pl_e(pl_web_text($input, 'date')) ?>" required <?= !$document && !$form['input'] ? 'data-local-today' : '' ?>><span class="field-hint">The accounting date for this transaction.</span></label>
    <label class="field">Amount (<?= pl_e($company['currency']) ?>)<input type="text" inputmode="decimal" name="amount" value="<?= pl_e(pl_web_text($input, 'amount')) ?>" placeholder="0.00" maxlength="21" pattern="[0-9]+(\.[0-9]{1,4})?" required autocomplete="off"><span class="field-hint">Use a decimal point, without separators.</span></label>
    <label class="field full-width">Counterparty name<input type="text" name="counterparty" value="<?= pl_e(pl_web_text($input, 'counterparty')) ?>" maxlength="160" placeholder="Who did you pay or receive money from?" required></label>
    <label class="field">Cash / bank account<select name="money_account_id" required><?php foreach ($cashAccounts as $account): ?><option value="<?= (int) $account['id'] ?>" <?= $cashId === (int) $account['id'] ? 'selected' : '' ?>><?= pl_e($account['name']) ?></option><?php endforeach; ?></select></label>
    <label class="field">Category<select name="category_account_id" required><option value="">Choose a category</option><?php foreach ($categoryAccounts as $account): ?><option value="<?= (int) $account['id'] ?>" data-category-kind="<?= $account['type'] === 'income' ? 'receipt' : 'expense' ?>" <?= pl_web_id($input, 'category_account_id') === (int) $account['id'] ? 'selected' : '' ?>><?= pl_e($account['name']) ?></option><?php endforeach; ?></select></label>
    <label class="field full-width">Reference <span class="optional">optional</span><input type="text" name="reference" value="<?= pl_e(pl_web_text($input, 'reference')) ?>" maxlength="120" placeholder="Receipt number or your own reference"></label>
    <label class="field full-width">Memo <span class="optional">optional</span><textarea name="memo" rows="3" maxlength="500" placeholder="What was this transaction for?"><?= pl_e(pl_web_text($input, 'memo')) ?></textarea></label></div>
    <div class="form-actions"><a href="<?= pl_e(pl_url($document ? '/transactions/detail' : '/transactions', $document ? ['id' => $document['id']] : [])) ?>" class="button secondary">Cancel</a><button type="submit" class="button primary">Save draft <?= pl_icon('arrow-right') ?></button></div>
</form><aside class="editor-guide"><span class="eyebrow">01 / Record</span><h2>Get the details right.<br>The books follow.</h2><p>This step saves your work without affecting your balances.</p><ol class="journey-steps"><li aria-current="step"><strong>Record</strong><span>Add the date, amount and category.</span></li><li><strong>Review</strong><span>Inspect the balanced journal.</span></li><li><strong>Post</strong><span>Include the entry in your reports.</span></li></ol><p class="muted small">This preview supports one category in your business's base currency. Split entries, tax and foreign currency posting are planned.</p></aside></div>
</div>
