<?php declare(strict_types=1);
$accountNames=[];
foreach ($company['accounts'] as $account) { $accountNames[(int)$account['id']]=$account['code'].' · '.$account['name']; }
?>
<section class="flex flex-col gap-4 py-5" aria-labelledby="general-title">
<?php pl_ui_page_header('Journals',$list['total'].' general journals · '.$company['currency'],static function () use ($company,$filters): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_url('/reports/account')) ?>">Account statement</a><?php if (pl_can_write($company)): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/general-journals/new',['return_filters'=>$filters])) ?>"><?= pl_icon('plus') ?> New journal</a><?php endif; },'general-title'); ?>
<div class="split-view"><section class="split-view-list<?= $selection?' has-detail':'' ?>" aria-label="Journal list">
<nav class="tabs-seg mb-3" aria-label="Journal status"><?php foreach (['draft'=>'Drafts','posted'=>'Posted','reversed'=>'Reversed','all'=>'All'] as $key=>$label): ?><a class="tabs-seg-item" href="<?= pl_e(pl_url('/general-journals',array_replace($filters,['status'=>$key,'page'=>1]))) ?>"<?= $filters['status']===$key?' aria-current="page"':'' ?>><?= pl_e($label) ?></a><?php endforeach; ?></nav>
<form method="get" action="<?= pl_e(pl_url('/general-journals')) ?>" class="filter-bar mb-3"><input type="hidden" name="status" value="<?= pl_e($filters['status']) ?>"><?php pl_ui_list_controls($filters); ?><button class="btn btn-secondary">Filter</button></form>
<div class="table-wrap" tabindex="0" role="region" aria-label="General journals"><table class="table"><caption class="sr-only">Saved general journals in <?= pl_e($company['currency']) ?></caption><thead><tr><th scope="col"><?php pl_ui_sort('/general-journals',$filters,'date','Journal / date'); ?></th><th scope="col"><?php pl_ui_sort('/general-journals',$filters,'description','Description'); ?></th><th scope="col"><?php pl_ui_sort('/general-journals',$filters,'status','Status'); ?></th><th scope="col" class="num">Debit</th><th scope="col" class="num">Credit</th><th scope="col">Balance</th></tr></thead><tbody>
<?php foreach ($list['rows'] as $row): ?><tr><td><a class="record-link" data-record-link href="<?= pl_e(pl_url('/general-journals',array_replace($filters,['select'=>$row['id']]))) ?>"<?= $selection && $selection['id']===$row['id']?' aria-current="true"':'' ?>><span class="row-title"><?= pl_e($row['number']) ?></span><span class="row-sub"><?= pl_e(pl_date_label($row['document_date'])) ?></span></a></td><td><?= pl_e($row['description']) ?><?php if ($row['reference']!==''): ?><span class="row-sub"><?= pl_e($row['reference']) ?></span><?php endif; ?></td><td><?php pl_ui_badge($row['status']); ?></td><td class="num"><?= pl_e(pl_money($row['totals']['debit'])) ?></td><td class="num"><?= pl_e(pl_money($row['totals']['credit'])) ?></td><td><?= $row['totals']['balanced']?'Balanced':'Needs balancing' ?></td></tr><?php endforeach; ?></tbody></table>
<?php if (!$list['rows']) { pl_ui_empty('No matching journals','Adjust the filters or create a journal draft. Drafts can be saved while you finish balancing them.'); } ?></div>
<?php pl_ui_pagination('/general-journals',$filters,$list['page'],$list['pages']); ?>
<p class="text-xs text-ink-muted mt-3">These are general journals. Receipt, expense and POS source records remain in their own workflows.</p></section>
<?php pl_ui_side_panel('Journal details',static function () use ($selection,$filters,$company,$accountNames): void { ?>
<a class="split-view-back link" href="<?= pl_e(pl_url('/general-journals',$filters)) ?>"><?= pl_icon('arrow-left') ?> Back to list</a>
<?php if (!$selection) { pl_ui_empty('Choose a journal','Select a journal to review its details, lines and current revision.'); return; } ?>
<div class="border-b border-border px-5 py-4"><div class="flex flex-wrap items-center gap-2"><h2 class="text-lg font-semibold"><?= pl_e($selection['number']) ?></h2><?php pl_ui_badge($selection['status']); ?></div><p class="text-sm text-ink-muted mt-2"><?= pl_e($selection['description']) ?></p><p class="amount-lg"><?= pl_e($company['currency'].' '.pl_money($selection['totals']['debit'])) ?></p></div>
<div class="flex min-h-0 flex-1 flex-col overflow-y-auto px-5 pt-4"><?php pl_ui_tabs(['Details'=>'#journal-details','Lines'=>'#journal-lines','History'=>'#journal-history'],'Details',true); ?>
<section class="py-3" id="journal-details" data-ui-tab-panel><dl class="dgrid"><?php foreach (['Description'=>$selection['description'],'Reference'=>$selection['reference']?:'—','Date'=>pl_date_label($selection['document_date']),'Status'=>ucfirst($selection['status'])] as $label=>$value): ?><div class="dgrid-row"><dt><?= pl_e($label) ?></dt><dd><?= pl_e($value) ?></dd></div><?php endforeach; ?></dl></section>
<section class="py-3" id="journal-lines" data-ui-tab-panel><h3 class="section-title mb-2"><?= $selection['totals']['balanced']?'Balanced entry':'Needs balancing' ?></h3><div class="table-wrap"><table class="table"><thead><tr><th scope="col">Account</th><th scope="col" class="num">Debit</th><th scope="col" class="num">Credit</th></tr></thead><tbody><?php foreach ($selection['lines'] as $line): ?><tr><td><?= pl_e($accountNames[(int)$line['account_id']]??'Unavailable account') ?></td><td class="num"><?= pl_e(pl_money($line['debit'])) ?></td><td class="num"><?= pl_e(pl_money($line['credit'])) ?></td></tr><?php endforeach; ?></tbody><tfoot><tr><th scope="row">Total</th><td class="num"><?= pl_e(pl_money($selection['totals']['debit'])) ?></td><td class="num"><?= pl_e(pl_money($selection['totals']['credit'])) ?></td></tr></tfoot></table></div></section>
<section class="py-3" id="journal-history" data-ui-tab-panel><p class="text-sm">Current revision <?= (int)$selection['revision'] ?>.</p><a class="link" href="<?= pl_e(pl_url('/general-journals/detail',['id'=>$selection['id'],'return_filters'=>$filters])) ?>">Open journal and full history</a></section></div>
<div class="panel-actions"><p class="panel-actions-note"><?= $selection['status']==='draft'?'This saved draft has no effect on balances.':'Posted details are preserved. Corrections use a linked reversal.' ?></p>
<a class="btn btn-secondary" href="<?= pl_e(pl_url('/general-journals/detail',['id'=>$selection['id'],'return_filters'=>$filters])) ?>">Open journal</a>
<?php if ($selection['status']==='draft' && pl_can_write($company)): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/general-journals/edit',['id'=>$selection['id'],'return_filters'=>$filters])) ?>">Edit draft</a>
<?php if ($company['setup_status']==='ready' && $selection['totals']['balanced']): ?><form method="post" action="<?= pl_e(pl_url('/general-journals/post')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="id" value="<?= (int)$selection['id'] ?>"><input type="hidden" name="revision" value="<?= (int)$selection['revision'] ?>"><input type="hidden" name="intent" value="post_reviewed_journal"><button class="btn btn-primary">Post journal</button></form><?php endif; endif; ?></div>
<?php }); ?></div></section>
