<?php declare(strict_types=1); ?>
<section class="page-wrap core-page" aria-labelledby="general-title">
<div class="page-heading"><div><p class="eyebrow">Accounting core</p><h1 id="general-title">General journals</h1><p class="muted">Save the entry, review its lines, then post to your books.</p></div><?php if (pl_can_write($company)): ?><a class="button primary" href="<?= pl_e(pl_url('/general-journals/new')) ?>"><?= pl_icon('plus') ?> New journal</a><?php endif; ?></div>
<div class="panel core-table-panel"><div class="table-wrap" tabindex="0" role="region" aria-label="General journals"><table class="data-table core-journal-list"><caption class="sr-only">Saved general journals in <?= pl_e($company['currency']) ?></caption><thead><tr><th scope="col">Journal / date</th><th scope="col">Description</th><th scope="col">Status</th><th scope="col" class="amount">Debit</th><th scope="col" class="amount">Credit</th><th scope="col">Balance</th></tr></thead><tbody>
<?php foreach ($list['rows'] as $row): ?><tr><td><a class="record-link" href="<?= pl_e(pl_url('/general-journals/detail', ['id' => $row['id']])) ?>"><strong><?= pl_e($row['number']) ?></strong><span><?= pl_e(pl_date_label($row['document_date'])) ?></span></a></td><td><?= pl_e($row['description']) ?><?php if ($row['reference'] !== ''): ?><span class="row-secondary muted"><?= pl_e($row['reference']) ?></span><?php endif; ?></td><td><span class="badge <?= pl_e($row['status']) ?>"><?= pl_e(ucfirst($row['status'])) ?></span></td><td class="amount"><?= pl_e(pl_money($row['totals']['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($row['totals']['credit'])) ?></td><td><?= $row['totals']['balanced'] ? 'Balanced' : 'Needs balancing' ?></td></tr><?php endforeach; ?>
</tbody></table></div>
<?php if (!$list['rows']): ?><div class="empty-state"><h2>No general journals yet</h2><p>Record a dated entry across your accounts. Drafts can be saved while you finish balancing them.</p><?php if (pl_can_write($company)): ?><a class="button primary" href="<?= pl_e(pl_url('/general-journals/new')) ?>">Create a journal draft</a><?php endif; ?></div><?php endif; ?>
<div class="list-footer"><span><?= (int) $list['total'] ?> journals · <?= pl_e($company['currency']) ?></span><nav class="pagination" aria-label="Journal pages"><?php if ($list['page'] > 1): ?><a class="icon-button" aria-label="Previous page" href="<?= pl_e(pl_url('/general-journals', ['page' => $list['page'] - 1])) ?>"><?= pl_icon('chevron-left') ?></a><?php endif; ?><span>Page <?= (int) $list['page'] ?> of <?= (int) $list['pages'] ?></span><?php if ($list['page'] < $list['pages']): ?><a class="icon-button" aria-label="Next page" href="<?= pl_e(pl_url('/general-journals', ['page' => $list['page'] + 1])) ?>"><?= pl_icon('chevron-right') ?></a><?php endif; ?></nav></div></div>
<p class="muted small core-footnote">These are general journals. Receipt, expense and POS source records remain in their own workflows.</p>
</section>
