<?php
declare(strict_types=1);
$accountNames = [];
foreach ($company['accounts'] as $detailAccount) { $accountNames[(int) $detailAccount['id']] = $detailAccount['code'] . ' · ' . $detailAccount['name']; }
$formInput = is_array($form['input'] ?? null) ? $form['input'] : [];
$hasFailure = pl_web_text($form, 'message') !== '';
$canPost = pl_can_write($company) && $company['setup_status'] === 'ready' && $draft['totals']['balanced'];
?>
<section class="flex flex-col gap-4 my-5 rounded-panel border border-border bg-surface" aria-labelledby="general-detail-title">
<?php pl_ui_document_header($draft['number'],$draft['status'],static function () use ($company,$draft,$filters,$canPost,$formInput,$hasFailure,$form): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_url('/general-journals',$filters)) ?>">Back to journals</a><a class="btn btn-secondary" href="<?= pl_e(pl_url('/reports/trial-balance')) ?>">Trial balance</a>
<?php if ($draft['status'] === 'draft' && pl_can_write($company)): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/general-journals/edit', ['id' => $draft['id'],'return_filters'=>$filters])) ?>">Edit draft</a><?php if ($canPost): ?><form method="post" action="<?= pl_e(pl_url('/general-journals/post')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="id" value="<?= (int) $draft['id'] ?>"><input type="hidden" name="revision" value="<?= array_key_exists('revision', $formInput) ? pl_web_id($formInput, 'revision') : (int) $draft['revision'] ?>"><input type="hidden" name="intent" value="post_reviewed_journal"><button class="btn btn-primary" type="submit">Post journal</button></form><?php endif; ?><?php endif; ?>
<?php if ($draft['status']==='posted' && pl_can_write($company)) { pl_ui_sheet('Reverse journal',static function () use ($company,$draft,$filters,$formInput,$hasFailure,$form): void { ?>
<?php if ($hasFailure): ?><p class="alert alert-danger" role="alert"><?= pl_e(pl_web_text($form,'message')) ?></p><?php endif; ?>
<p>Create an opposite entry on the selected date, preserving the original and its history.</p><form method="post" action="<?= pl_e(pl_url('/general-journals/reverse')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="id" value="<?= (int) $draft['id'] ?>"><div class="flex flex-col gap-3"><label class="field">Reversal date<input class="input" type="date" name="date" value="<?= pl_e(pl_web_text($formInput, 'date', gmdate('Y-m-d'))) ?>" required <?= !isset($formInput['date']) ? 'data-local-today' : '' ?>></label><label class="field">Reason<textarea class="textarea" name="reason" rows="3" maxlength="500" required><?= pl_e(pl_web_text($formInput, 'reason')) ?></textarea></label></div><button type="submit" class="btn btn-secondary">Post linked reversal</button></form>
<?php },$hasFailure,'btn btn-primary'); } },'general-detail-title'); ?>
<p class="text-xs text-ink-muted px-5"><?= pl_e(pl_date_label($draft['document_date'])) ?> · <?= pl_e($company['currency']) ?> · Revision <?= (int)$draft['revision'] ?></p>
<?php if ($hasFailure): ?><div class="alert alert-danger mx-5" role="alert"><strong>The action could not be completed.</strong><p><?= pl_e(pl_web_text($form, 'message')) ?></p><p><a href="<?= pl_e(pl_url('/general-journals/detail', ['id' => $draft['id'],'return_filters'=>$filters])) ?>">Reload and review the latest saved version</a> before retrying a changed draft.</p></div><?php endif; ?>
<div class="doc-body"><dl class="dgrid"><div class="dgrid-row"><dt>Description</dt><dd><?= pl_e($draft['description']) ?></dd></div><div class="dgrid-row"><dt>Reference</dt><dd><?= pl_e($draft['reference'] ?: '—') ?></dd></div></dl>
<div class="flex items-center justify-between gap-3"><h2 class="section-title"><?= $draft['status'] === 'draft' ? 'Review the entry' : 'Saved entry' ?></h2><span class="<?= $draft['totals']['balanced'] ? 'balanced-label' : 'core-unbalanced' ?>"><?= $draft['totals']['balanced'] ? 'Balanced' : 'Needs balancing' ?></span></div>
<div class="table-wrap" tabindex="0" role="region" aria-label="Journal debit and credit lines"><table class="table"><caption class="sr-only">Journal lines in <?= pl_e($company['currency']) ?></caption><thead><tr><th scope="col">Account</th><th scope="col">Description</th><th scope="col" class="amount">Debit</th><th scope="col" class="amount">Credit</th></tr></thead><tbody>
<?php foreach ($draft['lines'] as $line): ?><tr><td><a href="<?= pl_e(pl_url('/reports/account', ['id' => $line['account_id']])) ?>"><?= pl_e($accountNames[(int) $line['account_id']] ?? 'Account ' . (int) $line['account_id']) ?></a></td><td><?= pl_e($line['description'] ?: '—') ?></td><td class="amount"><?= pl_e(pl_money($line['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($line['credit'])) ?></td></tr><?php endforeach; ?>
</tbody><tfoot><tr><th scope="row" colspan="2">Total (<?= pl_e($company['currency']) ?>)</th><td class="amount"><?= pl_e(pl_money($draft['totals']['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($draft['totals']['credit'])) ?></td></tr></tfoot></table></div>
<?php if (!$draft['totals']['balanced']): ?><p class="text-xs text-danger">Debit minus credit: <?= pl_e($company['currency'] . ' ' . pl_money($draft['totals']['difference'])) ?>. Balance the draft before posting.</p><?php endif; ?>
<p class="text-xs text-ink-muted"><?= $draft['status'] === 'draft' ? 'This saved draft has no effect on balances. Posting includes these lines in the accounts and reports.' : 'Posted details are preserved. Corrections use a linked reversal.' ?></p>
<div class="flex flex-wrap gap-2">

<?php if ($draft['journal_id']): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/journals/detail', ['id' => $draft['journal_id']])) ?>">Open posted journal</a><?php endif; ?>
<?php if ($draft['reversal_journal_id']): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/journals/detail', ['id' => $draft['reversal_journal_id']])) ?>">Open linked reversal</a><?php endif; ?>
</div></div>

<details class="rounded-panel border border-border p-4 mx-5 mb-5"><summary>Journal history <span class="muted">· Latest 50 changes</span></summary><?php if (!$history): ?><p class="muted small">No history is available.</p><?php endif; ?><ol><?php foreach ($history as $event): ?><li><strong><?= pl_e(ucfirst(str_replace('_', ' ', $event['action']))) ?></strong> · <?= pl_e($event['display_name']) ?><p><?= pl_e($event['reason']) ?></p><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $event['recorded_at']) . 'Z') ?>"><?= pl_e($event['recorded_at']) ?> UTC</time></li><?php endforeach; ?></ol></details>
</section>
