<?php declare(strict_types=1); ?>
<section class="page-wrap core-page" aria-labelledby="general-title">
<p class="ledger-entry-link"><a href="<?= pl_e(pl_url('/reports/account')) ?>">Account ledger &amp; running balances <?= pl_icon('arrow-right') ?></a></p>
<div class="page-heading"><div><p class="eyebrow">Accounting core</p><h1 id="general-title">General journals</h1><p class="muted">Save the entry, review its lines, then post to your books.</p></div><?php if (pl_can_write($company)): ?><a class="button primary" href="<?= pl_e(pl_url('/general-journals/new')) ?>"><?= pl_icon('plus') ?> New journal</a><?php endif; ?></div>
<form method="get" action="<?= pl_e(pl_url('/general-journals')) ?>" class="filter-bar" data-fold="filters">
<?php pl_ui_list_controls($filters); ?>
<label class="field"><span class="sr-only">Journal status</span><select class="select" name="status"><?php foreach (['all'=>'All statuses','draft'=>'Drafts','posted'=>'Posted','reversed'=>'Reversed'] as $key=>$label): ?><option value="<?= pl_e($key) ?>"<?= $filters['status'] === $key ? ' selected' : '' ?>><?= pl_e($label) ?></option><?php endforeach; ?></select></label>
<button type="submit" class="btn btn-secondary">Filter</button></form>
<div class="panel core-table-panel"><div class="table-wrap" tabindex="0" role="region" aria-label="General journals"><table class="table core-journal-list"><caption class="sr-only">Saved general journals in <?= pl_e($company['currency']) ?></caption><thead><tr><th scope="col"><?php pl_ui_sort('/general-journals', $filters, 'date', 'Journal / date'); ?></th><th scope="col"><?php pl_ui_sort('/general-journals', $filters, 'description', 'Description'); ?></th><th scope="col"><?php pl_ui_sort('/general-journals', $filters, 'status', 'Status'); ?></th><th scope="col" class="amount">Debit</th><th scope="col" class="amount">Credit</th><th scope="col">Balance</th></tr></thead><tbody>
<?php foreach ($list['rows'] as $row): ?><tr><td><a class="record-link" href="<?= pl_e(pl_url('/general-journals/detail', array_replace($filters, ['id' => $row['id']]))) ?>"><strong><?= pl_e($row['number']) ?></strong><span><?= pl_e(pl_date_label($row['document_date'])) ?></span></a></td><td><?= pl_e($row['description']) ?><?php if ($row['reference'] !== ''): ?><span class="row-secondary muted"><?= pl_e($row['reference']) ?></span><?php endif; ?></td><td><span class="badge <?= pl_e($row['status']) ?>"><?= pl_e(ucfirst($row['status'])) ?></span></td><td class="amount"><?= pl_e(pl_money($row['totals']['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($row['totals']['credit'])) ?></td><td><?= $row['totals']['balanced'] ? 'Balanced' : 'Needs balancing' ?></td></tr><?php endforeach; ?>
</tbody></table></div>
<?php if (!$list['rows']): ?><div class="empty-state"><h2>No general journals yet</h2><p>Record a dated entry across your accounts. Drafts can be saved while you finish balancing them.</p><?php if (pl_can_write($company)): ?><a class="button primary" href="<?= pl_e(pl_url('/general-journals/new')) ?>">Create a journal draft</a><?php endif; ?></div><?php endif; ?>
<div class="list-footer"><span><?= (int) $list['total'] ?> journals · <?= pl_e($company['currency']) ?></span><nav class="pagination" aria-label="Journal pages"><?php if ($list['page'] > 1): ?><a class="icon-button" aria-label="Previous page" href="<?= pl_e(pl_url('/general-journals', array_replace($filters, ['page' => $list['page'] - 1]))) ?>"><?= pl_icon('chevron-left') ?></a><?php endif; ?><span>Page <?= (int) $list['page'] ?> of <?= (int) $list['pages'] ?></span><?php if ($list['page'] < $list['pages']): ?><a class="icon-button" aria-label="Next page" href="<?= pl_e(pl_url('/general-journals', array_replace($filters, ['page' => $list['page'] + 1]))) ?>"><?= pl_icon('chevron-right') ?></a><?php endif; ?></nav></div></div>
<p class="muted small core-footnote">These are general journals. Receipt, expense and POS source records remain in their own workflows.</p>
</section>
