<?php
declare(strict_types=1);
$accountNames = [];
foreach ($company['accounts'] as $detailAccount) { $accountNames[(int) $detailAccount['id']] = $detailAccount['code'] . ' · ' . $detailAccount['name']; }
$formInput = is_array($form['input'] ?? null) ? $form['input'] : [];
$hasFailure = pl_web_text($form, 'message') !== '';
$canPost = pl_can_write($company) && $company['setup_status'] === 'ready' && $draft['totals']['balanced'];
?>
<section class="page-wrap core-page core-journal-detail" aria-labelledby="general-detail-title">
<a class="back-link" href="<?= pl_e(pl_url('/general-journals')) ?>"><?= pl_icon('arrow-left') ?> Back to journals</a>
<div class="page-heading"><div><p class="eyebrow">General journal</p><div class="inline-heading"><h1 id="general-detail-title"><?= pl_e($draft['number']) ?></h1><span class="badge <?= pl_e($draft['status']) ?>"><?= pl_e(ucfirst($draft['status'])) ?></span></div><p class="muted"><?= pl_e(pl_date_label($draft['document_date'])) ?> · <?= pl_e($company['currency']) ?> · Revision <?= (int) $draft['revision'] ?></p></div><a class="button secondary" href="<?= pl_e(pl_url('/reports/trial-balance')) ?>">Trial balance</a></div>
<?php if ($hasFailure): ?><div class="alert" role="alert"><strong>The action could not be completed.</strong><p><?= pl_e(pl_web_text($form, 'message')) ?></p><p><a href="<?= pl_e(pl_url('/general-journals/detail', ['id' => $draft['id']])) ?>">Reload and review the latest saved version</a> before retrying a changed draft.</p></div><?php endif; ?>
<div class="panel"><dl class="record-details"><div><dt>Description</dt><dd><?= pl_e($draft['description']) ?></dd></div><div><dt>Reference</dt><dd><?= pl_e($draft['reference'] ?: '—') ?></dd></div></dl>
<div class="section-heading"><h2><?= $draft['status'] === 'draft' ? 'Review the entry' : 'Saved entry' ?></h2><span class="<?= $draft['totals']['balanced'] ? 'balanced-label' : 'core-unbalanced' ?>"><?= $draft['totals']['balanced'] ? 'Balanced' : 'Needs balancing' ?></span></div>
<div class="table-wrap" tabindex="0" role="region" aria-label="Journal debit and credit lines"><table class="data-table core-review-lines"><caption class="sr-only">Journal lines in <?= pl_e($company['currency']) ?></caption><thead><tr><th scope="col">Account</th><th scope="col">Description</th><th scope="col" class="amount">Debit</th><th scope="col" class="amount">Credit</th></tr></thead><tbody>
<?php foreach ($draft['lines'] as $line): ?><tr><td><a href="<?= pl_e(pl_url('/reports/account', ['id' => $line['account_id']])) ?>"><?= pl_e($accountNames[(int) $line['account_id']] ?? 'Account ' . (int) $line['account_id']) ?></a></td><td><?= pl_e($line['description'] ?: '—') ?></td><td class="amount"><?= pl_e(pl_money($line['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($line['credit'])) ?></td></tr><?php endforeach; ?>
</tbody><tfoot><tr><th scope="row" colspan="2">Total (<?= pl_e($company['currency']) ?>)</th><td class="amount"><?= pl_e(pl_money($draft['totals']['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($draft['totals']['credit'])) ?></td></tr></tfoot></table></div>
<?php if (!$draft['totals']['balanced']): ?><p class="core-unbalanced core-footnote">Debit minus credit: <?= pl_e($company['currency'] . ' ' . pl_money($draft['totals']['difference'])) ?>. Balance the draft before posting.</p><?php endif; ?>
<p class="muted small core-footnote"><?= $draft['status'] === 'draft' ? 'This saved draft has no effect on balances. Posting includes these lines in the accounts and reports.' : 'Posted details are preserved. Corrections use a linked reversal.' ?></p>
<div class="detail-actions">
<?php if ($draft['status'] === 'draft' && pl_can_write($company)): ?><a class="button secondary" href="<?= pl_e(pl_url('/general-journals/edit', ['id' => $draft['id']])) ?>">Edit draft</a><?php if ($canPost): ?><form method="post" action="<?= pl_e(pl_url('/general-journals/post')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="id" value="<?= (int) $draft['id'] ?>"><input type="hidden" name="revision" value="<?= array_key_exists('revision', $formInput) ? pl_web_id($formInput, 'revision') : (int) $draft['revision'] ?>"><input type="hidden" name="intent" value="post_reviewed_journal"><button class="button primary" type="submit">Post journal</button></form><?php endif; ?><?php endif; ?>
<?php if ($draft['journal_id']): ?><a class="button secondary" href="<?= pl_e(pl_url('/journals/detail', ['id' => $draft['journal_id']])) ?>">Open posted journal</a><?php endif; ?>
<?php if ($draft['reversal_journal_id']): ?><a class="button secondary" href="<?= pl_e(pl_url('/journals/detail', ['id' => $draft['reversal_journal_id']])) ?>">Open linked reversal</a><?php endif; ?>
</div></div>
<?php if ($draft['status'] === 'posted' && pl_can_write($company)): ?><details class="panel reversal-form" <?= $hasFailure ? 'open' : '' ?>><summary>Correct this entry with a reversal</summary><p>Create an opposite entry on the selected date, preserving the original and its history.</p><form method="post" action="<?= pl_e(pl_url('/general-journals/reverse')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="id" value="<?= (int) $draft['id'] ?>"><div class="form-grid"><label class="field">Reversal date<input type="date" name="date" value="<?= pl_e(pl_web_text($formInput, 'date', gmdate('Y-m-d'))) ?>" required <?= !isset($formInput['date']) ? 'data-local-today' : '' ?>></label><label class="field full-width">Reason<textarea name="reason" rows="3" maxlength="500" required><?= pl_e(pl_web_text($formInput, 'reason')) ?></textarea></label></div><button type="submit" class="button secondary">Post linked reversal</button></form></details><?php endif; ?>
<details class="panel history-section core-history"><summary>Journal history <span class="muted">· Latest 50 changes</span></summary><?php if (!$history): ?><p class="muted small">No history is available.</p><?php endif; ?><ol><?php foreach ($history as $event): ?><li><strong><?= pl_e(ucfirst(str_replace('_', ' ', $event['action']))) ?></strong> · <?= pl_e($event['display_name']) ?><p><?= pl_e($event['reason']) ?></p><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $event['recorded_at']) . 'Z') ?>"><?= pl_e($event['recorded_at']) ?> UTC</time></li><?php endforeach; ?></ol></details>
</section>
