<?php declare(strict_types=1); $submitted=$form['input']; $v=($submitted['action']??'')==='product'?$submitted:($product??[]);
$write=$enabled&&pl_can_write($company); $accountOptions=pl_starter_options(array_filter($accounts,static fn(array $a):bool=>!in_array($a['role'],['receivables','payables'],true)));
$stockProducts=array_values(array_filter($products,static fn(array $p):bool=>$p['kind']==='stock'&&$p['is_active']));
$productInput=($submitted['action']??'')==='product'?$submitted:[];
$openingInput=($submitted['action']??'')==='opening_preview'?$submitted:[];
$confirmInput=($submitted['action']??'')==='opening_confirm'?$submitted:[]; ?>
<section class="page-wrap starter-detail">
<?php pl_starter_header('Inventory','One stock location, exact quantities and moving weighted-average cost.',$form,$company); ?>
<?php if (!$enabled): ?><p class="starter-note">Inventory is disabled for new operations. Existing products and reports remain available. <a href="<?= pl_e(pl_url('/modules')) ?>">Review modules</a>.</p><?php endif; ?>
<div class="starter-actions"><?php if ($write): ?><a class="button primary" href="<?= pl_e(pl_url('/inventory',['new'=>'1'])) ?>">New product</a><?php endif; ?><a class="button secondary" href="<?= pl_e(pl_url('/accounts')) ?>">Manage accounts</a></div>
<?php if ($write&&(isset($_GET['new'])||$product||($submitted['action']??'')==='product')): ?><section class="panel"><h2><?= $product?'Product details':'New product' ?></h2><form method="post" action="<?= pl_e(pl_url('/inventory')) ?>"><?php pl_starter_form($company,'product',['id'=>$product['id']??0,'revision'=>$productInput?($productInput['revision']??''):($product['revision']??0),'request_key'=>($submitted['action']??'')==='product'?($submitted['request_key']??null):null]); ?><div class="starter-grid">
<?php if ($product) {
    foreach (['sku'=>'Product code','kind'=>'Type','base_unit'=>'Base unit'] as $field=>$label) { echo '<p>'.pl_e($label).'<br><strong>'.pl_e($product[$field]).'</strong></p>'; pl_starter_hidden($field,$product[$field]); }
} else { pl_starter_field('Product code','sku',$v['sku']??''); pl_starter_select('Type','kind',['stock'=>'Stock item','nonstock'=>'Service / non-stock'],$v['kind']??'stock'); pl_starter_field('Base unit','base_unit',$v['base_unit']??'each'); }
pl_starter_field('Name','name',$v['name']??''); pl_starter_field('Selling price','selling_price',$v['selling_price']??'0');
foreach (['inventory_account_id'=>'Inventory asset account','cogs_account_id'=>'Cost of goods sold account','sales_account_id'=>'Sales income account','purchase_account_id'=>'Purchase account'] as $field=>$label) {
    if ($product && in_array($field,['inventory_account_id','cogs_account_id'],true)) { echo '<p>'.pl_e($label).'<br><strong>'.pl_e($product[$field]===null?'Not used':($accountOptions[$product[$field]]??('Account '.$product[$field]))).'</strong></p>'; pl_starter_hidden($field,$product[$field]); continue; }
    $types=match($field){'inventory_account_id'=>['asset'],'cogs_account_id'=>['expense'],'sales_account_id'=>['income'],default=>['asset','expense']};
    $eligible=array_filter($accounts,static fn(array $a):bool=>in_array($a['type'],$types,true)&&!in_array($a['role'],['cash_bank','receivables','payables'],true));
    pl_starter_select($label,$field,pl_starter_options($eligible),$v[$field]??'',!in_array($field,['inventory_account_id','cogs_account_id'],true));
}
pl_starter_field('Reason','reason',$v['reason']??''); ?></div><p><label><input type="checkbox" name="is_active" value="1" <?= ($productInput?($productInput['is_active']??'')==='1':($v['is_active']??true))?'checked':'' ?>> Active</label></p><button class="button primary">Save product</button><?php if ($productInput && $product): ?><a class="button secondary" href="<?= pl_e(pl_url('/inventory',['id'=>$product['id']])) ?>">Reload saved product</a><?php endif; ?></form></section><?php endif; ?>
<?php if ($product && $product['kind']==='stock'): ?><section class="panel"><h2><?= pl_e($product['name']) ?></h2><div class="starter-grid"><p>Quantity<br><strong><?= pl_e($balance['quantity'].' '.$product['base_unit']) ?></strong></p><p>Carrying value<br><strong><?= pl_e($company['currency'].' '.pl_money($balance['value_base'])) ?></strong></p><p>Average unit cost<br><strong><?= pl_e($balance['average_cost']) ?></strong></p></div>
<?php if ($write): ?>
<?php foreach (['receive'=>'Manual stock receipt','issue'=>'Manual stock issue','count'=>'Record stock count','value'=>'Reviewed value adjustment'] as $action=>$label): $move=($submitted['action']??'')===$action?$submitted:[]; ?><details <?= $move?'open':'' ?>><summary><?= pl_e($label) ?></summary><p class="muted">Use Purchasing for ordered goods and supplier returns. Manual movements need an explicit counterpart account and reason. Value adjustments retain the quantity and must agree with the reviewed carrying value.</p><form method="post" action="<?= pl_e(pl_url('/inventory')) ?>"><?php pl_starter_form($company,$action,['id'=>$product['id'],'expected_quantity'=>$move?($move['expected_quantity']??''):$balance['quantity'],'expected_value_base'=>$move?($move['expected_value_base']??''):$balance['value_base'],'request_key'=>$move['request_key']??null]); ?><div class="starter-grid"><?php pl_starter_field('Date','date',$move['date']??gmdate('Y-m-d'),'date'); if ($action!=='value') { pl_starter_field($action==='count'?'Counted quantity':'Quantity',$action==='count'?'counted_quantity':'quantity',$move[$action==='count'?'counted_quantity':'quantity']??''); } else { pl_starter_field('Value change in '.$company['currency'].' (use a minus sign to reduce)','amount_base',$move['amount_base']??''); } if ($action==='receive') { pl_starter_field('Total cost in '.$company['currency'],'amount_base',$move['amount_base']??''); } if ($action==='count') { pl_starter_field('Unit cost for count increases','unit_cost',$move['unit_cost']??'0'); } pl_starter_select('Counterpart account','offset_account_id',$accountOptions,$move['offset_account_id']??($action==='issue'?$product['cogs_account_id']:'')); pl_starter_field('Source reference','reference',$move['reference']??''); pl_starter_field('Reason','reason',$move['reason']??''); ?></div><button class="button secondary"><?= pl_e($label) ?></button><?php if ($move && in_array($action,['count','value'],true)): ?><a class="button secondary" href="<?= pl_e(pl_url('/inventory',['id'=>$product['id']])) ?>">Reload current stock for review</a><?php endif; ?></form></details><?php endforeach; endif; ?></section><?php endif; ?>
<section class="panel"><h2>Stock valuation</h2><form method="get" action="<?= pl_e(pl_url('/inventory')) ?>"><?php pl_starter_field('As of','as_of',$valuation['as_of'],'date'); ?><button class="button secondary">Refresh valuation</button></form><p>Total carrying value <strong><?= pl_e($company['currency'].' '.pl_money($valuation['total_value_base'])) ?></strong></p>
<div class="starter-report"><table class="data-table"><thead><tr><th>Product</th><th>Quantity</th><th>Average unit cost</th><th>Carrying value</th></tr></thead><tbody><?php foreach ($valuation['products'] as $row): ?><tr><td><a href="<?= pl_e(pl_url('/inventory',['id'=>$row['id']])) ?>"><?= pl_e($row['sku'].' · '.$row['name']) ?></a></td><td><?= pl_e($row['quantity']) ?></td><td><?= pl_e($row['average_cost']) ?></td><td><?= pl_e(pl_money($row['value_base'])) ?></td></tr><?php endforeach; ?><?php if (!$valuation['products']): ?><tr><td colspan="4">No stock products yet.</td></tr><?php endif; ?></tbody></table></div>
<h3>Stock to ledger</h3><?php foreach ($valuation['accounts'] as $row): ?><p><a href="<?= pl_e(pl_url('/reports/account',['id'=>$row['account_id']])) ?>">Account <?= (int)$row['account_id'] ?></a> · Stock <?= pl_e($row['stock_value']) ?> · Ledger <?= pl_e($row['ledger_value']) ?> · Difference <strong><?= pl_e($row['difference']) ?></strong></p><?php endforeach; ?></section>
<section class="panel starter-report"><h2>Movement history</h2><p class="muted">Latest 500 movements, with original source references.</p><table class="data-table"><thead><tr><th>Date / product</th><th>Movement</th><th>Quantity change</th><th>Value change</th><th>Source</th></tr></thead><tbody><?php foreach ($movements as $row): ?><tr><td><?= pl_e($row['movement_date'].' · '.$row['sku']) ?></td><td><?= pl_e(str_replace('_',' ',$row['kind'])) ?></td><td><?= pl_e($row['quantity_delta']) ?></td><td><?= pl_e($row['value_delta']) ?></td><td><?php if ($row['journal_id']): ?><a href="<?= pl_e(pl_url('/journals/detail',['id'=>$row['journal_id']])) ?>"><?= pl_e($row['source_reference']) ?></a><?php else: ?><?= pl_e($row['source_reference']) ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></section>
<section class="panel"><h2>Product catalogue</h2><?php foreach ($products as $row): ?><p><a href="<?= pl_e(pl_url('/inventory',['id'=>$row['id']])) ?>"><?= pl_e($row['sku'].' · '.$row['name']) ?></a> · <?= pl_e($row['kind']) ?> · <?= $row['is_active']?'Active':'Inactive' ?></p><?php endforeach; ?></section>
<?php if ($write && $company['role']==='owner'): ?><details class="panel" <?= $openingInput?'open':'' ?>><summary>Review opening stock quantities and value</summary><p>Convert existing opening inventory value into product quantities. Values must match the opening journal; confirmation creates no second journal.</p><form method="post" action="<?= pl_e(pl_url('/inventory')) ?>"><?php pl_starter_form($company,'opening_preview',['request_key'=>$openingInput['request_key']??null]); ?><div class="starter-grid"><?php pl_starter_field('Opening date','date',$openingInput['date']??'','date'); pl_starter_field('Reason','reason',$openingInput['reason']??''); ?></div><?php for ($i=0;$i<max(5,min(500,count($openingInput['lines']??[])+1));$i++): ?><fieldset class="starter-line"><legend>Opening product <?= $i+1 ?></legend><div class="starter-grid"><?php pl_starter_select('Product',"lines[$i][product_id]",pl_starter_options($stockProducts),$openingInput['lines'][$i]['product_id']??'',false); pl_starter_field('Quantity',"lines[$i][quantity]",$openingInput['lines'][$i]['quantity']??'','text',false); pl_starter_field('Opening carrying value',"lines[$i][amount_base]",$openingInput['lines'][$i]['amount_base']??'','text',false); ?></div></fieldset><?php endfor; ?><button class="button secondary">Preview opening stock</button></form></details><?php endif; ?>
<?php if ($preview && $write && $company['role']==='owner'): ?><section class="panel"><h2>Confirm opening stock</h2><?php foreach ($preview['payload']['lines'] as $line): ?><p>Product <?= (int)$line['product_id'] ?> · Quantity <?= pl_e($line['quantity']) ?> · Value <?= pl_e($line['amount_base']) ?></p><?php endforeach; ?><form method="post" action="<?= pl_e(pl_url('/inventory')) ?>"><?php pl_starter_form($company,'opening_confirm',['preview_id'=>$confirmInput?($confirmInput['preview_id']??''):$preview['id'],'expected_hash'=>$confirmInput?($confirmInput['expected_hash']??''):$preview['payload_hash'],'request_key'=>$confirmInput['request_key']??null]); ?><p><label><input type="checkbox" name="confirmed" required value="1" <?= ($confirmInput['confirmed']??'')==='1'?'checked':'' ?>> I reviewed the product quantities and their reconciliation to opening balances.</label></p><button class="button primary">Confirm opening conversion</button><?php if ($confirmInput): ?><a class="button secondary" href="<?= pl_e(pl_url('/inventory')) ?>">Reload current preview</a><?php endif; ?></form></section><?php endif; ?>
</section>
