<?php declare(strict_types=1); $submitted=$form['input']; $v=($submitted['action']??'')==='product'?$submitted:($product??[]);
$write=$enabled&&pl_can_write($company); $accountOptions=pl_starter_options(array_filter($accounts,static fn(array $a):bool=>!in_array($a['role'],['receivables','payables'],true)));
$stockProducts=array_values(array_filter($products,static fn(array $p):bool=>$p['kind']==='stock'&&$p['is_active']));
$productInput=($submitted['action']??'')==='product'?$submitted:[];
$openingInput=($submitted['action']??'')==='opening_preview'?$submitted:[];
$confirmInput=($submitted['action']??'')==='opening_confirm'?$submitted:[]; ?>
<?php if ($product || isset($_GET['new']) || $productInput) { require dirname(__DIR__).'/partials/ui/product-editor.php'; return; } ?>
<section class="page-wrap starter-detail">
<?php pl_starter_header('Inventory','One stock location, exact quantities and moving weighted-average cost.',$form,$company); ?>
<?php if (!$enabled): ?><p class="starter-note">Inventory is disabled for new operations. Existing products and reports remain available. <a href="<?= pl_e(pl_url('/modules')) ?>">Review modules</a>.</p><?php endif; ?>
<div class="starter-actions"><?php if ($write): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/inventory')) ?>">Choose a product to count</a><a class="button primary" href="<?= pl_e(pl_url('/inventory',['new'=>'1'])) ?>">New product</a><?php endif; ?><a class="button secondary" href="<?= pl_e(pl_url('/accounts')) ?>">Manage accounts</a></div>
<section class="panel"><h2>Stock valuation</h2><form method="get" action="<?= pl_e(pl_url('/inventory')) ?>"><?php pl_starter_field('As of','as_of',$valuation['as_of'],'date'); ?><button class="button secondary">Refresh valuation</button></form><p>Total carrying value <strong><?= pl_e($company['currency'].' '.pl_money($valuation['total_value_base'])) ?></strong></p>
<div class="starter-report"><table class="data-table"><thead><tr><th>Product</th><th>Quantity</th><th>Average unit cost</th><th>Carrying value</th></tr></thead><tbody><?php foreach ($valuation['products'] as $row): ?><tr><td><a href="<?= pl_e(pl_url('/inventory',['id'=>$row['id']])) ?>"><?= pl_e($row['sku'].' · '.$row['name']) ?></a></td><td><?= pl_e($row['quantity']) ?></td><td><?= pl_e($row['average_cost']) ?></td><td><?= pl_e(pl_money($row['value_base'])) ?></td></tr><?php endforeach; ?><?php if (!$valuation['products']): ?><tr><td colspan="4">No stock products yet.</td></tr><?php endif; ?></tbody></table></div>
<h3>Stock to ledger</h3><?php foreach ($valuation['accounts'] as $row): ?><p><a href="<?= pl_e(pl_url('/reports/account',['id'=>$row['account_id']])) ?>">Account <?= (int)$row['account_id'] ?></a> · Stock <?= pl_e($row['stock_value']) ?> · Ledger <?= pl_e($row['ledger_value']) ?> · Difference <strong><?= pl_e($row['difference']) ?></strong></p><?php endforeach; ?></section>
<section class="panel starter-report"><h2>Movement history</h2><p class="muted">Latest 500 movements, with original source references.</p><table class="data-table"><thead><tr><th>Date / product</th><th>Movement</th><th>Quantity change</th><th>Value change</th><th>Source</th></tr></thead><tbody><?php foreach ($movements as $row): ?><tr><td><?= pl_e($row['movement_date'].' · '.$row['sku']) ?></td><td><?= pl_e(str_replace('_',' ',$row['kind'])) ?></td><td><?= pl_e($row['quantity_delta']) ?></td><td><?= pl_e($row['value_delta']) ?></td><td><?php if ($row['journal_id']): ?><a href="<?= pl_e(pl_url('/journals/detail',['id'=>$row['journal_id']])) ?>"><?= pl_e($row['source_reference']) ?></a><?php else: ?><?= pl_e($row['source_reference']) ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></section>
<section class="panel"><h2>Product catalogue</h2><?php foreach ($products as $row): ?><p><a href="<?= pl_e(pl_url('/inventory',['id'=>$row['id']])) ?>"><?= pl_e($row['sku'].' · '.$row['name']) ?></a> · <?= pl_e($row['kind']) ?> · <?= $row['is_active']?'Active':'Inactive' ?></p><?php endforeach; ?></section>
<?php if ($write && $company['role']==='owner'): ?><details class="panel" <?= $openingInput?'open':'' ?>><summary>Review opening stock quantities and value</summary><p>Convert existing opening inventory value into product quantities. Values must match the opening journal; confirmation creates no second journal.</p><form method="post" action="<?= pl_e(pl_url('/inventory')) ?>"><?php pl_starter_form($company,'opening_preview',['request_key'=>$openingInput['request_key']??null]); ?><div class="starter-grid"><?php pl_starter_field('Opening date','date',$openingInput['date']??'','date'); pl_starter_field('Reason','reason',$openingInput['reason']??''); ?></div><?php for ($i=0;$i<max(5,min(500,count($openingInput['lines']??[])+1));$i++): ?><fieldset class="starter-line"><legend>Opening product <?= $i+1 ?></legend><div class="starter-grid"><?php pl_starter_select('Product',"lines[$i][product_id]",pl_starter_options($stockProducts),$openingInput['lines'][$i]['product_id']??'',false); pl_starter_field('Quantity',"lines[$i][quantity]",$openingInput['lines'][$i]['quantity']??'','text',false); pl_starter_field('Opening carrying value',"lines[$i][amount_base]",$openingInput['lines'][$i]['amount_base']??'','text',false); ?></div></fieldset><?php endfor; ?><button class="button secondary">Preview opening stock</button></form></details><?php endif; ?>
<?php if ($preview && $write && $company['role']==='owner'): ?><section class="panel"><h2>Confirm opening stock</h2><?php foreach ($preview['payload']['lines'] as $line): ?><p>Product <?= (int)$line['product_id'] ?> · Quantity <?= pl_e($line['quantity']) ?> · Value <?= pl_e($line['amount_base']) ?></p><?php endforeach; ?><form method="post" action="<?= pl_e(pl_url('/inventory')) ?>"><?php pl_starter_form($company,'opening_confirm',['preview_id'=>$confirmInput?($confirmInput['preview_id']??''):$preview['id'],'expected_hash'=>$confirmInput?($confirmInput['expected_hash']??''):$preview['payload_hash'],'request_key'=>$confirmInput['request_key']??null]); ?><p><label><input type="checkbox" name="confirmed" required value="1" <?= ($confirmInput['confirmed']??'')==='1'?'checked':'' ?>> I reviewed the product quantities and their reconciliation to opening balances.</label></p><button class="button primary">Confirm opening conversion</button><?php if ($confirmInput): ?><a class="button secondary" href="<?= pl_e(pl_url('/inventory')) ?>">Reload current preview</a><?php endif; ?></form></section><?php endif; ?>
</section>
