<?php declare(strict_types=1); ?>
<div class="page-wrap">
    <?php pl_ui_page_header('Opening balances & cutover', 'Record the balances at the close of ' . pl_date_label($company['start_date']) . '. New transactions belong after this day.'); ?>
    <?php if ($form['message']): ?><div class="alert" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
    <details class="panel"><summary class="text-sm font-semibold">One balanced starting point</summary><p>Use a reviewed trial balance and the remaining amounts on unpaid invoices and bills. The unpaid-document register must match receivables and payables exactly. Confirmation posts the balances once; the register preserves supporting detail without posting those amounts a second time.</p><p class="small muted">This records a cutover snapshot. Invoice collection, bill settlement, credit notes, tax, stock valuation and detailed historical journal imports need their own workflows. Mid-year cutovers must include reviewed year-to-date income and expense balances.</p></details>
    <?php if ($preview): $payload = $preview['payload']; ?>
    <section class="panel"><p class="eyebrow"><?= $reviewing ? 'Review before posting' : 'Saved source evidence' ?></p><h2>Cutover preview #<?= (int) $preview['id'] ?></h2><p><?= pl_e($payload['source']) ?> · <?= pl_e(pl_date_label($payload['cutover_date'])) ?> · <?= pl_e($payload['currency']) ?></p>
        <div class="table-wrap"><table class="data-table"><caption class="sr-only">Opening trial balance</caption><thead><tr><th>Account</th><th class="amount">Debit</th><th class="amount">Credit</th></tr></thead><tbody>
        <?php foreach ($payload['balances'] as $balance): ?><tr><td><?= pl_e($balance['account_code']) ?></td><td class="amount"><?= pl_e(pl_money($balance['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($balance['credit'])) ?></td></tr><?php endforeach; ?>
        <?php if ($payload['balances'] === []): ?><tr><td colspan="3">Explicit zero opening. No journal is needed.</td></tr><?php endif; ?>
        </tbody><tfoot><tr><th>Balanced totals</th><td class="amount"><?= pl_e(pl_money($payload['total_debit'])) ?></td><td class="amount"><?= pl_e(pl_money($payload['total_credit'])) ?></td></tr></tfoot></table></div>
        <h3>Unpaid documents (<?= count($payload['unpaid_documents']) ?>)</h3>
        <?php if ($payload['unpaid_documents']): ?><div class="table-wrap"><table class="data-table"><caption class="sr-only">Unpaid document source register</caption><thead><tr><th>Kind / account</th><th>Customer or vendor</th><th>Reference</th><th>Document date</th><th>Due</th><th class="amount">Remaining</th></tr></thead><tbody>
        <?php foreach ($payload['unpaid_documents'] as $document): ?><tr><td><?= pl_e(ucfirst($document['kind']) . ' / ' . $document['account_code']) ?></td><td><?= pl_e($document['party']) ?></td><td><?= pl_e($document['reference']) ?></td><td><?= pl_e($document['document_date']) ?></td><td><?= pl_e($document['due_date']) ?></td><td class="amount"><?= pl_e(pl_money($document['outstanding'])) ?></td></tr><?php endforeach; ?>
        </tbody></table></div><?php else: ?><p>No unpaid invoices or bills. Control balances are zero.</p><?php endif; ?>
        <?php if ($reviewing && $company['setup_status'] === 'opening_required' && pl_can_write($company)): ?>
        <form method="post" action="<?= pl_e(pl_url('/opening-balances')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="confirm"><input type="hidden" name="preview_id" value="<?= (int) $preview['id'] ?>"><input type="hidden" name="payload_hash" value="<?= pl_e($preview['payload_hash']) ?>">
            <label class="checkbox"><input type="checkbox" name="confirmed" value="1" required> I checked the balanced totals against the source records and included all unpaid documents.</label><div class="form-actions"><button class="button primary" type="submit">Confirm opening balances</button><a class="button secondary" href="<?= pl_e(pl_url('/opening-balances')) ?>">Prepare a different preview</a></div>
        </form><?php endif; ?>
    </section><?php endif; ?>
    <?php if (!$reviewing && $company['setup_status'] === 'opening_required' && pl_can_write($company)): ?>
    <form class="panel" method="post" enctype="multipart/form-data" action="<?= pl_e(pl_url('/opening-balances')) ?>">
        <?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="preview"><input type="hidden" name="request_key" value="<?= pl_e(bin2hex(random_bytes(24))) ?>">
        <h2>Prepare the opening balances</h2><div class="form-grid"><label class="field">Cutover date<input type="date" name="cutover_date" value="<?= pl_e($company['start_date']) ?>" readonly required></label><label class="field">Source records reference<input name="source" maxlength="200" value="<?= pl_e(pl_web_text($input, 'source')) ?>" placeholder="Reviewed trial balance and unpaid list" required></label></div>
        <p class="small muted">Enter decimal points without separators, up to four decimal places. Leave zero balances blank.</p>
        <div class="table-wrap max-h-44 overflow-y-auto" tabindex="0" role="region" aria-label="Enter account balances"><table class="table"><caption class="sr-only">Enter account balances</caption><thead><tr><th>Account</th><th class="amount">Debit</th><th class="amount">Credit</th></tr></thead><tbody>
        <?php foreach ($company['accounts'] as $account): if (!$account['is_active']) { continue; } ?><tr><th scope="row"><?= pl_e($account['code'] . ' · ' . $account['name']) ?></th><td><input class="opening-amount" aria-label="<?= pl_e($account['name'] . ' debit') ?>" name="debit_<?= (int) $account['id'] ?>" inputmode="decimal" value="<?= pl_e(pl_web_text($input, 'debit_' . $account['id'])) ?>"></td><td><input class="opening-amount" aria-label="<?= pl_e($account['name'] . ' credit') ?>" name="credit_<?= (int) $account['id'] ?>" inputmode="decimal" value="<?= pl_e(pl_web_text($input, 'credit_' . $account['id'])) ?>"></td></tr><?php endforeach; ?>
        </tbody></table></div>
        <details<?= pl_web_text($input, 'balances_csv') !== '' ? ' open' : '' ?>><summary>Import account balances from CSV instead</summary><p class="small muted">A supplied CSV replaces the fields above. Header: <code>account_code,debit,credit</code>. Use this book's exact account codes, up to 500 rows / 512 KiB.</p><label class="field">Balance CSV file<input type="file" name="balances_csv_file" accept=".csv,text/csv"></label><label class="field">Or paste balance CSV<textarea name="balances_csv" rows="5"><?= pl_e(pl_web_text($input, 'balances_csv')) ?></textarea></label></details>
        <details<?= pl_web_text($input, 'documents_csv') !== '' ? ' open' : '' ?>><summary>Bring unpaid invoices and bills</summary><p class="small muted">Header: <code>kind,account_code,party,reference,document_date,due_date,outstanding</code>. Use <code>receivable</code> or <code>payable</code>, dates in YYYY-MM-DD, and each document's remaining unpaid amount. Amounts use this book's base currency.</p><label class="field">Unpaid-document CSV file<input type="file" name="documents_csv_file" accept=".csv,text/csv"></label><label class="field">Or paste unpaid-document CSV<textarea name="documents_csv" rows="6"><?= pl_e(pl_web_text($input, 'documents_csv')) ?></textarea></label></details>
        <label class="checkbox"><input type="checkbox" name="zero_confirmed" value="1"<?= pl_web_text($input, 'zero_confirmed') === '1' ? ' checked' : '' ?>> If all balances are zero, I confirm there are no opening balances or unpaid documents.</label>
        <div class="panel-actions" data-fold="primary action"><button class="btn btn-primary" type="submit">Preview and validate</button><p class="panel-actions-note">A preview has no effect on the books. You will review the totals before confirmation.</p></div>
    </form>
    <?php elseif (!$reviewing && $history === []): ?><div class="panel"><p><?= $company['setup_status'] === 'opening_required' ? 'An authorised owner can prepare and confirm these balances.' : 'This business does not need an opening cutover.' ?></p></div><?php endif; ?>
    <?php if ($history): ?><section class="panel"><h2>Cutover history</h2><div class="table-wrap"><table class="data-table"><caption class="sr-only">Confirmation and correction history</caption><thead><tr><th>Cutover</th><th>Status</th><th>Confirmed</th><th>Journal</th><th>Correction</th></tr></thead><tbody>
    <?php foreach ($history as $cutover): ?><tr><td>#<?= (int) $cutover['id'] ?> · <?= pl_e($cutover['cutover_date']) ?></td><td><?= pl_e(ucfirst($cutover['status'])) ?></td><td><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $cutover['confirmed_at']) . 'Z') ?>"><?= pl_e($cutover['confirmed_at']) ?> UTC</time></td><td><?php if ($cutover['journal_id']): ?><a href="<?= pl_e(pl_url('/journals/detail', ['id' => $cutover['journal_id']])) ?>">View journal</a><?php else: ?>Zero opening<?php endif; ?></td><td><?php if ($cutover['reversed_journal_id']): ?><a href="<?= pl_e(pl_url('/journals/detail', ['id' => $cutover['reversed_journal_id']])) ?>">Linked reversal</a><?php endif; ?> <?= pl_e($cutover['reversal_reason'] ?? '') ?></td></tr><?php endforeach; ?>
    </tbody></table></div>
    <?php if ($company['role'] === 'owner' && $history[0]['status'] === 'confirmed'): ?><details<?= pl_web_text($input, 'action') === 'reverse' ? ' open' : '' ?>><summary>Correct an opening cutover</summary><p>You can reverse and restart only before any transactions, drafts or bank statements exist, while the cutover period remains open. The original records and linked reversal remain in history.</p><form method="post" action="<?= pl_e(pl_url('/opening-balances')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="reverse"><input type="hidden" name="cutover_id" value="<?= (int) $history[0]['id'] ?>"><label class="field">Correction reason<input name="reason" maxlength="400" value="<?= pl_e(pl_web_text($input, 'reason')) ?>" required></label><button class="button secondary" type="submit">Reverse cutover and restart review</button></form></details><?php endif; ?>
    </section><?php endif; ?>
    <div class="form-actions"><a class="button secondary" href="<?= pl_e(pl_url('/periods')) ?>">Period administration</a><a class="button secondary" href="<?= pl_e(pl_url('/bank-reconciliation')) ?>">Bank reconciliation</a></div>
</div>
