<?php declare(strict_types=1);
$partyInput=($form['input']['action']??'')==='save'?$form['input']:[];
$contactInput=($form['input']['action']??'')==='contact'?$form['input']:[];
$v=$partyInput?:($party?array_merge($party,$party['financial']??[]):['currency'=>$company['currency'],'entity_type'=>'business']); ?>
<section class="page-wrap starter-detail">
<?php pl_starter_header('Customers and vendors','One shared party record can be both a customer and a vendor.',$form,$company); ?>
<?php if (pl_can_write($company)): ?><div class="starter-actions"><a class="button secondary" href="<?= pl_e(pl_url('/parties',['new'=>'1'])) ?>">New party</a></div><?php endif; ?>
<?php if ($party || isset($_GET['new']) || $partyInput): ?>
<section class="panel"><h2><?= $party?pl_e($party['legal_name']):'New party' ?></h2>
<?php if (pl_can_write($company)): ?><form method="post" action="<?= pl_e(pl_url('/parties')) ?>">
<?php pl_starter_form($company,'save',['id'=>$party['id']??0,'revision'=>$partyInput['revision']??$party['revision']??0,'request_key'=>$partyInput['request_key']??bin2hex(random_bytes(20))]); ?>
<div class="starter-grid">
<?php pl_starter_field('Legal name','legal_name',$v['legal_name']??''); pl_starter_field('Trading name','trading_name',$v['trading_name']??'','text',false);
pl_starter_field('Entity type','entity_type',$v['entity_type']??'business'); pl_starter_field('Country code (two letters)','country_code',$v['country_code']??'');
pl_starter_field('Default currency','currency',$v['currency']??$company['currency']); pl_starter_field('Payment terms','payment_terms',$v['payment_terms']??'','text',false);
pl_starter_select('Receivables account override','ar_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['role']==='receivables')),$v['ar_account_id']??'',false);
pl_starter_select('Payables account override','ap_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['role']==='payables')),$v['ap_account_id']??'',false);
pl_starter_field('Reason','reason',$partyInput['reason']??''); ?>
</div><p><label><input type="checkbox" name="is_customer" value="1" <?= !empty($v['is_customer'])?'checked':'' ?>> Customer</label> <label><input type="checkbox" name="is_vendor" value="1" <?= !empty($v['is_vendor'])?'checked':'' ?>> Vendor</label></p>
<?php if (!$party): ?><details <?= !empty($v['identifier_value'])?'open':'' ?>><summary>Legal identifier (optional)</summary><div class="starter-grid"><?php pl_starter_field('Identifier scheme, e.g. TAX_ID','identifier_scheme',$v['identifier_scheme']??'','text',false); pl_starter_field('Identifier value','identifier_value',$v['identifier_value']??'','text',false); ?></div></details><?php endif; ?>
<button class="button primary">Save party</button><?php if ($partyInput && $party): ?> <a href="<?= pl_e(pl_url('/parties',['id'=>$party['id']])) ?>">Reload saved party</a><?php endif; ?></form><?php else: ?><dl><dt>Country</dt><dd><?= pl_e($party['country_code']) ?></dd><dt>Currency</dt><dd><?= pl_e($party['financial']['currency']??$company['currency']) ?></dd><dt>Payment terms</dt><dd><?= pl_e($party['financial']['payment_terms']??'') ?></dd></dl><p>You have read-only access.</p><?php endif; ?>
<?php if ($party && $party['identifiers']): ?><h3>Legal identifiers</h3><?php foreach ($party['identifiers'] as $identifier): ?><p><?= pl_e($identifier['country_code'].' / '.$identifier['scheme'].': '.$identifier['value']) ?></p><?php endforeach; endif; ?>
</section><?php endif; ?>
<?php if ($party): ?><section class="panel"><h2>Contacts</h2><?php foreach ($contacts as $contact): ?><p><strong><?= pl_e($contact['name']) ?></strong> | <?= pl_e(str_replace('_',' ',$contact['role'])) ?><?= $contact['is_primary']?' | Primary':'' ?><br><?= pl_e($contact['email']) ?><?= $contact['phones']?' | '.pl_e($contact['phones']):'' ?></p><?php endforeach; ?><?php if (!$contacts): ?><p>No contacts yet.</p><?php endif; ?>
<?php if (pl_can_write($company)): ?><details <?= $contactInput?'open':'' ?>><summary>Add contact</summary><form method="post" action="<?= pl_e(pl_url('/parties')) ?>"><?php pl_starter_form($company,'contact',['id'=>$party['id'],'request_key'=>$contactInput['request_key']??bin2hex(random_bytes(20))]); ?><div class="starter-grid">
<?php pl_starter_field('Name','name',$contactInput['name']??''); pl_starter_field('Email','email',$contactInput['email']??'','email',false); pl_starter_field('Phone with country code','phone',$contactInput['phone']??'','tel',false); pl_starter_select('Role','role',['billing'=>'Billing','receiving'=>'Receiving','authorised_signatory'=>'Authorised signatory','owner'=>'Owner'],$contactInput['role']??'billing'); pl_starter_field('Reason','reason',$contactInput['reason']??''); ?></div>
<p><label><input type="checkbox" name="is_primary" value="1" <?= !empty($contactInput['is_primary'])?'checked':'' ?>> Primary contact</label></p><details <?= $contactInput?'open':'' ?>><summary>Shared phone acknowledgement</summary><p><label><input type="checkbox" name="acknowledge_phone_duplicates" value="1" <?= !empty($contactInput['acknowledge_phone_duplicates'])?'checked':'' ?>> I reviewed the duplicate phone and intend to share it.</label></p><?php pl_starter_field('Why this phone is shared','duplicate_reason',$contactInput['duplicate_reason']??'','text',false); ?></details><button class="button secondary">Save contact</button></form></details><?php endif; ?></section><?php endif; ?>
<section class="panel starter-report"><h2>Party register</h2><table class="data-table"><thead><tr><th>Legal name</th><th>Customer</th><th>Vendor</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><a href="<?= pl_e(pl_url('/parties',['id'=>$row['id']])) ?>"><?= pl_e($row['legal_name']) ?></a></td><td><?= $row['is_customer']?'Yes':'No' ?></td><td><?= $row['is_vendor']?'Yes':'No' ?></td></tr><?php endforeach; ?><?php if (!$rows): ?><tr><td colspan="3">No parties yet. Add a customer or vendor to begin.</td></tr><?php endif; ?></tbody></table></section>
</section>
