<?php declare(strict_types=1);
$write = $enabled && pl_can_write($company);
$submitted=$form['input'];
$saveInput=($submitted['action']??'')==='save'?$submitted:[];
$confirmInput=($submitted['action']??'')==='confirm'?$submitted:[];
$cancelInput=($submitted['action']??'')==='cancel'?$submitted:[];
$receiveInput=($submitted['action']??'')==='receive'?$submitted:[];
$billInput=($submitted['action']??'')==='bill_preview'?$submitted:($preview['input']??[]);
$billConfirmInput=($submitted['action']??'')==='bill_confirm'?$submitted:[];
$v=$saveInput?:($order??[]);
$receiveQuantities=[];
foreach ($receiveInput['lines']??[] as $line) { $receiveQuantities[(int)($line['order_line_id']??0)]=$line['quantity']??''; }
$billLines=[];
foreach ($billInput['lines']??[] as $line) { $billLines[(int)($line['receipt_line_id']??0)]=$line; }
$hasUnreceived=$order && array_filter($order['lines'],static fn(array $line):bool=>bccomp($line['remaining_quantity'],'0',4)>0)!==[];
$editing = isset($_GET['new']) || ($order && $order['status'] === 'draft') || (($v['action'] ?? '') === 'save');
$supplierOptions = pl_starter_options(array_filter($parties, static fn(array $p): bool => (bool) $p['is_vendor']), 'legal_name');
$productOptions = pl_starter_options(array_filter($products, static fn(array $p): bool => $p['kind'] === 'stock'));
$grniOptions = pl_starter_options(array_filter($accounts, static fn(array $a): bool => $a['type'] === 'liability' && !in_array($a['role'], ['payables', 'receivables', 'cash_bank'], true)));
$varianceOptions = pl_starter_options(array_filter($accounts, static fn(array $a): bool => in_array($a['type'], ['expense', 'income'], true)));
$roundingOptions = pl_starter_options(array_filter($accounts, static fn(array $a): bool => $a['type'] === 'expense'));
$receiptRows = array_values(array_filter($receipts, static fn(array $r): bool => !$order || (int) $r['order_id'] === $order['id']));
$billRows = array_values(array_filter($receiptRows, static fn(array $r): bool => bccomp($r['unbilled_quantity'], '0', 4) > 0));
if ($editing && $write) { require dirname(__DIR__).'/partials/ui/purchase-order-editor.php'; return; }
?>
<section class="page-wrap starter-detail">
<?php pl_starter_header('Purchasing', 'Order goods, record partial deliveries, match supplier bills and reconcile received goods awaiting billing.', $form, $company); ?>
<?php if (!$enabled): ?><p class="starter-note">Purchasing is disabled for new operations. Orders, receipt history and reconciliation remain available. <a href="<?= pl_e(pl_url('/modules')) ?>">Review modules</a>.</p><?php endif; ?>
<div class="starter-actions"><?php if ($write): ?><a class="button primary" href="<?= pl_e(pl_url('/purchasing', ['new' => '1'])) ?>">New purchase order</a><?php endif; ?><a class="button secondary" href="<?= pl_e(pl_url('/inventory')) ?>">Products and stock</a><?php if (pl_can_write($company)): ?><a class="button secondary" href="<?= pl_e(pl_url('/parties', ['new' => '1'])) ?>">Add supplier</a><?php endif; ?><a class="button secondary" href="<?= pl_e(pl_url('/accounts')) ?>">Manage accounts</a></div>
<?php if ($order): ?><section class="panel"><h2><?= pl_e($order['number']) ?>&nbsp; <span class="badge"><?= pl_e(ucfirst($order['status'])) ?></span></h2><p><?= pl_e($order['party_name'] . ' · ' . $order['document_date'] . ' · ' . $order['reference']) ?></p><div class="starter-report"><table class="data-table"><thead><tr><th>Goods</th><th>Ordered</th><th>Received</th><th>Unreceived</th><th>Unit price</th><th>Order value</th></tr></thead><tbody><?php foreach ($order['lines'] as $line): ?><tr><td><?= pl_e($line['description']) ?></td><td><?= pl_e($line['quantity']) ?></td><td><?= pl_e($line['received_quantity']) ?></td><td><?= pl_e($line['remaining_quantity']) ?></td><td><?= pl_e($line['unit_price']) ?></td><td><?= pl_e($line['amount']) ?></td></tr><?php endforeach; ?></tbody></table></div><p>Total order value <strong><?= pl_e($order['currency'] . ' ' . pl_money($order['total'])) ?></strong></p>
<?php if ($write && $order['status'] === 'draft'): ?><form method="post" action="<?= pl_e(pl_url('/purchasing')) ?>"><?php pl_starter_form($company, 'confirm', ['id' => $order['id'], 'revision' => $confirmInput?($confirmInput['revision']??''):$order['revision'],'request_key'=>$confirmInput['request_key']??null]); ?><button class="button primary">Confirm reviewed order</button><?php if ($confirmInput): ?><a class="button secondary" href="<?= pl_e(pl_url('/purchasing',['id'=>$order['id']])) ?>">Reload current order for review</a><?php endif; ?></form><?php endif; ?>
<?php if ($write && $order['status'] !== 'cancelled' && $hasUnreceived): ?><details <?= $cancelInput?'open':'' ?>><summary>Cancel unreceived quantities</summary><p>Existing receipts and supplier bills remain in their ledgers.</p><form method="post" action="<?= pl_e(pl_url('/purchasing')) ?>"><?php pl_starter_form($company, 'cancel', ['id' => $order['id'], 'revision' => $cancelInput?($cancelInput['revision']??''):$order['revision'],'request_key'=>$cancelInput['request_key']??null]); pl_starter_field('Cancellation reason', 'reason',$cancelInput['reason']??''); ?><button class="button secondary">Cancel remaining order</button><?php if ($cancelInput): ?><a class="button secondary" href="<?= pl_e(pl_url('/purchasing',['id'=>$order['id']])) ?>">Reload current order for review</a><?php endif; ?></form></details><?php endif; ?>
<?php if ($write && $order['status'] === 'confirmed' && $hasUnreceived): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/purchasing',['id'=>$order['id'],'receive'=>'1'])) ?>">Receive goods</a><?php endif; ?><?php if ($order['status']==='confirmed' && !$hasUnreceived): ?><p class="starter-note">All ordered quantities have been received. Receipt history, supplier billing and returns remain available below.</p><?php endif; ?></section><?php endif; ?>
<?php if ($preview && $write): ?><section class="panel"><h2>Review supplier bill</h2><p><?= pl_e($preview['supplier'] . ' · ' . $preview['input']['reference'] . ' · ' . $preview['input']['date']) ?></p><p>Currency <?= pl_e($preview['input']['currency']) ?> · Rate <?= pl_e($preview['rate_snapshot']['rate']) ?></p><div class="starter-report"><table class="data-table"><thead><tr><th>Received goods</th><th>Bill quantity</th><th>Net amount</th><th>Tax</th><th>Receipt carrying value</th><th>Price/rate variance</th></tr></thead><tbody><?php foreach ($preview['lines'] as $line): ?><tr><td><?= pl_e($line['description']) ?></td><td><?= pl_e($line['quantity']) ?></td><td><?= pl_e($line['net_fc']) ?></td><td><?= pl_e($line['tax']['tax_amount']) ?></td><td><?= pl_e($line['receipt_basis_base']) ?></td><td><?= pl_e($line['variance_base']) ?></td></tr><?php endforeach; ?></tbody></table></div><p>Total payable <strong><?= pl_e($preview['input']['currency'] . ' ' . $preview['total_fc']) ?></strong> · Purchase variance <?= pl_e($company['currency'] . ' ' . $preview['variance_base']) ?></p><form method="post" action="<?= pl_e(pl_url('/purchasing')) ?>"><?php pl_starter_form($company, 'bill_confirm', ['id' => $order['id'] ?? 0, 'expected_hash' => $billConfirmInput?($billConfirmInput['expected_hash']??''):$preview['payload_hash'],'request_key'=>$billConfirmInput['request_key']??$preview['input']['idempotency_key']]); ?><p><label><input type="checkbox" name="confirmed" value="1" required <?= ($billConfirmInput['confirmed']??'')==='1'?'checked':'' ?>> I reviewed the supplier, matched quantities, payable amount, taxes and price/rate differences.</label></p><button class="button primary">Post supplier bill and match receipts</button><?php if ($billConfirmInput): ?><a class="button secondary" href="<?= pl_e(pl_url('/purchasing',['id'=>$order['id']??null])) ?>">Reload current bill review</a><?php endif; ?></form></section><?php endif; ?>
<?php if ($write && $billRows): ?><details class="panel" <?= $order || $billInput ? 'open' : '' ?>><summary>Create supplier bill from receipts</summary><p>Enter quantities to bill below; leave unused receipt lines blank. All selected receipts must belong to the same supplier, currency and clearing account. Stock is already recorded.</p><form method="post" action="<?= pl_e(pl_url('/purchasing')) ?>"><?php pl_starter_form($company, 'bill_preview', ['id' => $order['id'] ?? 0,'request_key'=>$billInput['request_key']??$billInput['idempotency_key']??null]); ?><div class="starter-grid"><?php pl_starter_select('Supplier', 'party_id', $supplierOptions, $billInput['party_id']??$order['party_id']??''); pl_starter_field('Bill date', 'date', $billInput['date']??gmdate('Y-m-d'), 'date'); pl_starter_field('Due date', 'due_date', $billInput['due_date']??gmdate('Y-m-d'), 'date'); pl_starter_field('Currency', 'currency', $billInput['currency']??$order['currency']??$company['currency']); pl_starter_field('Supplier reference', 'reference', $billInput['reference']??'', 'text', false); pl_starter_select('Supplier bill prices', 'price_mode', ['exclusive' => 'Tax-exclusive: add selected tax', 'inclusive' => 'Tax-inclusive: entered price includes tax'], $billInput['price_mode']??$priceMode); pl_starter_select('Received-but-unbilled liability account', 'grni_account_id', $grniOptions, $billInput['grni_account_id']??$billRows[0]['grni_account_id']); pl_starter_field('Manual bill rate to ' . $company['currency'], 'rate', $billInput['rate']??'', 'text', false); pl_starter_select('Purchase variance account', 'variance_account_id', $varianceOptions, $billInput['variance_account_id']??'', false); pl_starter_select('Currency rounding expense account', 'rounding_account_id', $roundingOptions, $billInput['rounding_account_id']??'', false); ?></div>
<?php foreach (array_slice($billRows, 0, 100) as $i => $receipt): $billLine=$billLines[(int)$receipt['id']]??[]; ?><fieldset class="starter-line"><legend>Receipt <?= (int) $receipt['receipt_id'] ?> · <?= pl_e($receipt['description']) ?></legend><p><?= pl_e($receipt['document_date']) ?> · Supplier <?= pl_e($supplierOptions[(string) $receipt['party_id']] ?? '') ?> · Unbilled <?= pl_e($receipt['unbilled_quantity']) ?> · Receipt cost <?= pl_e($receipt['currency'] . ' ' . $receipt['unit_price']) ?></p><?php pl_starter_hidden("lines[$i][receipt_line_id]", $receipt['id']); ?><div class="starter-grid"><?php pl_starter_field('Quantity on bill', "lines[$i][quantity]", $billLine['quantity']??'', 'text', false); pl_starter_field('Unit price on bill', "lines[$i][unit_price]", $billLine['unit_price']??$receipt['unit_price'], 'text', false); pl_starter_select('Input tax code', "lines[$i][tax_code_id]", pl_starter_options($taxCodes), $billLine['tax_code_id']??'', false); ?></div></fieldset><?php endforeach; ?>
<p><label><input type="checkbox" name="variance_confirmed" value="1" <?= in_array($billInput['variance_confirmed']??false,[true,'1'],true)?'checked':'' ?>> Any price/rate difference is intentional and should use the selected variance account.</label></p><button class="button primary">Preview supplier bill</button></form></details><?php endif; ?>
<section class="panel"><h2>Goods receipts and returns</h2><?php if (!$receiptRows): ?><p class="muted">No goods received yet.</p><?php endif; ?>
<?php foreach ($receiptRows as $receipt): $returnInput=($submitted['action']??'')==='return'&&(int)($submitted['receipt_line_id']??0)===(int)$receipt['id']?$submitted:[]; ?><details <?= $returnInput?'open':'' ?>><summary>Receipt <?= (int) $receipt['receipt_id'] ?> · <?= pl_e($receipt['description'] . ' · ' . $receipt['document_date']) ?></summary><p>Received <?= pl_e($receipt['quantity']) ?> · Unbilled <?= pl_e($receipt['unbilled_quantity']) ?> · Returned <?= pl_e($receipt['returned_quantity']) ?> · <a href="<?= pl_e(pl_url('/journals/detail', ['id' => $receipt['journal_id']])) ?>">Receipt journal</a></p>
<?php foreach ($receipt['matches'] as $match): ?><p><a href="<?= pl_e(pl_url('/ap', ['id' => $match['bill_document_id']])) ?>">Supplier bill <?= (int) $match['bill_document_id'] ?></a> · Matched quantity <?= pl_e($match['quantity']) ?> · Unit price <?= pl_e($match['unit_price']) ?></p><?php endforeach; ?>
<?php foreach ($receipt['returns'] as $return): ?><p>Returned <?= pl_e($return['quantity'] . ' on ' . $return['document_date']) ?> · <?= pl_e($return['reason']) ?><?php if ($return['credit_document_id']): ?> · <a href="<?= pl_e(pl_url('/ap', ['id' => $return['credit_document_id']])) ?>">Supplier credit</a><?php endif; ?></p><?php endforeach; ?>
<?php if ($write): $matchOptions = ['0' => 'Unbilled goods: no supplier credit']; foreach ($receipt['matches'] as $match) { $matchOptions[(string) $match['id']] = 'Bill ' . $match['bill_document_id'] . ', line ' . $match['bill_line_number']; } ?><form method="post" action="<?= pl_e(pl_url('/purchasing')) ?>"><?php pl_starter_form($company, 'return', ['id' => $order['id'] ?? 0, 'receipt_line_id' => $receipt['id'],'request_key'=>$returnInput['request_key']??null]); ?><div class="starter-grid"><?php pl_starter_select('Return against', 'match_id', $matchOptions, $returnInput['match_id']??'0'); pl_starter_field('Quantity to return', 'quantity',$returnInput['quantity']??''); pl_starter_field('Return date', 'date', $returnInput['date']??gmdate('Y-m-d'), 'date'); pl_starter_field('Return reason', 'reason',$returnInput['reason']??''); pl_starter_select('Variance account if rounding differs', 'variance_account_id', $varianceOptions, $returnInput['variance_account_id']??'', false); pl_starter_select('Currency rounding expense account', 'rounding_account_id', $roundingOptions, $returnInput['rounding_account_id']??'', false); ?></div><p><label><input type="checkbox" name="variance_confirmed" value="1" <?= ($returnInput['variance_confirmed']??'')==='1'?'checked':'' ?>> Apply a carrying-value rounding difference to the selected variance account.</label></p><p><label><input type="checkbox" name="confirmed" value="1" required <?= ($returnInput['confirmed']??'')==='1'?'checked':'' ?>> These goods are returned; create the linked supplier credit when billed.</label></p><button class="button secondary">Record purchase return</button></form><?php endif; ?></details><?php endforeach; ?></section>
<section class="panel"><h2>Received-but-unbilled reconciliation</h2><form method="get" action="<?= pl_e(pl_url('/purchasing')) ?>"><?php if ($order) { pl_starter_hidden('id', $order['id']); } pl_starter_field('As of', 'as_of', $reconciliation['as_of'], 'date'); ?><button class="button secondary">Refresh reconciliation</button></form><div class="starter-report"><table class="data-table"><thead><tr><th>Clearing account</th><th>Receipt balance</th><th>Ledger balance</th><th>Difference</th></tr></thead><tbody><?php foreach ($reconciliation['accounts'] as $account): ?><tr><td><a href="<?= pl_e(pl_url('/reports/account', ['id' => $account['account_id']])) ?>"><?= pl_e($grniOptions[(string) $account['account_id']] ?? (string) $account['account_id']) ?></a></td><td><?= pl_e($account['unbilled_base']) ?></td><td><?= pl_e($account['ledger_base']) ?></td><td><strong><?= pl_e($account['difference']) ?></strong></td></tr><?php endforeach; ?><?php if (!$reconciliation['accounts']): ?><tr><td colspan="4">No receipt balances to reconcile.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="panel starter-report"><h2>Purchase orders</h2><table class="data-table"><thead><tr><th>Order</th><th>Supplier</th><th>Date</th><th>Status</th><th>Value</th></tr></thead><tbody><?php foreach ($orders as $row): ?><tr><td><a href="<?= pl_e(pl_url('/purchasing', ['id' => $row['id']])) ?>"><?= pl_e($row['number']) ?></a></td><td><?= pl_e($row['party_name']) ?></td><td><?= pl_e($row['document_date']) ?></td><td><?= pl_e($row['status']) ?></td><td><?= pl_e($row['currency'] . ' ' . $row['total']) ?></td></tr><?php endforeach; ?><?php if (!$orders): ?><tr><td colspan="5">No purchase orders yet.</td></tr><?php endif; ?></tbody></table></section>
</section>
