<?php declare(strict_types=1); ?>
<section class="page-wrap sample-guide">
    <header class="page-heading"><div><p class="eyebrow"><?= pl_e($pack['business']) ?> · Your private practice books</p><h1><?= pl_e($pack['name']) ?></h1><p>Two years of history. A new year to practise. Follow a figure to its source, then try an editable draft.</p></div><a class="button primary" href="<?= pl_e(pl_url('/transactions', ['status' => 'draft'])) ?>">Open the three practice drafts <?= pl_icon('arrow-right') ?></a></header>
    <div class="panel sample-overview"><div><strong>2024–2025 · Historical periods closed</strong><p>The original history is reconciled month by month. Closed periods reject new postings. The 2024 annual period and twelve 2025 monthly periods do not overlap.</p></div><div><strong>2026 · Open practice year</strong><p>January is posted; February has three editable drafts. Choose a date in 2026 for your own entries. The original pack has 74 source records, leaving 26 new records at the default demo limit.</p></div></div>
    <p class="notice sample-note">All names and amounts are fictional. <?= pl_e($pack['notice']) ?></p>

    <div class="sample-journeys">
        <article class="panel"><p class="eyebrow">1 · Daily checks</p><h2>Where did the money go?</h2><p>On <strong>15 January 2026</strong>, the bank receipt summary records <strong><?= pl_e(pl_money($pack['monthly_support'][24]['bank_receipts'])) ?> <?= pl_e($company['currency']) ?></strong>. Open its source, then inspect the primary bank's movements for that day.</p><ul><li><a href="<?= pl_e(pl_url('/transactions/detail', ['id' => $sourceIds['receipt']])) ?>">Read the January receipt</a></li><li><a href="<?= pl_e(pl_url('/reports/account', ['id' => $accountIds['1000'], 'from' => '2026-01-15', 'as_of' => '2026-01-15'])) ?>">Check that day's bank movements</a></li><li><a href="<?= pl_e(pl_url('/reports/account', ['id' => $accountIds['1030'], 'from' => '2026-01-01', 'as_of' => '2026-02-28'])) ?>">Compare petty cash before and after a draft</a></li></ul><p class="small muted">The receipt is an illustrative monthly summary dated on the 15th. Cash sales appear separately in the month-end support journal. Neither is an imported bank statement.</p></article>
        <article class="panel"><p class="eyebrow">2 · Monthly closing</p><h2>Check December's adjustments</h2><p>Read <strong>December 2025</strong> on its own. Inspect salaries, insurance released from prepayments, depreciation, and the <strong>550.00</strong> maintenance bill still unpaid at year end.</p><ul><li><a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2025-12-01', 'to' => '2025-12-31'])) ?>">December profit and loss</a></li><li><a href="<?= pl_e(pl_url('/general-journals/detail', ['id' => $sourceIds['operations']])) ?>">Open December's support journal</a></li><li><a href="<?= pl_e(pl_url('/reports/account', ['id' => $accountIds['2000'], 'from' => '2025-12-01', 'as_of' => '2026-01-31'])) ?>">Follow the bill into January's payment</a></li></ul><p class="small muted">Closing a period prevents backdated posting. It does not certify statements or move profit into retained earnings. The Balance Sheet shows accumulated unclosed earnings once.</p></article>
        <article class="panel"><p class="eyebrow">3 · Quarterly and annual review</p><h2>Compare separate periods</h2><p>Compare each quarter of <strong>2025</strong>, then the two complete years. Quarter results add to the year's result. Use the same company and currency throughout.</p><ul><li><?php foreach ([['01-01','03-31','Q1'],['04-01','06-30','Q2'],['07-01','09-30','Q3'],['10-01','12-31','Q4']] as [$fromDate, $toDate, $label]): ?><a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2025-' . $fromDate, 'to' => '2025-' . $toDate])) ?>"><?= pl_e($label) ?></a> <?php endforeach; ?></li><li><a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2024-01-01', 'to' => '2024-12-31'])) ?>">2024 profit and loss</a> · <a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2025-01-01', 'to' => '2025-12-31'])) ?>">2025 profit and loss</a></li><li><a href="<?= pl_e(pl_url('/reports/balance-sheet', ['as_of' => '2025-12-31'])) ?>">2025 Balance Sheet</a> · <a href="<?= pl_e(pl_url('/reports/trial-balance', ['as_of' => '2025-12-31'])) ?>">2025 Trial Balance</a></li></ul><p class="small muted">Year-end loans have 3,600.00 principal outstanding. Equipment cost is 2,400.00 and accumulated depreciation is 920.00. Amounts use your chosen base currency; no foreign-exchange conversion occurs.</p></article>
    </div>

    <section class="panel"><h2>Manual support schedules</h2><p>These authored schedules explain the general-ledger entries. They are examples to read, not operational payroll, customer/vendor subledgers or a stock module.</p>
        <dl class="sample-schedules"><div><dt>Staff and cash</dt><dd>Mira Vale: 600.00 per month; Noel Reed: 900.00. The 420.00 December 2024 bonus is paid in January 2025. Rent uses the reserve bank; utilities use 90.00 from the primary bank and 10.00 petty cash each posted month. No deductions or payroll tax are calculated.</dd></div><div><dt>Assets, prepayments and loan</dt><dd>Equipment: cost 2,400.00, illustrative 60-month life, zero residual, 40.00 monthly from February 2024. Insurance is prepaid 1,200.00 each January and released at 100.00 per posted month. A 6,000.00 loan starts in March 2024; each December payment has 1,200.00 principal and an illustrative 300.00 interest component.</dd></div><div><dt>Cross-year items</dt><dd>Alder Customer owes 800.00 on 31 December 2024 and pays in February 2025. Harbor maintenance is owed 550.00 on 31 December 2025 and paid in January 2026. The later settlements do not record the income or expense again.</dd></div><div><dt>Corrections</dt><dd><a href="<?= pl_e(pl_url('/general-journals/detail', ['id' => $sourceIds['correction']])) ?>">The 25.00 mistaken cost</a> is reversed in full on 20 August 2025. The separately referenced replacement records 45.00 on the following day. All three journal entries remain visible.</dd></div></dl>
        <?php if (isset($accountIds['1400'])): ?><p><strong>Manual stock example:</strong> Each posted month records <?= (int) $pack['monthly_support'][0]['units_in'] ?> units purchased and <?= (int) $pack['monthly_support'][0]['units_out'] ?> units sold at an illustrative <?= pl_e(pl_money($pack['monthly_support'][0]['unit_cost'])) ?> per unit. The stock account at December 2025 reconciles to the accumulated unsold units. POS practice does not deduct this stock or calculate cost of sales.</p><?php endif; ?>
        <details><summary>Read the 25 posted monthly support rows</summary><div class="sample-table-scroll" role="region" aria-label="Manual monthly support" tabindex="0"><table><caption>Original fixture support · <?= pl_e($company['currency']) ?> · exact source values have four decimal places</caption><thead><tr><th scope="col">Month</th><th scope="col">Gross receipts</th><th scope="col">Salaries</th><th scope="col">Insurance</th><th scope="col">Depreciation</th><th scope="col">Stock bought</th><th scope="col">Cost of sales</th></tr></thead><tbody><?php foreach ($pack['monthly_support'] as $row): ?><tr><th scope="row"><?= pl_e($row['month']) ?></th><?php foreach (['gross_receipts','salaries','insurance_release','depreciation','stock_purchases','cost_of_sales'] as $key): ?><td><?= pl_e(pl_money($row[$key])) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></details>
    </section>
    <section class="panel"><h2>Check any original month</h2><p>Choose an original checkpoint to open its P&amp;L and month-end Trial Balance. February–December 2026 start with no posted activity; your practice entries can change those reports.</p><div class="sample-months"><?php foreach ([2024,2025,2026] as $year): ?><details><summary><?= $year ?> monthly reports</summary><ul><?php foreach ($pack['checkpoints'] as $point): ?><?php if (str_starts_with($point['from'], (string) $year)): ?><li><?= pl_e(substr($point['from'], 0, 7)) ?> · <a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => $point['from'], 'to' => $point['to']])) ?>">P&amp;L</a> · <a href="<?= pl_e(pl_url('/reports/trial-balance', ['as_of' => $point['to']])) ?>">Trial Balance</a> · original profit <?= pl_e(pl_money($point['profit'])) ?></li><?php endif; ?><?php endforeach; ?></ul></details><?php endforeach; ?></div></section>
    <p class="small muted">Original pack <?= pl_e($pack['id']) ?> · version <?= pl_e($pack['version']) ?> · 36 month-end checkpoints verified when provisioned. <?php if (pl_demo_enabled()): ?>Use Leave demo and start again to choose another company. Each new visitor receives separate books; all access expires at the next hourly reset.<?php endif; ?></p>
</section>
