<?php declare(strict_types=1); ?>
<?php if (($pack['kind'] ?? '') === 'starter_playground'): ?>
<section class="page-wrap sample-guide">
    <header class="page-heading"><div><p class="eyebrow">Your private practice books</p><h1>Accounting starter playground</h1><p>Try a purchase, an invoice and partial payments. Follow the same figures through stock, outstanding balances and the general ledger.</p></div><a class="button primary" href="<?= pl_e(pl_url('/purchasing', ['new' => '1'])) ?>">Create a purchase order <?= pl_icon('arrow-right') ?></a></header>
    <div class="panel sample-overview"><div><strong><?= pl_e(substr($pack['start_date'], 0, 4)) ?> · Open practice year</strong><p>Your sample began with zero balances, no unpaid documents and no stock. Use a date in this year for practice entries.</p></div><div><strong>Ready to enter your own examples</strong><p>Sample customer and supplier has both roles. Sample goods uses one stock location; Sample service needs no stock. Receivables, payables, purchasing and inventory are ready.</p></div></div>
    <p class="notice sample-note">All names and amounts are fictional. <?= pl_e($pack['notice']) ?> Do not enter real customer or financial data.</p>
    <?php if (isset($pack['scenario']) && is_array($pack['scenario'])): ?><section class="panel sample-scenario" aria-labelledby="scenario-title"><p class="eyebrow">Industry teaching scenario · <?= pl_e($pack['status'] === 'preview_only' ? 'Preview only' : 'Bookkeeping example') ?></p><h2 id="scenario-title"><?= pl_e($pack['scenario']['title'] ?? 'Bookkeeping review') ?></h2><p><?= pl_e($pack['scenario']['goal'] ?? '') ?></p><div class="form-grid"><div><h3>Suggested path</h3><ol><?php foreach (($pack['scenario']['steps'] ?? []) as $step): ?><li><?= pl_e($step) ?></li><?php endforeach; ?></ol></div><div><h3>Review boundaries</h3><ul><?php foreach (($pack['scenario']['checks'] ?? []) as $check): ?><li><?= pl_e($check) ?></li><?php endforeach; ?></ul></div></div></section><?php endif; ?>

    <div class="sample-journeys">
        <article class="panel"><p class="eyebrow">1 · Buy and receive</p><h2>Start with five items</h2><p>Create an order for <strong>5 Sample goods at 10.00 each</strong>. Confirm it, then receive the five items using <strong>2100 · Goods received awaiting bills</strong>. Stock is now worth 50.00.</p><p>From the receipt, preview and post the supplier bill for the same quantity and net price. Choose tax-exclusive prices and <strong>DEMO5</strong> for an illustrative 2.50 tax and a 52.50 payable.</p><p><a href="<?= pl_e(pl_url('/purchasing', ['new' => '1'])) ?>">Open purchasing</a> · <a href="<?= pl_e(pl_url('/inventory')) ?>">Check stock and its ledger balance</a></p></article>
        <article class="panel"><p class="eyebrow">2 · Invoice and collect</p><h2>Sell two items</h2><p>Invoice <strong>2 Sample goods at 25.00 each</strong>, using tax-exclusive prices and DEMO5. Posting records a 52.50 receivable and the cost of the goods sold. Record a partial receipt of 25.00, then the remaining 27.50.</p><p>For a simpler first invoice, use <strong>Sample service</strong>; it needs no purchase or stock receipt. Posted documents offer linked credit notes and traceable corrections.</p><p><a href="<?= pl_e(pl_url('/ar', ['new' => '1'])) ?>">Create an invoice</a> · <a href="<?= pl_e(pl_url('/ar')) ?>">Review receivables and ageing</a></p></article>
        <article class="panel"><p class="eyebrow">3 · Pay and reconcile</p><h2>Follow what remains</h2><p>Open the posted supplier bill and pay 20.00 through <strong>1000 · Cash and bank</strong>. Review the remaining 32.50 payable. After the two-item sale, three goods remain with a 30.00 carrying value.</p><p>Compare the open-item and stock totals with their ledger accounts. Keep dates and the selected <?= pl_e($company['currency']) ?> currency consistent. Bank-file imports remain disabled in the public demo.</p><p><a href="<?= pl_e(pl_url('/ap')) ?>">Open payables</a> · <a href="<?= pl_e(pl_url('/reports/trial-balance')) ?>">Read the Trial Balance</a></p></article>
    </div>
    <section class="panel"><h2>Your prepared chart and controls</h2><p>1100 is receivables; 2000 is payables; 1300 is stock; 2100 is received goods awaiting bills; 5100 is cost of goods sold. The separate synthetic input/output tax accounts use the manually configured DEMO5 rate. 5200 is available when a reviewed purchase variance or currency rounding adjustment is needed.</p><p>Account, product, tax, module and user administration are locked in the public demo. The prepared examples let you try financial workflows without changing those controls.</p></section>
    <p class="small muted">This playground has no historical balances. The eleven historical sample companies remain separate choices. Each visitor receives separate books and access ends at the next hourly reset. The default capacity is 100 source and operation records; linked actions can use several records. Leave the demo and start again to choose a different sample.</p>
</section>
<?php return; endif; ?>
<section class="page-wrap sample-guide">
    <header class="page-heading"><div><p class="eyebrow"><?= pl_e($pack['business']) ?> · Your private practice books</p><h1><?= pl_e($pack['name']) ?></h1><p>Two years of history. A new year to practise. Follow a figure to its source, then try an editable draft.</p></div><a class="button primary" href="<?= pl_e(pl_url('/transactions', ['status' => 'draft'])) ?>">Open the three practice drafts <?= pl_icon('arrow-right') ?></a></header>
    <div class="panel sample-overview"><div><strong>2024–2025 · Historical periods closed</strong><p>The original history is reconciled month by month. Closed periods reject new postings. The 2024 annual period and twelve 2025 monthly periods do not overlap.</p></div><div><strong>2026 · Open practice year</strong><p>January is posted; February has three editable drafts. Choose a date in 2026 for your own entries. The original pack has 74 source records, leaving 26 new records at the default demo limit.</p></div></div>
    <p class="notice sample-note">All names and amounts are fictional. <?= pl_e($pack['notice']) ?></p>

    <div class="sample-journeys">
        <article class="panel"><p class="eyebrow">1 · Daily checks</p><h2>Where did the money go?</h2><p>On <strong>15 January 2026</strong>, the bank receipt summary records <strong><?= pl_e(pl_money($pack['monthly_support'][24]['bank_receipts'])) ?> <?= pl_e($company['currency']) ?></strong>. Open its source, then inspect the primary bank's movements for that day.</p><ul><li><a href="<?= pl_e(pl_url('/transactions/detail', ['id' => $sourceIds['receipt']])) ?>">Read the January receipt</a></li><li><a href="<?= pl_e(pl_url('/reports/account', ['id' => $accountIds['1000'], 'from' => '2026-01-15', 'as_of' => '2026-01-15'])) ?>">Check that day's bank movements</a></li><li><a href="<?= pl_e(pl_url('/reports/account', ['id' => $accountIds['1030'], 'from' => '2026-01-01', 'as_of' => '2026-02-28'])) ?>">Compare petty cash before and after a draft</a></li></ul><p class="small muted">The receipt is an illustrative monthly summary dated on the 15th. Cash sales appear separately in the month-end support journal. Neither is an imported bank statement.</p></article>
        <article class="panel"><p class="eyebrow">2 · Monthly closing</p><h2>Check December's adjustments</h2><p>Read <strong>December 2025</strong> on its own. Inspect salaries, insurance released from prepayments, depreciation, and the <strong>550.00</strong> maintenance bill still unpaid at year end.</p><ul><li><a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2025-12-01', 'to' => '2025-12-31'])) ?>">December profit and loss</a></li><li><a href="<?= pl_e(pl_url('/general-journals/detail', ['id' => $sourceIds['operations']])) ?>">Open December's support journal</a></li><li><a href="<?= pl_e(pl_url('/reports/account', ['id' => $accountIds['2000'], 'from' => '2025-12-01', 'as_of' => '2026-01-31'])) ?>">Follow the bill into January's payment</a></li></ul><p class="small muted">Closing a period prevents backdated posting. It does not certify statements or move profit into retained earnings. The Balance Sheet shows accumulated unclosed earnings once.</p></article>
        <article class="panel"><p class="eyebrow">3 · Quarterly and annual review</p><h2>Compare separate periods</h2><p>Compare each quarter of <strong>2025</strong>, then the two complete years. Quarter results add to the year's result. Use the same company and currency throughout.</p><ul><li><?php foreach ([['01-01','03-31','Q1'],['04-01','06-30','Q2'],['07-01','09-30','Q3'],['10-01','12-31','Q4']] as [$fromDate, $toDate, $label]): ?><a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2025-' . $fromDate, 'to' => '2025-' . $toDate])) ?>"><?= pl_e($label) ?></a> <?php endforeach; ?></li><li><a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2024-01-01', 'to' => '2024-12-31'])) ?>">2024 profit and loss</a> · <a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2025-01-01', 'to' => '2025-12-31'])) ?>">2025 profit and loss</a></li><li><a href="<?= pl_e(pl_url('/reports/balance-sheet', ['as_of' => '2025-12-31'])) ?>">2025 Balance Sheet</a> · <a href="<?= pl_e(pl_url('/reports/trial-balance', ['as_of' => '2025-12-31'])) ?>">2025 Trial Balance</a></li></ul><p class="small muted">Year-end loans have 3,600.00 principal outstanding. Equipment cost is 2,400.00 and accumulated depreciation is 920.00. Amounts use your chosen base currency; no foreign-exchange conversion occurs.</p></article>
    </div>

    <?php
    $sourceMaterial = is_array($pack['source_material'] ?? null) ? $pack['source_material'] : [];
    $researchEvidence = is_array($sourceMaterial['research_evidence'] ?? null) ? $sourceMaterial['research_evidence'] : null;
    $profile = is_array($researchEvidence['business_profile'] ?? null) ? $researchEvidence['business_profile'] : [];
    $verticalProfile = is_array($researchEvidence['industry_profile'] ?? null) ? $researchEvidence['industry_profile'] : [];
    $futureScenarios = is_array($researchEvidence['industry_scenarios'] ?? null) ? $researchEvidence['industry_scenarios'] : [];
    ?>
    <section class="panel sample-evidence" aria-labelledby="sample-evidence-title">
        <p class="eyebrow">Pinned sample evidence</p>
        <h2 id="sample-evidence-title">What this business example contains</h2>
        <?php if ($researchEvidence !== null): ?>
            <p><?= pl_e($profile['description'] ?? 'This profile is synthetic teaching material.') ?> The operational contract is shown as source evidence; it is not silently posted as an unsupported industry module.</p>
            <dl class="sample-evidence-grid">
                <div><dt>Source pack</dt><dd><?= pl_e((string) ($researchEvidence['source_pack_id'] ?? $pack['id'])) ?> · <?= pl_e((string) ($researchEvidence['source_pack_version'] ?? '1.0.0')) ?></dd></div>
                <div><dt>Source status</dt><dd><?= pl_e((string) ($researchEvidence['review_status'] ?? 'not recorded')) ?></dd></div>
                <div><dt>Vertical profile</dt><dd><?= pl_e((string) ($verticalProfile['name'] ?? 'Neutral bookkeeping')) ?></dd></div>
                <div><dt>Account vocabulary</dt><dd><?= count(is_array($verticalProfile['accounts'] ?? null) ? $verticalProfile['accounts'] : []) ?> profile accounts</dd></div>
                <div><dt>Contacts</dt><dd><?= count(is_array($researchEvidence['contacts'] ?? null) ? $researchEvidence['contacts'] : []) ?></dd></div>
                <div><dt>Products or services</dt><dd><?= count(is_array($researchEvidence['products'] ?? null) ? $researchEvidence['products'] : []) ?></dd></div>
                <div><dt>Locations</dt><dd><?= count(is_array($researchEvidence['locations'] ?? null) ? $researchEvidence['locations'] : []) ?></dd></div>
                <div><dt>Operational events</dt><dd><?= count(is_array($researchEvidence['operational_event_contract'] ?? null) ? $researchEvidence['operational_event_contract'] : []) ?></dd></div>
            </dl>
            <?php if ($verticalProfile !== [] && is_array($verticalProfile['distinct_controls'] ?? null)): ?><details><summary>Vertical controls represented by the profile</summary><ul><?php foreach ($verticalProfile['distinct_controls'] as $control): ?><li><?= pl_e((string) $control) ?></li><?php endforeach; ?></ul></details><?php endif; ?>
            <?php if ($futureScenarios !== []): ?><details><summary>Future or unsupported scenarios retained as evidence</summary><ul><?php foreach ($futureScenarios as $scenario): ?><li><strong><?= pl_e((string) ($scenario['id'] ?? 'scenario')) ?></strong> · <?= pl_e((string) ($scenario['status'] ?? 'future')) ?><?php if (isset($scenario['description'])): ?> — <?= pl_e((string) $scenario['description']) ?><?php endif; ?></li><?php endforeach; ?></ul></details><?php endif; ?>
        <?php else: ?>
            <p class="alert">This successor pack has no authored operational source pack yet. The generic ledger history is still synthetic and reconciled, but specialist business research remains a release blocker.</p>
        <?php endif; ?>
    </section>

    <section class="panel"><h2>Manual support schedules</h2><p>These authored schedules explain the general-ledger entries. They are examples to read, not operational payroll, customer/vendor subledgers or a stock module.</p>
        <dl class="sample-schedules"><div><dt>Staff and cash</dt><dd>Mira Vale: 600.00 per month; Noel Reed: 900.00. The 420.00 December 2024 bonus is paid in January 2025. Rent uses the reserve bank; utilities use 90.00 from the primary bank and 10.00 petty cash each posted month. No deductions or payroll tax are calculated.</dd></div><div><dt>Assets, prepayments and loan</dt><dd>Equipment: cost 2,400.00, illustrative 60-month life, zero residual, 40.00 monthly from February 2024. Insurance is prepaid 1,200.00 each January and released at 100.00 per posted month. A 6,000.00 loan starts in March 2024; each December payment has 1,200.00 principal and an illustrative 300.00 interest component.</dd></div><div><dt>Cross-year items</dt><dd>Alder Customer owes 800.00 on 31 December 2024 and pays in February 2025. Harbor maintenance is owed 550.00 on 31 December 2025 and paid in January 2026. The later settlements do not record the income or expense again.</dd></div><div><dt>Corrections</dt><dd><a href="<?= pl_e(pl_url('/general-journals/detail', ['id' => $sourceIds['correction']])) ?>">The 25.00 mistaken cost</a> is reversed in full on 20 August 2025. The separately referenced replacement records 45.00 on the following day. All three journal entries remain visible.</dd></div></dl>
        <?php if (isset($accountIds['1400'])): ?><p><strong>Manual stock example:</strong> Each posted month records <?= (int) $pack['monthly_support'][0]['units_in'] ?> units purchased and <?= (int) $pack['monthly_support'][0]['units_out'] ?> units sold at an illustrative <?= pl_e(pl_money($pack['monthly_support'][0]['unit_cost'])) ?> per unit. The stock account at December 2025 reconciles to the accumulated unsold units. POS practice does not deduct this stock or calculate cost of sales.</p><?php endif; ?>
        <details><summary>Read the 25 posted monthly support rows</summary><div class="sample-table-scroll" role="region" aria-label="Manual monthly support" tabindex="0"><table><caption>Original fixture support · <?= pl_e($company['currency']) ?> · exact source values have four decimal places</caption><thead><tr><th scope="col">Month</th><th scope="col">Gross receipts</th><th scope="col">Salaries</th><th scope="col">Insurance</th><th scope="col">Depreciation</th><th scope="col">Stock bought</th><th scope="col">Cost of sales</th></tr></thead><tbody><?php foreach ($pack['monthly_support'] as $row): ?><tr><th scope="row"><?= pl_e($row['month']) ?></th><?php foreach (['gross_receipts','salaries','insurance_release','depreciation','stock_purchases','cost_of_sales'] as $key): ?><td><?= pl_e(pl_money($row[$key])) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></details>
    </section>
    <section class="panel"><h2>Check any original month</h2><p>Choose an original checkpoint to open its P&amp;L and month-end Trial Balance. February–December 2026 start with no posted activity; your practice entries can change those reports.</p><div class="sample-months"><?php foreach ([2024,2025,2026] as $year): ?><details><summary><?= $year ?> monthly reports</summary><ul><?php foreach ($pack['checkpoints'] as $point): ?><?php if (str_starts_with($point['from'], (string) $year)): ?><li><?= pl_e(substr($point['from'], 0, 7)) ?> · <a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => $point['from'], 'to' => $point['to']])) ?>">P&amp;L</a> · <a href="<?= pl_e(pl_url('/reports/trial-balance', ['as_of' => $point['to']])) ?>">Trial Balance</a> · original profit <?= pl_e(pl_money($point['profit'])) ?></li><?php endif; ?><?php endforeach; ?></ul></details><?php endforeach; ?></div></section>
    <?php if (isset($pack['scenario']) && is_array($pack['scenario'])): ?><section class="panel sample-scenario" aria-labelledby="scenario-title"><p class="eyebrow">Industry teaching scenario · <?= pl_e($pack['status'] === 'preview_only' ? 'Preview only' : 'Bookkeeping example') ?></p><h2 id="scenario-title"><?= pl_e($pack['scenario']['title'] ?? 'Bookkeeping review') ?></h2><p><?= pl_e($pack['scenario']['goal'] ?? '') ?></p><div class="form-grid"><div><h3>Suggested path</h3><ol><?php foreach (($pack['scenario']['steps'] ?? []) as $step): ?><li><?= pl_e($step) ?></li><?php endforeach; ?></ol></div><div><h3>Review boundaries</h3><ul><?php foreach (($pack['scenario']['checks'] ?? []) as $check): ?><li><?= pl_e($check) ?></li><?php endforeach; ?></ul></div></div></section><?php endif; ?>
    <p class="small muted">Original pack <?= pl_e($pack['id']) ?> · version <?= pl_e($pack['version']) ?> · 36 month-end checkpoints verified when provisioned. <?= pl_e($pack['capability_note'] ?? 'This is a synthetic bookkeeping example, not a complete industry system.') ?> <?php if (pl_demo_enabled()): ?>Use Leave demo and start again to choose another company. Each new visitor receives separate books; all access expires at the next hourly reset.<?php endif; ?></p>
</section>
