<?php
declare(strict_types=1);
$v=$form['input'];
$settingsInput=($v['action']??'')==='settings'?$v:[];
$codeInput=($v['action']??'')==='code'?$v:[];
$rateInput=($v['action']??'')==='rate'?$v:[];
?>
<section class="page-wrap starter-detail">
<?php pl_starter_header('Tax codes and rates','Country-neutral codes with dated rates and frozen document amounts.',$form,$company); ?>
<p class="starter-note">Choose whether entered prices include or exclude tax. Documents show net, tax and total separately. Select a code on each taxable invoice or bill line. The rate effective on the document date is shown in the saved draft. Input tax uses the explicitly configured recoverable tax account. No country rules, forms or e-filing are included.</p>
<section class="panel"><h2>Price entry setting</h2><p>Current default: <strong><?= $settings['price_mode']==='inclusive'?'Prices include tax':'Prices exclude tax' ?></strong>. This applies to new documents. Existing documents retain their saved price mode.</p>
<?php if ($company['role']==='owner'): ?><form method="post" action="<?= pl_e(pl_url('/tax')) ?>"><?php
pl_starter_form($company,'settings',['revision'=>$settingsInput?($settingsInput['revision']??''):$settings['revision'],'request_key'=>$settingsInput['request_key']??null]);
pl_starter_select('Entered prices','price_mode',['exclusive'=>'Exclude tax (tax added)','inclusive'=>'Include tax (tax extracted)'],$settingsInput['price_mode']??$settings['price_mode']);
pl_starter_field('Reason','reason',$settingsInput['reason']??'');
?><button class="button primary">Save price setting</button><?php if ($settingsInput): ?><a class="button secondary" href="<?= pl_e(pl_url('/tax')) ?>">Reload saved setting</a><?php endif; ?></form><?php else: ?><p>Only the company owner can change the price entry setting.</p><?php endif; ?></section>
<?php if (pl_can_write($company)): ?><section class="panel"><h2>Create tax code</h2><form method="post" action="<?= pl_e(pl_url('/tax')) ?>"><?php pl_starter_form($company,'code',['request_key'=>$codeInput['request_key']??null]); ?><div class="starter-grid">
<?php pl_starter_field('Code','code',$codeInput['code']??''); pl_starter_field('Name','name',$codeInput['name']??''); pl_starter_select('Treatment','treatment',['standard'=>'Standard rate','zero'=>'Zero-rated','exempt'=>'Exempt'],$codeInput['treatment']??'standard'); pl_starter_select('Output tax liability account','sales_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['type']==='liability'&&$a['role']===null)),$codeInput['sales_account_id']??''); pl_starter_select('Recoverable input tax asset account','purchase_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['type']==='asset'&&$a['role']===null)),$codeInput['purchase_account_id']??''); pl_starter_field('Reason','reason',$codeInput['reason']??''); ?></div><button class="button primary">Create tax code</button></form></section>
<section class="panel"><h2>Add dated rate</h2><p>A new effective date applies until the next dated rate. A revision for the same date supersedes it for new drafts; existing posted documents remain unchanged.</p><form method="post" action="<?= pl_e(pl_url('/tax')) ?>"><?php pl_starter_form($company,'rate',['request_key'=>$rateInput['request_key']??null]); ?><div class="starter-grid"><?php pl_starter_select('Tax code','tax_code_id',pl_starter_options($codes),$rateInput['tax_code_id']??''); pl_starter_field('Effective from','effective_from',$rateInput['effective_from']??'','date'); pl_starter_field('Percentage','percentage',$rateInput['percentage']??''); pl_starter_field('Reason','reason',$rateInput['reason']??''); ?></div><button class="button primary">Record dated rate</button></form></section><?php endif; ?>
<section class="panel starter-report"><h2>Rate history</h2><table class="data-table"><thead><tr><th>Code</th><th>Effective from</th><th>Percentage</th><th>Revision</th><th>Reason</th></tr></thead><tbody><?php foreach ($rates as $row): ?><tr><td><?= pl_e($row['code']) ?></td><td><?= pl_e($row['effective_from']) ?></td><td><?= pl_e($row['percentage']) ?>%</td><td><?= (int)$row['revision'] ?></td><td><?= pl_e($row['reason']) ?></td></tr><?php endforeach; ?><?php if (!$rates): ?><tr><td colspan="5">No rates configured. No tax is added unless a code is explicitly selected.</td></tr><?php endif; ?></tbody></table></section>
</section>
