<?php declare(strict_types=1);
$v=$form['input']; $settingsInput=($v['action']??'')==='settings'?$v:[]; $codeInput=($v['action']??'')==='code'?$v:[]; $rateInput=($v['action']??'')==='rate'?$v:[];
$accountNames=pl_starter_options($accounts); $today=gmdate('Y-m-d'); $effective=[];
foreach ($rates as $rate) { if ($rate['effective_from']<=$today && !isset($effective[$rate['tax_code_id']])) { $effective[$rate['tax_code_id']]=$rate; } }
?>
<div class="flex flex-col gap-4 py-5">
<?php pl_ui_page_header('Tax codes','Country-neutral codes with dated rates and frozen document amounts',static function () use ($company,$codeInput,$accounts,$form): void {
if (pl_can_write($company)) { pl_ui_sheet('New tax code',static function () use ($company,$codeInput,$accounts,$form): void { ?>
<?php if ($codeInput && $form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
<form class="flex flex-col gap-4" method="post" action="<?= pl_e(pl_url('/tax')) ?>"><?php pl_starter_form($company,'code',['request_key'=>$codeInput['request_key']??null]);
pl_starter_field('Code','code',$codeInput['code']??''); pl_starter_field('Name','name',$codeInput['name']??''); pl_starter_select('Treatment','treatment',['standard'=>'Standard rate','zero'=>'Zero-rated','exempt'=>'Exempt'],$codeInput['treatment']??'standard');
pl_starter_select('Output tax liability account','sales_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['type']==='liability'&&$a['role']===null)),$codeInput['sales_account_id']??'');
pl_starter_select('Recoverable input tax asset account','purchase_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['type']==='asset'&&$a['role']===null)),$codeInput['purchase_account_id']??''); pl_starter_field('Reason','reason',$codeInput['reason']??''); ?>
<p class="text-xs text-ink-muted">Code definitions are retained as created. Add dated rates after saving. For a different treatment or posting account, create a new code.</p><button class="btn btn-primary">Create tax code</button></form>
<?php },(bool)$codeInput,'btn btn-primary'); } }); ?>
<div class="alert alert-info"><div><strong>No national tax rules are inferred</strong><p>Codes, rates and accounts are entered manually. Select a code on each taxable invoice or bill line. Input tax uses the configured recoverable tax account. No country rules, forms or e-filing are included.</p></div></div>
<section class="rounded-panel border border-border bg-surface p-4"><h2 class="section-title mb-2">Price entry default</h2><p class="text-sm">Current default: <strong><?= $settings['price_mode']==='inclusive'?'Prices include tax':'Prices exclude tax' ?></strong></p><p class="text-xs text-ink-muted mt-1">Applies to new documents. Existing documents retain their saved price mode. Net, tax and total are shown separately.</p>
<?php if ($settingsInput && $form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
<?php if ($company['role']==='owner'): ?><form class="grid grid-cols-1 md:grid-cols-3 gap-3 items-end mt-3" method="post" action="<?= pl_e(pl_url('/tax')) ?>"><?php pl_starter_form($company,'settings',['revision'=>$settingsInput?($settingsInput['revision']??''):$settings['revision'],'request_key'=>$settingsInput['request_key']??null]); pl_starter_select('Entered prices','price_mode',['exclusive'=>'Exclude tax (tax added)','inclusive'=>'Include tax (tax extracted)'],$settingsInput['price_mode']??$settings['price_mode']); pl_starter_field('Reason','reason',$settingsInput['reason']??''); ?><button class="btn btn-secondary">Save price setting</button></form><?php if ($settingsInput): ?><a class="link" href="<?= pl_e(pl_url('/tax')) ?>">Reload saved setting</a><?php endif; else: ?><p class="text-sm mt-2">Only the company owner can change the price entry setting.</p><?php endif; ?></section>
<section><h2 class="section-title mb-2">Codes</h2><p class="text-xs text-ink-muted mb-2">Effective rates as of <?= pl_e(pl_date_label($today)) ?>. Code definitions are read-only; manage dated rates below.</p>
<?php pl_ui_table(['Code','Treatment','Effective rate','Output account','Input account','Actions'],static function () use ($codes,$effective,$accountNames,$company,$rateInput,$form): void { foreach ($codes as $code): $rate=$effective[$code['id']]??null; $input=(int)($rateInput['tax_code_id']??0)===(int)$code['id']?$rateInput:[]; ?>
<tr><td><span class="row-title"><?= pl_e($code['code']) ?></span><span class="row-sub"><?= pl_e($code['name']) ?></span></td><td><?= pl_e(['standard'=>'Standard rate','zero'=>'Zero-rated','exempt'=>'Exempt'][$code['treatment']]) ?></td><td class="amount"><?= $rate?pl_e($rate['percentage']).'%':'Not configured' ?><?php if ($rate): ?><span class="row-sub">Since <?= pl_e(pl_date_label($rate['effective_from'])) ?></span><?php endif; ?></td><td><?= pl_e($accountNames[$code['sales_account_id']]??('Account '.$code['sales_account_id'])) ?></td><td><?= pl_e($accountNames[$code['purchase_account_id']]??('Account '.$code['purchase_account_id'])) ?></td><td>
<?php if (pl_can_write($company)) { pl_ui_sheet('Manage rates · '.$code['code'],static function () use ($company,$code,$input,$form,$accountNames): void { ?>
<dl class="dgrid mb-4"><?php foreach (['Code'=>$code['code'],'Name'=>$code['name'],'Treatment'=>$code['treatment'],'Output account'=>$accountNames[$code['sales_account_id']]??('Account '.$code['sales_account_id']),'Input account'=>$accountNames[$code['purchase_account_id']]??('Account '.$code['purchase_account_id'])] as $label=>$value): ?><div class="dgrid-row"><dt><?= pl_e($label) ?></dt><dd><?= pl_e($value) ?></dd></div><?php endforeach; ?></dl>
<p class="text-xs text-ink-muted mb-4">These code fields are read-only. A new effective date applies until the next dated rate. A revision for the same date supersedes it for new drafts; posted documents retain their original snapshots.</p>
<?php if ($input && $form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
<form class="flex flex-col gap-4" method="post" action="<?= pl_e(pl_url('/tax')) ?>"><?php pl_starter_form($company,'rate',['request_key'=>$input['request_key']??null,'tax_code_id'=>$code['id']]); pl_starter_field('Effective from','effective_from',$input['effective_from']??'','date'); pl_starter_field('Percentage','percentage',$input['percentage']??''); pl_starter_field('Reason','reason',$input['reason']??''); ?><button class="btn btn-primary">Record dated rate</button></form>
<?php },(bool)$input,'btn btn-ghost btn-sm'); } else { echo 'Read-only'; } ?></td></tr>
<?php endforeach; if (!$codes): ?><tr><td colspan="6">No tax codes yet. No tax is added unless a code is explicitly selected.</td></tr><?php endif; },'Tax codes and current effective rates'); ?></section>
<section><h2 class="section-title mb-2">Rate history</h2><?php pl_ui_table(['Code','Effective from','Percentage','Revision','Reason'],static function () use ($rates): void { foreach ($rates as $row): ?><tr><td><?= pl_e($row['code']) ?></td><td><?= pl_e(pl_date_label($row['effective_from'])) ?></td><td class="amount"><?= pl_e($row['percentage']) ?>%</td><td><?= (int)$row['revision'] ?></td><td><?= pl_e($row['reason']) ?></td></tr><?php endforeach; if (!$rates): ?><tr><td colspan="5">No rates configured. No tax is added unless a code is explicitly selected.</td></tr><?php endif; },'Tax rate history'); ?></section>
</div>
