<?php
declare(strict_types=1);
$statusLabels = ['draft' => 'Drafts', 'posted' => 'Posted', 'reversed' => 'Reversed', 'all' => 'All transactions'];
$selectedStatus = $filters['status'];
$scopeQuery = $filters;
?>
<div class="flex flex-col gap-4 py-5">
<?php pl_ui_page_header('Receipts & expenses', $list['total'] . ' records · ' . $company['currency'] . ' ' . pl_money($list['total_amount']), static function () use ($company, $filters): void { ?>
    <a class="btn btn-ghost" href="<?= pl_e(pl_url('/reports/account')) ?>"><?= pl_icon('book-2') ?> Account ledger</a>
    <?php if (pl_can_write($company)): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/transactions/new', ['return_filters'=>$filters])) ?>"><?= pl_icon('plus') ?> New transaction</a><?php endif; ?>
<?php }); ?>
<div class="split-view <?= $detailOnly ? 'transaction-record-view' : '' ?>">
<section class="split-view-list<?= $detailOnly || isset($_GET['id']) ? ' has-detail' : '' ?>" aria-label="Transaction list">
    <nav class="tabs-seg mb-3" aria-label="Transaction status"><?php foreach ($statusLabels as $key => $label): ?><a class="tabs-seg-item" href="<?= pl_e(pl_url('/transactions', array_replace($scopeQuery, ['status' => $key, 'page' => 1]))) ?>" <?= $selectedStatus === $key ? 'aria-current="page"' : '' ?>><?= pl_e($label) ?></a><?php endforeach; ?></nav>
    <form class="filter-bar mb-3" action="<?= pl_e(pl_url('/transactions')) ?>" method="get">
        <input type="hidden" name="status" value="<?= pl_e($selectedStatus) ?>">
        <?php pl_ui_list_controls($filters); ?>
        <label><span class="sr-only">Transaction type</span><select class="select" name="kind"><option value="all">All types</option><option value="expense" <?= $filters['kind'] === 'expense' ? 'selected' : '' ?>>Expenses</option><option value="receipt" <?= $filters['kind'] === 'receipt' ? 'selected' : '' ?>>Receipts</option></select></label>
        <button class="btn btn-secondary" type="submit">Filter</button>
        <details class="date-filters"><summary>Date range</summary><div><label>From <input type="date" name="from" value="<?= pl_e($filters['from']) ?>"></label><label>To <input type="date" name="to" value="<?= pl_e($filters['to']) ?>"></label><button class="btn btn-secondary" type="submit">Apply dates</button></div></details>
        <?php if ($filters['q'] || $filters['from'] || $filters['to'] || $filters['kind'] !== 'all'): ?><a class="clear-filter" href="<?= pl_e(pl_url('/transactions', ['status' => $selectedStatus])) ?>">Clear filters</a><?php endif; ?>
    </form>
    <div class="transaction-table table-wrap"><table class="table">
        <caption class="sr-only">Choose a transaction to inspect its details</caption>
        <thead><tr><?php foreach (['date'=>'Date / reference','name'=>'Name','amount'=>'Amount','status'=>'Status'] as $key=>$label): ?><th scope="col"<?= $key === 'amount' ? ' class="num"' : '' ?>><?php pl_ui_sort('/transactions', $filters, $key, $label); ?></th><?php endforeach; ?></tr></thead>
        <tbody><?php foreach ($list['documents'] as $row): $selected = $document && (int) $document['id'] === (int) $row['id']; ?>
        <tr class="<?= $selected ? 'selected' : '' ?>"><td><a class="record-link" href="<?= pl_e(pl_url('/transactions/detail', array_replace($scopeQuery, ['id' => $row['id']]))) ?>" <?= $selected ? 'aria-current="true"' : '' ?> data-record-link><strong><?= pl_e(pl_date_label($row['date'])) ?></strong><span class="muted"><?= pl_e($row['number']) ?></span></a></td><td><span class="payee"><?= pl_e($row['counterparty'] ?: 'No name entered') ?></span><span class="muted row-secondary"><?= pl_e(ucfirst($row['kind'])) ?></span></td><td class="amount"><?= pl_e(pl_money($row['amount'])) ?></td><td><?php pl_ui_badge($row['status']); ?></td></tr>
        <?php endforeach; ?></tbody>
    </table>
    <?php if (!$list['documents']): ?><div class="empty-state"><?= pl_icon('receipt') ?><h2><?= $selectedStatus === 'draft' ? 'A clear place to start.' : 'No matching transactions.' ?></h2><p><?= $selectedStatus === 'draft' ? 'Record money in or money out. Review the balanced entry before it reaches your books.' : 'Try another status or adjust your filters.' ?></p><?php if (pl_can_write($company)): ?><a href="<?= pl_e(pl_url('/transactions/new')) ?>" class="btn btn-primary">Record your first transaction</a><?php endif; ?></div><?php endif; ?>
    </div>
    <div class="list-footer"><span><?= (int) $list['total'] ?> records · Total <strong><?= pl_e($company['currency'] . ' ' . pl_money($list['total_amount'])) ?></strong></span><div class="pagination"><?php if ($list['page'] > 1): ?><a class="icon-button" aria-label="Previous page" href="<?= pl_e(pl_url('/transactions', array_replace($scopeQuery, ['page' => $list['page'] - 1]))) ?>"><?= pl_icon('chevron-left') ?></a><?php endif; ?><span>Page <?= (int) $list['page'] ?> of <?= max(1, (int) $list['pages']) ?></span><?php if ($list['page'] < $list['pages']): ?><a class="icon-button" aria-label="Next page" href="<?= pl_e(pl_url('/transactions', array_replace($scopeQuery, ['page' => $list['page'] + 1]))) ?>"><?= pl_icon('chevron-right') ?></a><?php endif; ?></div></div>
    <?php if ($company['is_sample']): ?><p class="sample-note"><?= pl_icon('info-circle') ?> These are synthetic records in a separate sample company.</p><?php endif; ?>
</section>
<section class="transaction-detail split-view-detail" aria-label="Transaction details">
<?php if ($document): ?>
    <a class="split-view-back" href="<?= pl_e(pl_url('/transactions', $scopeQuery)) ?>"><?= pl_icon('arrow-left') ?> Back to list</a>
    <?php if ($form['message']): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><strong>We couldn't complete that action.</strong><p><?= pl_e($form['message']) ?></p></div><?php endif; ?>
    <div class="detail-heading"><div><div class="inline-heading"><h2><?= pl_e($document['number']) ?></h2><span class="badge <?= pl_e($document['status']) ?>"><?= pl_e(ucfirst($document['status'])) ?></span></div><h3><?= pl_e($document['counterparty'] ?: ucfirst($document['kind'])) ?></h3></div><p class="detail-amount"><?= pl_e($company['currency']) ?> <strong><?= pl_e(pl_money($document['amount'])) ?></strong></p></div>
    <?php pl_ui_tabs(['Details'=>'#record-details','Journal'=>'#record-journal','History'=>'#record-history'], 'Details', true); ?>
    <section id="record-details" data-ui-tab-panel><dl class="record-details"><div><dt><?= $document['kind'] === 'expense' ? 'Paid to' : 'Received from' ?></dt><dd><?= pl_e($document['counterparty'] ?: '—') ?></dd></div><div><dt>Reference</dt><dd><?= pl_e($document['reference'] ?: '—') ?></dd></div><div><dt>Date</dt><dd><?= pl_e(pl_date_label($document['date'])) ?></dd></div><div><dt><?= $document['kind'] === 'expense' ? 'Paid from' : 'Received into' ?></dt><dd><?= pl_e($document['money_account_name']) ?></dd></div><div><dt>Category</dt><dd><?= pl_e($document['category_account_name']) ?></dd></div><div><dt>Memo</dt><dd><?= pl_e($document['memo'] ?: '—') ?></dd></div></dl></section>
    <section id="record-journal" class="journal-section" data-ui-tab-panel><div class="section-heading"><h3><?= $document['status'] === 'draft' ? 'Posting preview' : 'Posted journal' ?></h3><span class="balanced-label"><?= pl_icon('check') ?> Balanced</span></div>
        <?php $entryLines = $document['journal'] ? $document['journal']['lines'] : $document['journal_preview']['lines']; require __DIR__ . '/../partials/entry.php'; ?>
        <p class="muted small"><?= $document['status'] === 'draft' ? 'Posting adds this transaction to reports. A saved draft does not change your books.' : 'This entry is included in your reports. Posted financial details are preserved.' ?> <?php if ($document['journal_id']): ?><a href="<?= pl_e(pl_url('/journals/detail', ['id' => $document['journal_id']])) ?>">Open journal <?= pl_e($document['journal']['reference']) ?></a><?php endif; ?></p>
    </section>
    <section id="record-history" class="history-section" data-ui-tab-panel><h3 class="section-title">History <span class="muted">· Revision <?= (int) $document['revision'] ?></span></h3><dl class="record-details"><div><dt>Created</dt><dd><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $document['created_at']) . 'Z') ?>"><?= pl_e($document['created_at']) ?> UTC</time></dd></div><div><dt>Last saved</dt><dd><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $document['updated_at']) . 'Z') ?>"><?= pl_e($document['updated_at']) ?> UTC</time></dd></div></dl><?php if ($document['reversal_journal_id']): ?><p><a href="<?= pl_e(pl_url('/journals/detail', ['id' => $document['reversal_journal_id']])) ?>">Inspect the linked reversal</a></p><?php endif; ?></section>
    <?php if (pl_can_write($company)): ?><div class="detail-actions panel-actions" data-fold="primary action">
        <?php if ($document['status'] === 'draft'): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/transactions/edit', ['id' => $document['id'], 'return_filters'=>$filters])) ?>">Edit draft</a><form method="post" action="<?= pl_e(pl_url('/transactions/post')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="id" value="<?= (int) $document['id'] ?>"><input type="hidden" name="revision" value="<?= (int) $document['revision'] ?>"><button class="btn btn-primary" type="submit" <?= $company['setup_status'] !== 'ready' ? 'disabled' : '' ?>>Post <?= pl_e($document['kind']) ?></button></form>
        <?php elseif ($document['status'] === 'posted'): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/reports/trial-balance')) ?>">See report effect</a><a class="text-button" href="#reverse-entry" data-open-details>Reverse transaction</a>
        <?php else: ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/reports/trial-balance')) ?>">View trial balance</a><span class="muted">Original and reversal retained</span><?php endif; ?>
    </div><?php endif; ?>
    <?php if ($document['status'] === 'posted' && pl_can_write($company)): ?><details class="reversal-form" id="reverse-entry" <?= $form['message'] ? 'open' : '' ?>><summary>Correct this entry with a reversal</summary><p>A reversal creates an opposite, linked entry on the date you choose. It preserves this transaction.</p><form method="post" action="<?= pl_e(pl_url('/transactions/reverse')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="id" value="<?= (int) $document['id'] ?>"><div class="form-grid"><label class="field">Reversal date<input type="date" name="date" value="<?= pl_e(pl_web_text($form['input'], 'date', gmdate('Y-m-d'))) ?>" required <?= !isset($form['input']['date']) ? 'data-local-today' : '' ?>></label><label class="field full-width">Reason<textarea name="reason" rows="2" maxlength="500" required><?= pl_e(pl_web_text($form['input'], 'reason')) ?></textarea></label></div><button type="submit" class="btn btn-secondary">Post linked reversal</button></form></details><?php endif; ?>
<?php else: ?><div class="empty-detail"><span class="detail-mark"><?= pl_icon('book') ?></span><h2>Every entry tells a story.</h2><p>Select a transaction to see where the money went and how it appears in your books.</p></div><?php endif; ?>
</section>
</div>
</div>
